/*
 * Wise World - Quiz data (English)
 * ⚠ AI translation from the Japanese source. Review by a native speaker /
 *    health expert is recommended before relying on it.
 * Keep id / answerIndex / emoji identical across all languages.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).en = [
  { id:1, topic:"Safe water", emoji:"💧",
    question:"Which water is safe and won't make your tummy hurt?",
    choices:["River water","Well water","Water boiled hard over a fire","Rain water"],
    answerIndex:2,
    explanation:"River water, well water, and rain water may look perfectly clear and clean, but they can be full of tiny living things too small for our eyes to see (germs and viruses). If you drink that water as it is, it can cause terrible stomach pain or a serious, life-threatening illness. But when you put water over a fire and boil it hard until it bubbles, the heat kills all of those harmful living things. That is why water that has been boiled well and then cooled is the safest water in the world, and the water you can drink with confidence." },
  { id:2, topic:"Washing hands", emoji:"🧼",
    question:"What should you do before eating?",
    choices:["Wash your hands with water and soap","Wipe your hands on your clothes","Do nothing","Touch the soil"],
    answerIndex:0,
    explanation:"Our hands touch many tools and the ground every day, so without noticing it we pick up many invisible germs. If you touch food with those hands, the germs move onto the food, and you swallow them into your body along with the food. Wiping your hands on dirty clothes, or just splashing them with water, will not remove the germs — they cling on. Only by using soap and scrubbing your palms, the backs of your hands, and between your fingers with a good lather, then rinsing with water, can you truly wash the germs away." },
  { id:3, topic:"Washing hands", emoji:"🚽",
    question:"What should you do after using the toilet?",
    choices:["Go and play right away","Wash your hands with water and soap","Rub your hands on your clothes","Wipe your hands on your trousers"],
    answerIndex:1,
    explanation:"After going to the toilet, very strong germs from stool and urine that cause disease stick to your hands easily. If you go off to play without washing, those germs get onto the doorknobs and toys you touch, and pass the illness to the next friend or family member who touches them. And if you touch your own mouth or eyes with those hands, you can make yourself sick too. No matter how much of a hurry you are in, always washing your hands well with water and soap after the toilet is a rule that protects your life and the lives of those around you." },
  { id:4, topic:"Health", emoji:"💧",
    question:"When your tummy is upset and your stool turns watery (diarrhoea), what matters most?",
    choices:["Eat a lot of food","Drink nothing","Drink plenty of safe water","Run around and play"],
    answerIndex:2,
    explanation:"When your tummy is upset and watery stool (diarrhoea) keeps coming out, precious water and nourishment are being lost from your body again and again. This is called dehydration. When the body runs short of water, the important functions that keep us alive begin to stop, and small children especially can suddenly lose their lives. When you have diarrhoea, rather than forcing down solid food, the best treatment is first to replace the water you have lost. By drinking safe, boiled-and-cooled water little by little, many times over, you can keep your strength and protect your life." },
  { id:5, topic:"Treating wounds", emoji:"🩹",
    question:"When you fall and bleed, what should you do first?",
    choices:["Put soil on it","Wash it well with clean water","Leave it alone and do nothing","Rub it with a leaf"],
    answerIndex:1,
    explanation:"When you fall and get a wound that bleeds, the wound is covered with dirt, mud, and dust from the ground, along with many germs. If you believe old sayings and smear soil on it, rub it with a dirty leaf, or just leave it alone, the germs go deep into the wound and multiply. Then the wound swells up red and hurts badly, and in the worst case an arm or leg can rot and stop moving. When you are hurt, the first correct step to keep a wound from becoming serious is to use clean, safe water nearby to rinse the mud and dirt off the wound with a strong flow." },
  { id:6, topic:"Food", emoji:"🦠",
    question:"What happens when food goes rotten (spoils)?",
    choices:["It becomes tasty","It rots and gives you a stomach ache","It becomes hard","Nothing changes"],
    answerIndex:1,
    explanation:"Food naturally holds a tiny number of invisible microbes from the start. In a cool place the microbes cannot be active, but if you leave food in a warm, hot place for a long time, it becomes the perfect environment for them, and within a few hours they multiply into millions — a frightening number. When microbes multiply this much and the shape and nature of the food change, we say it has gone rotten (spoiled). Rotten food holds the strong poison the microbes have made, so eating it brings severe stomach pain, diarrhoea, and nausea, and harms your body." },
  { id:7, topic:"Food", emoji:"👃",
    question:"What is a sign that food has gone bad?",
    choices:["A strange smell or taste","A red colour","Something cold","Something well cooked"],
    answerIndex:0,
    explanation:"You can use your own nose and tongue to check whether food has gone bad and is no longer safe. If it has an unusual sour smell or a sharp, unpleasant smell, or a strange taste when you put a little in your mouth, or if it is sticky and stringy, that is proof that germs have multiplied greatly and poison has formed. If you force yourself to eat it because it would be a waste, you put your life in danger from severe food poisoning. If the smell or taste is even a little suspicious, decide to throw it away and never swallow it." },
  { id:8, topic:"Food", emoji:"🪰",
    question:"What should you do with food a fly has landed on?",
    choices:["Eat it as it is","Don't eat the part the fly touched (throw it away)","Raise the fly as a pet","Stare at it"],
    answerIndex:1,
    explanation:"The insect we call a fly likes to walk around very dirty places full of germs, such as animal droppings, dead bodies, and rubbish dumps. Because of this, frightening disease-causing germs stick thickly to a fly's thin legs and body. When such a fly lands on our food, in that instant the germs on its legs move onto the food. If you eat the spot it touched, you are indirectly putting droppings and rubbish germs into your mouth, which can cause serious illness. Even if it feels wasteful, it is safer to cut away and throw out the part of the food the fly landed on." },
  { id:9, topic:"Preventing disease", emoji:"🦟",
    question:"What happens if you leave water standing for a long time?",
    choices:["The water becomes clean","Harmful mosquitoes multiply","Your money grows","Nothing happens"],
    answerIndex:1,
    explanation:"Old water that stays in one place without flowing becomes the perfect spot for the insect called the mosquito to lay its eggs. If you leave buckets, old tyres, or empty cans around your yard or house holding water, hundreds and thousands of new mosquitoes are born there and fly all around. When a mosquito sucks a person's blood, it injects into the body the germs of very frightening, life-threatening diseases such as malaria and dengue fever. Getting rid of pools of water around the house is an important plan to protect your family from these terrible diseases." },
  { id:10, topic:"Cleanliness", emoji:"✋",
    question:"When your nails are long, what builds up inside them?",
    choices:["Your hands get stronger","Black dirt and germs collect under the nails","Food tastes better","Nothing changes"],
    answerIndex:1,
    explanation:"When your fingernails grow long, black mud and dirt pack tightly into the narrow gap between the nail and the skin while you play in the soil, help out, or work. The dirt that gets into this gap does not come off easily with ordinary hand-washing, and it becomes the perfect hideout for germs. With long nails, when you eat with your hands or touch your own face or a wound, those hidden germs easily get into your body. Keeping your nails cut short at all times is a basic way to prevent illness." },
  { id:11, topic:"Cough manners", emoji:"🤧",
    question:"What should you do when you cough or sneeze?",
    choices:["Do it towards someone's face","Cover your mouth and nose with your hand or sleeve","Shout loudly","Do nothing"],
    answerIndex:1,
    explanation:"When you have a cold or a lung illness, a single cough or sneeze sends tiny droplets of water you cannot see flying out of your mouth and nose, several metres away with great force. Each droplet can contain tens of thousands of disease germs. If you cough towards someone's face you pass the illness directly, and if you cover nothing the germs spread through the air and everyone in the same room can get sick. When you cough, firmly covering your mouth and nose with your sleeve or hand keeps you from spreading illness to the precious family and friends around you." },
  { id:12, topic:"Cleanliness", emoji:"🗑️",
    question:"What happens if you leave rubbish lying near the house?",
    choices:["The house becomes clean","Harmful rats and insects gather and disease spreads","The rubbish turns into flowers","Nothing goes wrong"],
    answerIndex:1,
    explanation:"If you throw food scraps and kitchen rubbish away right next to your house, the smell draws many creatures such as rats, flies, and cockroaches. These creatures usually walk around sewers and filthy places, so they carry many frightening disease germs on their bodies. As they increase around the rubbish, they eventually get into the house and dirty the precious food and drinking water inside. Rubbish must be thrown away in a set place far enough from the house, or buried deep in a hole in the ground." },
  { id:13, topic:"Healthy teeth", emoji:"🪥",
    question:"What is the main reason for brushing your teeth?",
    choices:["To paint the teeth white","To reduce cavity germs in the mouth and protect the teeth","To make your jaw strong","To fill your stomach"],
    answerIndex:1,
    explanation:"After you eat, small scraps of food always remain in the gaps and on the surface of your teeth. The invisible creatures called cavity germs that live in our mouths love these food scraps. If you leave the scraps there, the cavity germs feed on them and make a strong acid that dissolves the teeth. Because of this acid, holes slowly open in the teeth — which should be the hardest part of the body — and when it reaches the nerve it brings pain so fierce you cannot sleep at night. Brushing your teeth after eating is absolutely necessary work to remove the germs' food and protect your teeth." },
  { id:14, topic:"Preventing injury", emoji:"👟",
    question:"Why do you wear shoes when you walk outside?",
    choices:["To make your feet bigger","To stop worms and germs in the soil from entering through the skin of your feet","To practise running","To keep your clothes clean"],
    answerIndex:1,
    explanation:"When you walk barefoot on soil and mud, tiny creatures hiding in the ground that are too small to see (the larvae of parasites) and germs can break through the soft skin of the soles of your feet and enter your body on their own. The worms that get in settle in your tummy (intestines) and steal the nourishment you eat, making you badly anaemic, stopping your growth, and draining your energy. Wearing shoes also protects you from serious injury caused by stepping on broken glass, sharp stones, or wooden thorns. Always wear shoes or sandals when you go outside." },
  { id:15, topic:"Cleanliness", emoji:"👕",
    question:"What happens if you keep wearing dirty clothes?",
    choices:["The clothes get stronger","Your skin gets itchy or you become ill","Your body gets stronger","Nothing changes"],
    answerIndex:1,
    explanation:"If you keep wearing clothes soaked with sweat or stained with mud for many days, mould and germs feed on the human sweat and skin oil on the clothes and multiply explosively inside the fibres. As those dirty clothes keep rubbing against your skin, the skin can swell up red, become very itchy, or develop a sore, oozing illness. Dirty clothes can be completely rid of germs by washing them clean with water and soap and drying them well in the sunlight (ultraviolet rays). Always wearing clean clothes is important for protecting the barrier of your skin." },
  { id:16, topic:"Cleanliness", emoji:"🚿",
    question:"What is good about washing your body?",
    choices:["Your skin gets clean and you prevent skin disease","You grow taller","Your hair falls out","You get hungry"],
    answerIndex:0,
    explanation:"Every day invisible oil (sebum) and sweat come out of human skin, and outside dust and soil mix in, making the whole body dirty. If you leave this dirt for many days, bad germs multiply on the surface of the skin, and you can get terrible boils or a frightening illness where the skin festers and rots. By regularly washing your whole body gently with water and soap and resetting the old oil and dirt, your skin is kept healthy and strong, building a powerful barrier that keeps illness from getting in from outside." },
  { id:17, topic:"Safe water", emoji:"💧",
    question:"When you only have muddy water, how can you drink it safely?",
    choices:["Drink it as it is","Filter out the mud with cloth or sand, then boil it over a fire","Just leave it in the sun and drink it","Drink only a little"],
    answerIndex:1,
    explanation:"When all you can get is muddy water, drinking it as it is sends a huge amount of germs into your body along with the mud and causes serious illness. Making it safe takes two pieces of wisdom. First, pass the water through fine, clean cloth, or a container packed with sand and small stones, to filter out the mud and large bits and make the water clear. But being clear is not enough — invisible germs are still alive. After that, you must put it over a fire and boil it hard until it bubbles, so the heat wipes out the germs and it finally becomes safe drinking water. With wisdom, you can make life-saving water even from muddy water." },
  { id:18, topic:"Babies", emoji:"🍼",
    question:"What is the best nourishment for a baby?",
    choices:["Cow's milk (raw)","The mother's milk (breast milk)","River water","Sugar water"],
    answerIndex:1,
    explanation:"A newborn baby's body is very weak and has almost no power to beat disease germs. A mother's milk (breast milk) not only holds perfect nourishment for the baby to grow, but also large amounts of a special protective ingredient called immunity that guards against illness. Breast milk also comes straight from the body, so it never touches dirty outside water or germs on containers — it is the cleanest and safest in the world. Other animals' raw milk, river water, or sugar water can wreck a baby's delicate stomach and intestines and take its life, so you must never give them." },
  { id:19, topic:"Preventing disease", emoji:"😷",
    question:"What should you do near someone with a bad cough?",
    choices:["Keep a little distance, and turn your face away when passing","Take a big breath in front of them","Shake hands with them","Stand right in front of them"],
    answerIndex:0,
    explanation:"Serious breathing illnesses such as tuberculosis (TB) float in the air for a long time, carried on the tiny invisible droplets that scatter when a sick person coughs. If you take a big breath nearby, or stay close for a long time, you breathe those germs deep into your own lungs and can catch the same serious illness. When someone has a bad cough, it is not about being unkind or treating them differently; to protect yourself, keep several metres of distance, and when passing, turn your face away and breathe out gently — this is the right way for both of you to stay safe." },
  { id:20, topic:"Fresh air", emoji:"🪟",
    question:"How do you keep the air in a room clean?",
    choices:["Shut all the doors and windows tight","Open windows and doors to let the air change","Everyone shout loudly together","Nothing changes"],
    answerIndex:1,
    explanation:"When many people gather in a small, closed room, the disease germs and viruses someone carries build up more and more in the air, until the air in the room is full of germs. If you stay in that room a long time, everyone breathes the dirty air and gets sick together (a group infection). By opening windows and doors in two or more places to exchange the fresh outside air with the dirty air in the room (ventilating), you can drive the germs out of the air and protect the health of everyone in the room." },
  { id:21, topic:"Levers", emoji:"🪨",
    question:"When you want to move a heavy stone buried in the ground using a long pole, where should you push hardest to move it with the least force?",
    choices:["The spot right next to the stone","The middle of the pole","The very far end of the pole, away from the stone","It is the same wherever you push"],
    answerIndex:2,
    explanation:"When you move something heavy with a pole, there is a rule called 'the lever principle': the farther you are from the small stone that acts as the support (the fulcrum), the less force you need to push with. If you push near the stone the pole will not budge, but if you grip the very far end of the pole and push by leaning your weight on it, you can lift a heavy stone with surprisingly little force. Knowing how a tool works like this lets you make your own strength many times greater and do heavy jobs easily." },
  { id:22, topic:"Levers", emoji:"⚖️",
    question:"When you lift a heavy load using a long pole, where should you place the small stone (the fulcrum) that supports the pole so it lifts most easily?",
    choices:["Right next to the heavy load","Right next to where you push with your force","Exactly in the middle of the pole","It is better not to place a small stone at all"],
    answerIndex:0,
    explanation:"When you lift something heavy with a pole, the position of the small supporting stone (the fulcrum) is very important. By placing this support right next to the heavy load, the load moves only a short distance, but the force you need to lift it becomes dramatically smaller. The other way around, if the support stone is close to you, no matter how hard you press you cannot lift the load. When you want to move something heavy, remember the wisdom of placing the support close to the thing you want to move." },
  { id:23, topic:"Rolling", emoji:"🪵",
    question:"When you move a heavy wooden box by dragging it along the ground, how can you move it most easily with the least force?",
    choices:["Lay several round, hard logs under the box and roll it","Just pull it with all your might","Pour water on top of the box","Smash the box hard against the floor"],
    answerIndex:0,
    explanation:"When you drag something heavy straight along the ground, a braking force called 'friction', made where the object rubs against the ground, works strongly, so it takes enormous force to move. But if you lay round, hard logs under the box, the motion changes from dragging to the logs rolling. Rolling has dozens of times less braking force than dragging, so even one person can move a heavy load smoothly. When the load moves forward, you take the logs that come out at the back and lay them in front again, a piece of wisdom humans have used since ancient times." },
  { id:24, topic:"Ramps", emoji:"🛝",
    question:"When you want to put a heavy load onto a high platform about chest height for an adult, which way of moving it puts the least strain on your body?",
    choices:["Stand in front of the platform and lift it straight up with all your might","Lean a long board against the platform at a slant to make a slope, and push it up","Throw the load at the platform from far away","Shave the platform down to make it lower"],
    answerIndex:1,
    explanation:"If you try to lift a heavy load straight up, you face head-on the force that pulls things down toward the earth (gravity), so you must support everything with your muscles alone, which hurts your back and arms. Here, if you lean a long board against the platform at a slant to make a slope (an inclined plane), the board comes to support most of the load's weight. Going up a slope, the distance you walk gets longer, but the force needed to push the load can be cut to less than half. When carrying things to a high place, always find a way to make a slope." },
  { id:25, topic:"Pulleys", emoji:"🪣",
    question:"When you pull a heavy bucket of water up from a deep well with a rope, what becomes easier if you fit a 'round wheel that spins (a pulley)' on the bar above the well and hang the rope over it?",
    choices:["The weight of the water becomes half as light","The amount of water increases on its own","You can raise the water just by pulling the rope downward","The rope will never break"],
    answerIndex:2,
    explanation:"When you hang a rope over the round wheel above the well (a fixed pulley), the weight of the water itself does not actually get lighter. But the wonderful thing about this tool is that it changes the direction in which you apply force. If you try to lift the rope straight up, you must raise it with the strength of your arms and back alone; but if you hang the rope over the round wheel and pull downward, you can put your whole body weight onto the rope. Being able to use your own body weight to pull heavy water up easily and safely is the wisdom of this round wheel." },
  { id:26, topic:"Wheel and axle", emoji:"🔄",
    question:"When you want to turn a screw that just will not turn, or a heavy well winch, how can you turn it most easily?",
    choices:["Turn it using a short, thin rod","Make the handle part large and long, and turn that","Turn it with just your fingertips, using no tool","Hit the screw hard with a hammer"],
    answerIndex:1,
    explanation:"When you want to turn an axle at the center, if you fit a large round handle or a long grip onto that axle, you can create a large turning force with a small effort. This is called the 'wheel-and-axle' principle. You cannot budge the thin part by turning it directly with your fingers, but when you turn the large outer handle, the distance your hand moves gets longer while the force on the axle becomes many times stronger. A machine that winds up a well rope, a doorknob at home, the screws on tools, every turning tool around you uses this wisdom." },
  { id:27, topic:"Center of gravity", emoji:"🏺",
    question:"There are people who walk skillfully with a heavy water jar or firewood balanced on top of their head. Why can they walk long distances without hurting their neck or back?",
    choices:["Because they walk bending their body far forward or backward","Because they keep their back perfectly straight and place the center of the load (its center of gravity) right above their bones","Because they constantly shake the load violently on their head","Because everyone is born with neck bones thicker than other people's"],
    answerIndex:1,
    explanation:"When you carry a heavy load in your hands, the strain falls on only one side of your body and your muscles tire quickly. But if you straighten your back perfectly and place the load right on top of your head, the weight at the center of the load (its center of gravity) passes straight down through the pillar of bones, from head to neck to spine, and out into the ground. Because the sturdy bones, not the muscles, support the weight, you can carry it safely over long distances without wasting muscle power, as long as you keep your balance. Keeping things close to the central axis of your body is important wisdom for not hurting yourself." },
  { id:28, topic:"Pressure", emoji:"🦶",
    question:"When you walk on a muddy road where, after rain, it turns to deep mud and your feet sink in, how can you walk more easily without sinking?",
    choices:["Walk on your tiptoes, making the soles of your feet as small as possible","Tie a flat, large wooden board to the soles of your feet and walk","Just shout loudly and run across","Carry a lot of luggage to make yourself heavier"],
    answerIndex:1,
    explanation:"The weight pressing on the ground concentrates more strongly in one spot and sinks in deeper, like a needle, the smaller the area touching it. This is called 'pressure.' Standing on tiptoe makes the area smaller, so you sink in even deeper. The other way around, if you attach a flat, large wooden board to the soles of your feet, your body weight is spread over a wide area, so the force pushing the ground down weakens and you can walk on the mud without sinking. Making the base of a heavy building wide and flat is the same wisdom for spreading out pressure." },
  { id:29, topic:"Carts", emoji:"🛒",
    question:"When you want to load a two-wheeled cart with lots of heavy luggage and pull it, where should you place the heavy things so it is lightest and easiest to pull?",
    choices:["Right next to your hands, by the handle","At the very back end of the cart","Right above the axle of the wheels","It is the same wherever you load it"],
    answerIndex:2,
    explanation:"When you pull a cart, the weight on your hands changes dramatically depending on where you place the load. If you load the heavy luggage near your hands, you end up running while lifting the load's weight directly with your arms, and tire quickly. If it is too far back, the cart tips over backward, which is dangerous. The correct answer is right above the axle of the wheels. If you load the heavy things here, the sturdy wheels and the ground support all of the weight, so almost no weight falls on your hands. Since you only need the force to pull it forward, you can carry a large load very easily." },
  { id:30, topic:"Blades", emoji:"🔪",
    question:"When you sharpen the tip of a hatchet for splitting firewood, or a kitchen knife for cutting food, by rubbing it on a stone (a whetstone), why does it cut better?",
    choices:["Because the tip of the blade gets thinner and finer, so the force concentrates in one spot","Because the blade gets hot and melts the food","Because the blade gets heavier","Because the blade becomes rounded"],
    answerIndex:0,
    explanation:"When something is cut by a blade, it happens because the force a person applies concentrates on the extremely narrow spot of the blade's tip and breaks through the object. When a blade gets old and rounded, the force spreads over a wide area, so no matter how hard you press it will not cut. Sharpening a blade is the work of shaving the rounded tip to make it as fine and thin as possible. Once the tip is fine, even a small force creates enormous pressure at that spot, so you can slice through hard firewood or food with a light touch. Caring for your tools is basic to saving your energy." },
  { id:31, topic:"Friction", emoji:"👟",
    question:"When you walk on a slope or on wet rocks, which is harder to slip on and safer: smooth, slippery shoes, or shoes with deep, spiky grooves on the sole?",
    choices:["Smooth, flat shoes","Shoes with deep, spiky grooves on the sole","It is the same whichever you wear","You slip less with no shoes at all"],
    answerIndex:1,
    explanation:"When the sole of a shoe rubs against the ground, a braking force called 'friction' works there to stop you slipping. If the sole is smooth, no braking works between it and the ground, and you slip and fall easily, especially where there is water or mud. If the sole has deep, spiky grooves, those grooves bite firmly into the bumps of the ground and create a strong braking force. Slipping and falling can lead to serious injury, but by knowing how friction works, choosing shoes with grooves on slippery ground or putting your whole sole firmly on the ground, you can act safely." },
  { id:32, topic:"Floating", emoji:"⛵",
    question:"A small pebble sinks in water, yet a wooden ship thousands of times heavier and bigger can float on the water. Why?",
    choices:["Because the ship is shaped like a bowl, holding lots of air and water inside","Because the ship gets a lot of wind","Because magic stones are painted on the ship's bottom","Because the ship is made of oil that is lighter than water"],
    answerIndex:0,
    explanation:"On an object in water, a mysterious force called 'buoyancy' works, pushing it upward by as much as the water it pushes aside. A pebble is packed solid inside and heavy, so the pebble is heavier than the water it pushes aside, and it sinks. But a large ship is shaped like a bowl, and inside it holds lots of air. Looked at as a whole, it becomes very light for its size, so the force of the water pushing up from below becomes stronger, and even a large ship can float on the water without tipping over." },
  { id:33, topic:"Triangles", emoji:"🔺",
    question:"When you build a house or a bridge out of wood or iron, why does shaping the frame into triangles make a very sturdy building that is hard to break?",
    choices:["Because it needs more material than a square","Because a triangle has the property that its shape never distorts even when strong force is applied from above","Because making triangles lets the wind pass through more easily","Because it is an old shape used as a charm from the gods"],
    answerIndex:1,
    explanation:"A building made of pillars joined only into squares easily collapses, with the joints bending limp, when strong force or the shaking of an earthquake is applied from above or the side. But if you add one slanted rod inside that square to make a triangle (a truss structure), then no matter which direction force comes from, the rods pull and push against each other so the shape does not distort at all. If you look at large bridges around the world, or the underside of building roofs, these triangles are always finely combined together. It is a wonderful building wisdom: even with little material, just by working out the shape you can make something many times sturdier." },
  { id:34, topic:"Inertia", emoji:"🐎",
    question:"When a running horse or cart slams on the brakes and stops dead, what happens to the luggage and people riding on top?",
    choices:["They tip over backward as they are","They are flung forward with great force","They jump straight up on the spot","Nothing happens; they stop dead too"],
    answerIndex:1,
    explanation:"In the universe there is a mysterious force called 'inertia': a moving thing tries to keep moving at the same speed. Even when a horse or cart suddenly stops, the people and luggage on top are still trying to keep going forward. So unless you brace your feet firmly or tie the luggage down with rope, you are flung forward with great force and badly hurt. When you stop something that is moving, or when you ride a fast vehicle, you must keep in mind that this force that tries to fling things forward is always at work, and prepare for safety." },
  { id:35, topic:"Scissors", emoji:"✂️",
    question:"When you want to cut a hard branch or thick cloth with scissors, at which part of the blade should you hold it to cut most easily with the least force?",
    choices:["At the very tip of the blade","At the base of the blade (closest to the screw or hinge)","At the middle of the blade","The force needed is the same wherever you cut"],
    answerIndex:1,
    explanation:"Scissors, too, are a very handy tool that uses the lever principle we have been learning. The screw where the two blades cross and are fixed becomes the support (the fulcrum). The closer to this supporting screw you cut, the many times stronger the force becomes that your gripping hand passes to the blade. So with something hard that will not cut, trying to cut at the scissor tip only makes your hand hurt, but if you grip it deep at the base of the blade, you can snip it off with surprisingly little force. Know the nature of your tools and use the most efficient spot." },
  { id:36, topic:"Gravity", emoji:"🍎",
    question:"Why is it that dropping a small pebble onto your foot from knee height, versus from the high roof of your house, the one dropped from the roof causes a worse injury?",
    choices:["Because the stone gets colder up on the roof","Because gravity, the force pulling things down toward the earth, makes the stone faster and faster the longer the drop, so the impact when it hits is stronger","Because a stone in a high place becomes bigger in size","Because the air pushes the stone down"],
    answerIndex:1,
    explanation:"Everything on the earth is constantly pulled by a force called 'gravity', drawn toward the ground. For something in a high place, the longer the drop, the more it keeps being pulled by gravity and speeds up faster and faster (it accelerates). An object that has sped up creates enormous destructive power (energy) the instant it hits the ground or your body. From knee height it only hurts, but something falling from a high roof or cliff, even a small stone or tool, becomes a weapon that can take a person's life. When you work near a high place, you must check that no one is below and take the greatest care not to drop anything." },
  { id:37, topic:"Balance", emoji:"⚖️",
    question:"When you carry two heavy water jars hung on the front and back of a single long pole (a carrying pole) on your shoulder, how can you walk easily without hurting your shoulder?",
    choices:["Make the front load very heavy and the back load light","Make the front and back loads exactly the same weight, and put the very middle of the pole on your shoulder","Do not put the pole on your shoulder; carry it with your hands only","Drop the loads to the ground alternately as you run"],
    answerIndex:1,
    explanation:"When you carry loads hung on each side of a long pole, if the front and back weights are uneven, the pole tilts to one side and you have to fight to hold it down with your hands. This tires not only your shoulder but your arms and back quickly. The correct answer is to make the front and back loads exactly the same balance. Then the weight presses evenly right above your shoulder through the carrying pole, and you can carry heavy loads just by walking, without using extra muscle to fight a tilt. If one load is unavoidably lighter, adjust the balance by sliding the rope of the lighter side toward the end of the pole." },
  { id:38, topic:"Air resistance", emoji:"🪂",
    question:"You have two sheets of paper of the same size and same weight. One is left as a flat sheet, the other is squeezed by hand into a tight ball. When you drop them at the same time from a high place, which lands on the ground first?",
    choices:["The flat sheet left as it is","The paper squeezed into a tight ball","Both land at exactly the same time","It changes every time depending on the wind"],
    answerIndex:1,
    explanation:"Even for things of the same weight, when they fall through the air a braking force called 'air resistance' works, with the air getting in the way. The flat sheet of paper has a wide area, so it catches a lot of the air beneath it and falls only slowly, like a parachute. But the paper squeezed into a small ball touches the air over a very narrow area, so it receives almost no braking and falls fast, pulled straight down by gravity. A windmill turning in the wind, or an umbrella nearly being blown away on a windy day, also have to do with this braking force of the air." },
  { id:39, topic:"Elasticity", emoji:"🏹",
    question:"When you bend a hard, sturdy bamboo or a supple tree branch with all your might and then let go, it springs back to its original shape with force. What can you use this property (elasticity) for to make a handy tool useful in daily life?",
    choices:["A refrigerator to keep food from rotting","A bow and arrow to shoot an arrow at distant prey, or a trap that flings heavy things","A filter to clean water","A tool to dye clothes white"],
    answerIndex:1,
    explanation:"Rubber and springs, and bamboo and tree branches too, have a mysterious property called 'elasticity': when you apply force their shape bends, and when you let go they try to return to their original shape at great speed. While you hold it bent by hand, the force a person applies is stored up inside that tool for a moment as energy. The instant you let go, that stored force is released all at once, so you can shoot an arrow many times farther, or work a trap, than by throwing with your arm alone. Using this power that natural plants have, humans have made tools for hunting and daily life since ancient times." },
  { id:40, topic:"Oiling", emoji:"🛢️",
    question:"The wheels of a cart, or a door's hinge, started making a nasty squeak-squeak sound and getting heavy every time you moved them. If you drip a few drops of oil here, why does it move smoothly again?",
    choices:["Because the oil melts the iron and makes it lighter","Because the oil hardens and becomes glue","Because the oil gets into the gap between metal and metal and dramatically reduces the rubbing braking force (friction)","Because the smell of the oil drives insects away"],
    answerIndex:2,
    explanation:"When a machine or tool moves, there are places where metal rubs hard and directly against metal. A very strong braking force called 'friction' works there, and if left alone it wears down and breaks, or it takes enormous force to move. When you apply oil, a thin film of oil forms in the tiny gap of the metal and keeps it from rubbing directly. Because the braking force suddenly disappears, the tool moves astonishingly smoothly with little force. Just by applying a little cooking oil or plant oil to a tool, the tool lasts longer and greatly reduces the wearing-out of a person's strength." },
  { id:41, topic:"Lightning", emoji:"⚡",
    question:"When thunder is rumbling and you are outside, where is the safest place to escape to?",
    choices:["Right under a tall tree","In the middle of a wide open field","Inside a sturdy building, or a car surrounded by metal","Standing while holding up a big umbrella"],
    answerIndex:2,
    explanation:"Lightning has a strong tendency to strike tall things. So if you stand alone in a wide open field, you become the tallest pointed thing around, and the danger of a direct strike becomes very high. Also, standing right under a tall tree is dangerous: lightning that hits the tree can jump across to your body, a phenomenon called a side flash, causing fatal injury. The safest places are inside a sturdy building made of concrete, or inside a car surrounded by metal panels. Even if lightning hits the car, the electricity flows through the outer metal and down into the ground, so the people inside are completely safe." },
  { id:42, topic:"Floods", emoji:"🌊",
    question:"In heavy rain the road has turned into a river, and you have no choice but to walk through the water to evacuate. What is the safest thing to wear on your feet?",
    choices:["Bare feet","Sandals","Shoes tied firmly with laces","Rubber boots"],
    answerIndex:2,
    explanation:"The bottom of a flooded road hides many invisible dangers: broken glass, sharp cans, open manhole holes. With bare feet or sandals you easily injure your feet and can no longer move. Rubber boots may look good, but once water gets in from the top they become heavy like water-filled pillows, your feet cannot lift at all, and you cannot walk or even drown. The safest are shoes that do not slip off and have a hard sole: sneakers tied firmly with laces. They do not get heavy even when water enters, and they protect your feet while letting you walk steadily." },
  { id:43, topic:"Evacuation", emoji:"⛰️",
    question:"A flood from heavy rain or a tsunami has come, and water is rushing up to your feet. Which direction is it right to flee?",
    choices:["Downstream where the water flows fast (a low place)","A nearby high hill or mountain, or an upper floor of a sturdy building (a high place)","A relative's house far away","Your home's basement (lower than the ground)"],
    answerIndex:1,
    explanation:"In a flood or tsunami, water fills up with tremendous force, starting from the lowest places. If you hide in a basement lower than the ground, water pours in from the entrance all at once, you cannot get out, and you drown. Also, trying to flee far away by wandering around, you may be hit by drifting trees or cars, or have your feet swept out by the fierce flow and be carried away. When water closes in, the rule is not to go far, but to head for the nearest high place from where you are now. Climbing a nearby hill or mountain, or the 2nd or 3rd floor of a sturdy concrete building, and waiting for the water to recede, is the choice that protects your life." },
  { id:44, topic:"Heatstroke", emoji:"🥵",
    question:"On a very hot day when the sunlight is extremely strong, what is the most important thing to prevent the illness where your body overheats and you collapse (heatstroke)?",
    choices:["Endure it without drinking any water","Smear cold mud all over your body","Rest in the shade, and drink safe water little by little, many times","Run a lot to sweat it out"],
    answerIndex:2,
    explanation:"If you stay in a very hot place for a long time, the water and salt in your body leave as sweat, and your body can no longer lower its own heat. This is the frightening condition called heatstroke. To prevent it, it is important to find cool shade where the sunlight does not hit you directly, and rest your body. And you need to drink safe, boiled-and-cooled water little by little, many times over, even before you feel thirsty. Rather than gulping a lot at once, drinking in small frequent sips lets your body absorb water well, so you can stay healthy and safe even under the hot sun." },
  { id:45, topic:"Earthquakes", emoji:"🪑",
    question:"When an earthquake hits and the ground and your house start shaking violently, what is the first thing to do inside the room?",
    choices:["Panic and rush outside","Hide under a sturdy desk and protect your head and body","Shut the windows tight and look outside","Stuff a lot of things into a bag"],
    answerIndex:1,
    explanation:"When an earthquake hits, the most dangerous things are objects falling from above and furniture toppling over. If you panic and rush outside, broken glass and roof tiles can fall from the upper parts of buildings and hit your head, a very high risk of serious injury. When you feel shaking, first crawl under a sturdy desk or bed right where you are, grip the desk legs firmly, and protect your head and body. If there is nowhere to hide, cover your head tightly with a cushion, a bag, or your own arms, make yourself small in the middle of the room where furniture will not fall on you, and wait quietly until the shaking completely stops, that is safest." },
  { id:46, topic:"Lightning", emoji:"⚡",
    question:"When thunder is rumbling nearby, which action is the most dangerous to do while outside?",
    choices:["Holding a plastic toy","Holding a long metal pole or fishing rod up high toward the sky","Wearing cloth clothes","Wearing wooden shoes"],
    answerIndex:1,
    explanation:"Lightning has a frightening tendency to strike intensively at things that are tall and have a pointed tip. So if you are outside holding a long metal pole, a fishing rod, or a long umbrella thrust up high toward the sky, it becomes like an antenna calling the lightning, and you get struck directly. When you hear thunder rumbling, immediately lay any long pole you are holding down flat on the ground, lower your own posture as much as possible, and crouch with your head down. Then evacuate into a safe building right away." },
  { id:47, topic:"Landslides", emoji:"⚠️",
    question:"When heavy rain keeps falling near a mountain, which is a dangerous sign that the mountain might collapse (a landslide)?",
    choices:["The river water suddenly turns pitch-black and muddy, and lots of wood chips flow down","Small stones come tumbling down from the mountain bit by bit","A strange rumbling sound, like the ground groaning, comes from deep underground","All of these are dangerous signs"],
    answerIndex:3,
    explanation:"When heavy rain pours onto a mountain, the soil soaks up a huge amount of water, and at some moment the cliff or the whole mountain collapses all at once, a great disaster called a landslide or a debris flow. Just before these happen, nature always gives several warning signs. River water suddenly turning muddy with more driftwood is proof that soil is starting to collapse higher up. Also, if small stones fall from the mountain, or an eerie sound comes from the ground, it is a signal that the whole mountain is about to move. If you find or feel even one of these signs, you must leave that place even one second sooner and flee to a high, sturdy place." },
  { id:48, topic:"Floods", emoji:"🦯",
    question:"When you must walk through flood water, on a road where mud makes the ground completely invisible, how should you walk to be safe?",
    choices:["Run at full speed to escape quickly","Use a long pole to tap and check the ground is safe, one step at a time","Close your eyes and go straight ahead","Take off all your clothes and swim"],
    answerIndex:1,
    explanation:"After a flood, the road water is muddy brown with mixed-in mud and rubbish, so you cannot see at all what the ground is like. In fact, under the water a manhole cover may have come off leaving a deep hole, or the ground may have eroded into a deep ditch. If you run or walk without noticing, you can fall into a deep hole in an instant and sink underwater. When walking through water, always hold a long, sturdy pole like a cane, and before taking the next step, tap the ground with the pole to check whether there is a hole, advancing slowly and carefully, that is the way of walking that protects your life." },
  { id:49, topic:"Tornadoes", emoji:"🌪️",
    question:"When a tornado (an intense wind spinning around at tremendous speed) approaches, where in the house is the safest place to hide?",
    choices:["Right next to a window with a good view outside","On the rooftop where the wind feels nice","A sturdy room with no windows, or a toilet or closet in the center of the house","Lying down on a big bed"],
    answerIndex:2,
    explanation:"A tornado is the most violent gust on Earth, strong enough to blow off a house roof or whirl big trees and cars into the air. When a tornado approaches, the most frightening thing is flying objects smashing through the window glass, scattering glass shards around the room at tremendous speed. So being near a window means serious injury. The safest place is where the walls are thickest and there are absolutely no windows: a toilet, a sturdy room, or a closet in the center of the house. Shut yourself in there, cover your head with a cushion or blanket, curl up small, and wait quietly for the storm to pass, that is the right way to hide." },
  { id:50, topic:"Fire", emoji:"🔥",
    question:"When a fire breaks out and a lot of smoke builds up in the room, how should you escape outside?",
    choices:["Stand up tall and run at full speed","Get into a low posture, crawling on the floor, cover your mouth with cloth, and escape","Shut all the windows to trap the smoke","Pull a big blanket over yourself and sleep in bed"],
    answerIndex:1,
    explanation:"The smoke produced by a fire contains a lot of harmful poison (such as carbon monoxide) that makes a person faint the instant they breathe it in. Because smoke is hot, it builds up in the room starting from the ceiling (the high area) first, and relatively clean air remains last near the floor. So if you stand up tall, you breathe in the thickest poisonous smoke head-on and can no longer move. When escaping, keep a low posture with your chest near the floor, press a wet cloth or clothing firmly over your mouth and nose, breathe the air near the floor, and quickly get outside, that is the right way to escape." },
  { id:51, topic:"Tsunami", emoji:"🌊",
    question:"When you are near the sea and feel a violent earthquake, what is the most important thing you must do immediately?",
    choices:["Go to see if there are fish in the sea","Return home to gather all your belongings","Get away from the coast and quickly climb a high mountain or sturdy high ground","Sit still on the sandy beach"],
    answerIndex:2,
    explanation:"When a large earthquake occurs under the sea, the seabed moves greatly, and all the surrounding water surges in as a huge wall-like wave, a great disaster called a tsunami. Unlike ordinary waves, a tsunami has tremendous weight and destructive power, enough to sweep away buildings and houses in an instant. Also, before a tsunami arrives, the tide may suddenly pull back and reveal the sandy bottom, but if you go to look at it for fun, the next moment you are swallowed by the great wave. If you feel shaking near the sea, take nothing, get away from the sea even one second sooner, and flee to a high hill or mountain, or an upper floor of a sturdy building. Once you can see the wave, it is too late to escape." },
  { id:52, topic:"Cold", emoji:"🧥",
    question:"When you might get lost in a freezing cold place in winter, what is the best action to keep your body warm and survive?",
    choices:["Drink a lot of cold water","Stay in your wet clothes as they are","Hide where the wind does not hit you, and put on many layers of clothes or cloth","Lie down and sleep directly on the snow"],
    answerIndex:2,
    explanation:"The human body, if its temperature drops too much, can no longer move and loses its life (hypothermia). Especially wind and wet clothes are dangerous enemies that steal heat from the body in an instant. To protect yourself in a cold place, the top priority is to hide where the wind absolutely does not hit you, such as behind a big rock or inside a building. Then, if your clothes are wet, be sure to change into dry ones, and put on many layers of the clothes, cloth, or paper you have. Layering cloth creates a layer of warm air between the layers, a magic wall that keeps your body heat from escaping. Sleeping directly on snow steals your heat, so spreading grass or cardboard on the ground to sit on is also important wisdom." },
  { id:53, topic:"Volcanoes", emoji:"🌋",
    question:"When a nearby volcano (a mountain that spews hot fire and mud) suddenly erupts, how do you protect yourself from the ash and stones flying from the sky?",
    choices:["Look up at the sky and watch carefully what is falling","Go inside a sturdy building (such as a concrete house) and cover your mouth and nose with cloth","Jump into a nearby river and swim","Run at full speed toward the mountain"],
    answerIndex:1,
    explanation:"When a volcano erupts, heavy red-hot lava and big stones come down from the sky at frightening speed from the summit. If these hit your head it is life-threatening, so you must hide right away inside a sturdy building made of concrete or the like. Also, the volcanic ash that the volcano spews out is not ordinary sand but like fine, crushed glass thorns. Breathing it in injures your lungs so you cannot breathe, and getting it in your eyes causes strong pain so you cannot open them. Once inside the building, shut the windows tight, cover your mouth and nose firmly with a mask or a water-dampened cloth, and protect yourself from ever breathing in the filthy ash." },
  { id:54, topic:"Fog", emoji:"🌫️",
    question:"When fog (white haze spreading through the air) becomes extremely thick and you cannot see ahead at all, what is the most dangerous thing about walking?",
    choices:["Stopping where you are","No longer being able to hear the sounds around you","Not being able to see your own position or dangerous places like cliffs, so you get lost or fall","Your clothes getting a little damp and wet"],
    answerIndex:2,
    explanation:"When thick fog forms, even the scenery just a few meters ahead turns pure white and you can see nothing. If you force yourself to keep walking in this state, your sense of direction, of where you are heading, becomes completely paralyzed, and it can lead to serious accidents: wandering into a dangerous deep forest, or failing to notice a deep cliff or river right in front of you and plunging straight down to your death. When you cannot see ahead, you must never push on. The safest defense is to stop where you are in a place with sure footing, such as the middle of a safe wide road, and wait quietly until the fog clears and you can see around you well again." },
  { id:55, topic:"Cliff collapse", emoji:"🪨",
    question:"When you are near a high wall of earth (a cliff) after heavy rain has fallen, what must you absolutely be careful of?",
    choices:["The rainwater may soak into the cliff and it may suddenly collapse (a cliff collapse), so get away immediately","Climb up onto the cliff and play happily","Pitch a tent right under the cliff and sleep","Pour lots of water at the cliff wall"],
    answerIndex:0,
    explanation:"A cliff or old earthen slope after heavy rain has a huge amount of water packed to the limit inside the soil, and it is in a very fragile, sponge-like soggy state. Even after the rain stops, hours to days later, a cliff collapse frequently happens where the whole wall suddenly crumbles down as if exploding, with no sound at all. If you play or sleep at the foot of the cliff, you get buried under many tons of heavy earth in an instant and cannot be saved. During heavy rain, and for several days after the rain stops, you must always keep the rule: never go near a high earthen wall or cliff, get away immediately." },
  { id:56, topic:"Evacuation", emoji:"🏃",
    question:"When the river near your house is rising more and more in heavy rain and is about to overflow, when should you start evacuating?",
    choices:["After water has come into the house","Early, while it is still light outside and no water has built up on the road, while it is safe","Wait quietly until the river water completely overflows","Think about it after getting into bed and sleeping"],
    answerIndex:1,
    explanation:"Trying to evacuate after the river overflows and water starts building up on the road is the most dangerous, too-late decision. When water builds up to knee height on the road, even a grown man is swept away by the strong force of the water and cannot walk at all. Also, once it gets dark at night, you can no longer tell where the road is and where the river is, and you fall into the river and are carried away on the way to evacuate. The most correct timing to start evacuating is while it is still light outside and no water has built up at your feet, while it is safe. The moment you sense even a little danger from the rising river, keep your belongings to a minimum and set out early toward a high, safe shelter, that is the wisdom that surely protects your life." },
  { id:57, topic:"Electric shock", emoji:"🔌",
    question:"After an earthquake or heavy rain, you find a broken electric wire in the house giving off sparks. Why must you absolutely not touch it?",
    choices:["Because your hands will get dirty with black mud","Because the strong electricity flowing in the wire flows into your body and causes serious injury, such as your heart stopping (electric shock)","Because the wire is cold like ice","Because the room will go pitch dark"],
    answerIndex:1,
    explanation:"From a broken wire, or from an electrical appliance wet with water, very strong electricity invisible to the human eye may be leaking out. If you touch it with your hand without knowing, the electricity in the wire shoots through your body in an instant and flows down into the ground. This is called electric shock. Receiving strong electricity not only burns your body but can make your heart stop dead, a fatal accident in an instant. Especially when your body or hands are wet with water, electricity flows into your body many times more easily, which is even more dangerous. If you find a sparking wire or a snapped wire, never go near it, never touch it, and report it to an adult." },
  { id:58, topic:"Typhoons", emoji:"🌀",
    question:"When a fierce strong wind (a typhoon or cyclone) is blowing, why is going outside dangerous enough to be life-threatening?",
    choices:["Because the air outside does not taste very good","Because shop signboards, roof tiles, and big tree branches fly at you and hit your head","Because your favorite clothes get dirty with mud","Because getting strong wind all over your body makes you fat"],
    answerIndex:1,
    explanation:"In a fierce storm like a typhoon or cyclone, the force of the wind becomes far beyond what humans imagine. Being blown away by the wind itself is dangerous, but the most frightening thing is everything in town becoming a weapon and flying at you. Heavy shop signboards, hard roof tiles, broken tree branches and the like come flying sideways at a speed like a sharp knife or a bullet. If even one of these hits your body, it is a fatal injury. While you can hear the sound of strong wind, no matter what business you have, you must absolutely not go outside. Staying in a safe house away from windows and waiting quietly for the storm to completely pass is the right action." },
  { id:59, topic:"Sandstorms", emoji:"🏜️",
    question:"When a sandstorm (sand and dust whirled up by strong wind) happens, what should you do to protect your eyes and lungs?",
    choices:["Open your eyes and mouth wide and take in the wind","Cover your face, mouth, and nose firmly with a scarf or cloth, and hide inside a sturdy building","Go outside and run races with your friends","Look up at the sky to see how far the sand flies"],
    answerIndex:1,
    explanation:"A sandstorm that happens near a desert or in a dry region is a great storm that whirls up hundreds of millions of fine sand grains and filthy dust with strong wind. If you breathe this sand and dust in as it is, sand builds up deep in your lungs and you cough violently, becoming a serious illness where you cannot breathe. Also your eyes can be injured by sand so you cannot see. When a sandstorm approaches, evacuate inside a sturdy building right away and close the windows and doors with no gaps. Then, layer the scarf or clothing cloth you have many times over and cover your whole face, especially your mouth and nose, tightly to make a mask that blocks the sand from getting in. Until the storm passes, protect yourself by quietly breathing only the air that comes through the cloth." },
  { id:60, topic:"Floods", emoji:"🌊",
    question:"During a flood where muddy water surges into the house, why is being in the basement (a room lower than the ground) absolutely not allowed?",
    choices:["Because the basement is cooler and more comfortable than other rooms","Because muddy water from the road above pours in all at once like a waterfall, the exit gets blocked, and you drown in an instant","Because the basement goes pitch dark when the power goes out","Because small rats sometimes live in the basement"],
    answerIndex:1,
    explanation:"A basement or semi-basement room lower than the ground turns into the most life-threatening, most dangerous place in the world when a flood occurs. The muddy water that has overflowed onto the road above pours in all at once through the basement's stairs and windows with the tremendous force and weight of a waterfall. The force of the water flowing down the stairs is intense, and even an adult's strength cannot resist it to climb up. Furthermore, the weight of the water pushes the basement door from outside, and it becomes absolutely impossible to open from inside. The room fills with water in an instant, the escape route is completely lost, and you drown. When the rain gets heavy, the absolute iron rule is: never go near the basement, climb to an upper floor right now." },
  { id:61, topic:"Division", emoji:"🍎",
    question:"There are 10 apples. If you share them equally among 5 people, how many does each person get?",
    choices:["1 apple","2 apples","3 apples","5 apples"],
    answerIndex:1,
    explanation:"Sharing things equally among everyone is the idea of 'division.' To share 10 apples equally among 5 people, first give everyone 1 apple — that uses up 5 apples. You still have 5 apples left, so you can give everyone 1 more apple each. Now all 10 apples are gone, and each person is holding '2 apples.' So that nobody gets more while someone else feels sad with less, the wisdom of counting carefully and sharing fairly is a very important power for living together in peace." },
  { id:62, topic:"Multiplication", emoji:"🍬",
    question:"You buy 3 snacks that cost 5 coins each. How much do you pay in total?",
    choices:["5 coins","8 coins","15 coins","20 coins"],
    answerIndex:2,
    explanation:"A calculation where the same number is repeated over and over is called 'multiplication.' Three snacks at 5 coins each means 5 is added three times. 5 plus 5 is 10, and adding one more 5 makes 15 in total. When you shop, if you cannot do this calculation, you may be charged more than you should and be cheated without even noticing. Knowing how multiplication adds up the same number at once becomes a powerful weapon to protect your precious money and to trade and live correctly." },
  { id:63, topic:"Subtraction (change)", emoji:"🪙",
    question:"You go to a shop with 10 coins and buy a fish for 7 coins. How much change (money you get back) do you receive?",
    choices:["2 coins","3 coins","5 coins","7 coins"],
    answerIndex:1,
    explanation:"Taking away what you spent from the whole amount you have is called 'subtraction.' When you pay the shopkeeper 7 coins out of your 10, you work out what is left by taking 7 from 10. Counting down from 10 one at a time — 9, 8, 7, 6, 5, 4, 3 — leaves 3. This leftover money is called 'change.' If you cannot work out the change yourself after shopping, you can lose out, for example by being given too little change. Mastering subtraction is the first step to living independently without being cheated in society." },
  { id:64, topic:"Counting by swapping", emoji:"📦",
    question:"You load cargo onto a cart. One box weighs the same as 3 small stones. If there are 3 boxes, how many stones is that in total?",
    choices:["3 stones","6 stones","9 stones","12 stones"],
    answerIndex:2,
    explanation:"This is the wisdom of replacing a total weight with another measure — here, the number of stones. One box is 3 stones, so 3 boxes means 'three sets of 3 stones.' 3 plus 3 is 6, and adding 3 more makes 9. When you can calculate not just the number of items you see but 'how heavy they really are' by swapping them for something else, you can keep a cart from breaking under too much load, and carry things in a planned way without overburdening an ox or a horse." },
  { id:65, topic:"Pattern rule", emoji:"🔷",
    question:"A pattern puzzle. 'Circle, triangle, square, circle, triangle, square, circle, triangle' — what shape comes next?",
    choices:["Circle","Triangle","Square","Cross"],
    answerIndex:2,
    explanation:"This is a puzzle for finding the 'rule (pattern)' in how things are lined up. Looking closely at the order, you can see that three shapes — circle, triangle, square — repeat in the same order again and again. When one set of 'circle, triangle, square' finishes, the next 'circle, triangle, square' begins. The puzzle stops at 'circle, triangle,' so following the rule, the next one must be 'square.' Even in a world that looks random, careful observation often reveals hidden rules. Growing this brain power to find patterns makes you much better at predicting and planning for the future." },
  { id:66, topic:"Logic", emoji:"📏",
    question:"There are 3 sticks of different lengths (A, B, C). A is longer than B. B is longer than C. Which stick is the longest?",
    choices:["Stick A","Stick B","Stick C","All the same length"],
    answerIndex:0,
    explanation:"This is a 'logical thinking' puzzle where you organize information in your head to reach the right answer. First, from 'A is longer than B,' we know A is above B. Next, from 'B is longer than C,' we know B is above C. Linking these in a vertical line, the order is A at the top, B in the middle, and C at the bottom. Therefore the longest is 'Stick A.' Even without the real objects in front of you, this power to build up words and conditions to find the correct answer is very useful for finding the cause of a problem and solving it wisely." },
  { id:67, topic:"Wisdom of dividing", emoji:"🍞",
    question:"A puzzle about sharing food equally. To divide one round loaf of bread into equal parts for '4 people,' how many straight cuts with a knife do you need?",
    choices:["1 cut","2 cuts","3 cuts","4 cuts"],
    answerIndex:1,
    explanation:"This is the wisdom of 'spatial awareness' — dividing a shape in your head. First cut the round bread straight through the middle '1 time,' and it splits into two halves. Then cut a '2nd time' straight through the middle, crossing the first cut like a plus sign, and the bread splits neatly into 4 equal pieces. With just 2 movements of the knife, you can share it equally among 4 people. Knowing the properties of shapes like this lets you divide things up efficiently and fairly, without wasted effort and without anyone feeling unhappy." },
  { id:68, topic:"Multiplication", emoji:"🐟",
    question:"You sell fish for money. Selling 1 fish earns 2 coins. If you sell 5 fish, how many coins do you earn in total?",
    choices:["2 coins","5 coins","7 coins","10 coins"],
    answerIndex:3,
    explanation:"This is multiplication, the basis of trade. You get 2 coins for each fish, so selling 5 fish means 2 coins gathered 5 times. Counting up by twos — 2, 4, 6, 8, 10 — gives 10 coins in total. When you work hard or sell what you have grown, if you cannot correctly work out 'how much it should come to,' a bad merchant can beat the price down and exploit you, leaving you with far less money than your labor is worth. The power to calculate numbers is a shield that protects the value of your work and lets you live a richer life." },
  { id:69, topic:"The tens place", emoji:"🔟",
    question:"A puzzle about groups of ten. There are boxes that each hold a 'group' of 10. If you have 3 of these boxes and 5 loose pieces, how many do you have in total?",
    choices:["8","15","35","53"],
    answerIndex:2,
    explanation:"The numbers we use every day follow a rule called the 'base-ten system,' where 10 gathered together carries over into the next larger place. Three boxes of 10 means 10, 20, 30 — that alone is 30. Adding the 5 loose pieces, 30 plus 5 makes 35. In many languages and trades around the world, things and money are counted in these 'groups of ten.' Once you can picture in your head how the boxes (the tens place) and the loose pieces (the ones place) work, even larger numbers like 100 or 1000 become easy to count and calculate." },
  { id:70, topic:"Step-by-step calculation", emoji:"🥚",
    question:"There are 8 eggs in a basket. You use 3 for cooking. After that, a hen lays 2 new eggs. How many eggs are in the basket now?",
    choices:["3","5","7","10"],
    answerIndex:2,
    explanation:"This is a puzzle where you do a 'two-step' calculation in order, as the number first goes down and then up. First, take the 3 eggs used for cooking away from the 8 you started with. 8 minus 3 is 5, so at this point the basket has 5. Then the hen lays 2 new eggs that are added to the basket, so now add 2 to 5. 5 plus 2 is 7. In daily life, complex changes like 'decreasing and then increasing' happen every day. When you can organize events in order in your head and combine addition and subtraction, you become very good at managing and planning the food in your home." },
  { id:71, topic:"Double", emoji:"🪣",
    question:"There is water in some buckets. Bucket A holds '2 times' as much as bucket B. Bucket B holds 4 liters of water. How many liters does bucket A hold?",
    choices:["2 liters","4 liters","6 liters","8 liters"],
    answerIndex:3,
    explanation:"'2 times (double)' a number means putting together another one the same as it — in other words, 'adding it twice' or 'multiplying by 2.' Bucket B holds 4 liters, and A is twice as big, so think of two lots of 4 liters. Calculating 4 plus 4 gives 8. So bucket A holds 8 liters. In daily life we often say 'twice the area,' 'twice the weight,' 'twice the people,' and knowing the idea of 'times' lets you compare amounts accurately and correctly estimate the tools or water a job needs." },
  { id:72, topic:"Order", emoji:"🧒",
    question:"5 children are standing in a straight line. Behind the child who is 3rd from the front, how many children are standing?",
    choices:["1 child","2 children","3 children","4 children"],
    answerIndex:1,
    explanation:"This is a logic puzzle about correctly grasping the relationship between the total number and a position in the middle. There are 5 children in all. Counting from the front — 1st, 2nd, 3rd — that accounts for 3 children, including the 3rd child themselves. Subtracting those 3 from the total of 5 leaves 2. So behind the 3rd child stand the 4th and the 5th child — '2 children.' The power to grasp order and position accurately with numbers is important wisdom for when you line up in a group to receive something, or to fairly keep your turn in society." },
  { id:73, topic:"Rule of shapes", emoji:"🔺",
    question:"A puzzle about the features of shapes. Which shape can you make by joining '3 straight sticks' together with no gaps?",
    choices:["Circle","Triangle","Square","Star"],
    answerIndex:1,
    explanation:"This is a puzzle about the basic rules for making shapes. Using 3 straight sticks (sides) and joining their ends together with no gaps, you always make a 'triangle' with 3 corners. With 4 sticks you get a square, and a circle is made of a curved line, not straight sticks. As we learned in the earlier mechanics pack, a triangle is the strongest shape in the world — it never distorts under force from above. Knowing the relationship between the number of sticks and the shape is the basis for building sturdy houses and designing safe supports for things." },
  { id:74, topic:"Number rule", emoji:"🔢",
    question:"A puzzle about how numbers grow. '2, 4, 6, 8, 10' are lined up. Following this rule, what number comes after 10?",
    choices:["11","12","13","15"],
    answerIndex:1,
    explanation:"This is a brain exercise for finding the 'rule (sequence)' where numbers grow by a fixed amount. Looking closely, from 2 to 4 it grows by '2.' From 4 to 6 it also grows by '2.' So this row of numbers follows the rule 'grow by 2 each step.' To find the number after 10, just add the rule's '2' to 10, so 10 plus 2 is 12. When you can see through laws where numbers grow or shrink by a fixed rule, it becomes very easy to predict the daily growth of a plant or to understand the rules of dates on a calendar." },
  { id:75, topic:"Half", emoji:"🫘",
    question:"You want to split the beans harvested from your field into 2 baskets, 'the same number each,' exactly in half. If there are 12 beans in all, how many should go in each basket?",
    choices:["4 each","6 each","8 each","12 each"],
    answerIndex:1,
    explanation:"Splitting a number into exactly two equal amounts is called 'half.' If you deal 12 beans into 2 baskets one at a time, taking turns, each basket gets the same number of beans. When you finish dealing them all out and count, each basket holds exactly '6 beans.' Since 6 plus 6 is 12, the half of 12 is 6. When you share food or a harvest with family and friends, being able to work out the half is a kind wisdom that prevents quarrels and lets you share fairly, caring for one another." },
  { id:76, topic:"Balance", emoji:"⚖️",
    question:"A puzzle comparing weights. On the left side of a 'balance scale' you place 1 apple, and it balances exactly when 4 small stones are on the right side. To match the weight of 2 apples, how many stones do you need in total?",
    choices:["2 stones","4 stones","6 stones","8 stones"],
    answerIndex:3,
    explanation:"This is the wisdom of calculating a balance of weights (a ratio). One apple weighs exactly the same as 4 stones. So what happens when the apples increase to 2? Since the apples have doubled, the number of stones needed to balance them must also double, or the balance breaks. In other words, you need another set the same as the 4 stones. Calculating 4 plus 4, or 4 times 2, the answer is 8. When buying and selling, the power to weigh and compare correctly is very important knowledge for avoiding being cheated with an unfairly small amount." },
  { id:77, topic:"Spotting a lie", emoji:"🧩",
    question:"A logic puzzle to find who is lying. There are two people, A and B. A says, 'I am not lying.' B says, 'A is lying.' If what A says is [true], is B lying, or telling the truth?",
    choices:["B is lying","B is telling the truth","Both are lying","Cannot tell"],
    answerIndex:0,
    explanation:"This is a slightly advanced logic puzzle for finding a contradiction in words. The puzzle's condition states that 'what A says is true.' That means A is an honest person who really is not lying. And yet B says, 'A is lying.' Since B is accusing the truthful A of being a liar, it is B's words that are 'wrong (a lie).' Therefore the answer is 'B is lying.' In society, the power to sort out in your head whose words are correct and whose contradict the facts is very important for protecting yourself." },
  { id:78, topic:"A good buy", emoji:"🪵",
    question:"A puzzle comparing which is the better deal. A shop sells 2 bundles of firewood. Bundle A has '5 sticks for 10 coins.' Bundle B has '3 sticks for 10 coins.' If you pay the same 10 coins, which one gives you more firewood and is the better deal?",
    choices:["Bundle A","Bundle B","Both are the same","Both are a loss"],
    answerIndex:0,
    explanation:"This is a shopping story about wisely comparing the 'amount' you get for the same price. Both A and B cost exactly the same '10 coins.' But choosing A gets you 5 sticks, while choosing B gets you only 3. Comparing 5 and 3, 5 is 2 more, so for the same money, buying A gets you more firewood and is the 'better deal.' Being able to judge for yourself which is a gain and which is a loss by comparing numbers when you shop is a great wisdom for using your limited money and resources carefully and making your life richer." },
  { id:79, topic:"How many more", emoji:"🏺",
    question:"There is a large water jar. It holds exactly '5 buckets' of water. Right now the jar already has 2 buckets of water in it. To fill the jar completely, how many more buckets of water do you need to add?",
    choices:["2 buckets","3 buckets","5 buckets","7 buckets"],
    answerIndex:1,
    explanation:"This is an application of subtraction — working out how much more (the difference) you need to reach a target amount. The total to fill the jar is 5 buckets. Since 2 buckets are already inside, to find the remaining empty space, take the current 2 from the total of 5. Calculating 5 minus 2, the answer is 3. So adding 3 more buckets fills the jar exactly without overflowing. In cooking, farming, and work, the power to figure out exactly 'how much more is needed' toward a goal is essential wisdom for avoiding waste and preparing efficiently." },
  { id:80, topic:"Speed", emoji:"⏱️",
    question:"A puzzle comparing times. Three friends — A, B, and C — had a race. The time each took to reach the goal was: A 10 seconds, B 8 seconds, C 12 seconds. Who was the 'fastest runner'?",
    choices:["A","B","C","All the same speed"],
    answerIndex:1,
    explanation:"This is a logic puzzle for correctly understanding what the numbers of time mean. In a race, being 'fast' means 'taking the shortest time (the smallest number)' to reach the goal. Someone who takes a lot of time ran that much more slowly. Comparing the three times — 12, 10, and 8 seconds — the smallest number is B's '8 seconds.' So because B reached the goal in the shortest time, B was the fastest. Understanding situations where a bigger number does not mean winning is also an important step of thinking in arithmetic and daily life." },
  { id:81, topic:"Discovery of fire", emoji:"🔥",
    question:"When ancient humans learned to use 'fire' well, what became the safest thing in their lives?",
    choices:["They could see far away even in the dark of night","By roasting meat and fish to eat, they prevented stomach illness and could protect themselves from wild beasts","They could wash their clothes clean","They could run faster"],
    answerIndex:1,
    explanation:"For ancient humans, discovering fire and learning to control it freely was the greatest advance for protecting life. Meat and plants that are hard and full of germs when raw could be turned into soft, easy-to-digest, safe food that does not upset the stomach by 'heating (cooking)' them with fire. Also, by keeping a fire crackling in the dark of night, the fearsome wild beasts that attack humans grow afraid of the fire and stop coming near, so people could sleep safely at night too. Fire was humanity's first and finest means of defense for surviving in harsh nature." },
  { id:82, topic:"The power of writing", emoji:"📜",
    question:"By inventing 'writing,' why did societies all over the world become wisest?",
    choices:["Your voice reaches a far-away person without speaking","Without having to keep it only in your head, you could pass important knowledge and laws (promises) accurately to many people over a long time","Drawing pictures became completely unnecessary","Writing letters makes money grow on its own"],
    answerIndex:1,
    explanation:"In the age before writing existed, humans had no choice but to memorize and pass on all wisdom and history only by 'word of mouth (telling stories).' But this way, the content could be forgotten partway or passed on wrongly. Here humans invented the wisdom of carving 'writing' into clay tablets and stone. With this, they could leave to descendants hundreds of years later, without the slightest error, things like how to tell safe plants apart, the rules of society everyone must keep (laws), and records of past mistakes. Writing is the greatest time machine for sharing and storing all of humanity's knowledge together, beyond the limits of human memory." },
  { id:83, topic:"The wheel", emoji:"🛞",
    question:"The 'wheel (a round tire)' invented long ago — why did it dramatically ease human travel and labor?",
    choices:["A round shape reduces the braking force (friction) of rubbing against the ground, so heavy loads can be rolled and carried with little force","Putting on wheels makes the load float into the sky","A lot of water collects inside the wheel","It looks cuter than square cargo"],
    answerIndex:0,
    explanation:"As we learned in the earlier mechanics pack, dragging something heavy straight along the ground creates a strong brake called 'friction.' But from the experience of 'rolling a round log,' humans came up with the wisdom of attaching a spinning round ring (a wheel) to a cart. With wheels, hundreds of kilograms of heavy firewood, stone, and food that even 10 adults could not move could be loaded onto a cart and carried smoothly far away by just 1 person. It was thanks to the invention of the wheel that humans could trade large amounts of goods with distant towns and develop a rich society." },
  { id:84, topic:"Invention of paper", emoji:"📄",
    question:"'Paper,' invented in ancient China, was wonderful compared to the stone, animal skins, and clay tablets used before it. Why?",
    choices:["It is very light and thin and can be folded, so large numbers of books could be made cheaply and carried around","Paper never tears even when it gets wet","Eating paper fills your stomach","It is harder to carve and sturdier than stone"],
    answerIndex:0,
    explanation:"Before paper was invented, people wrote letters on heavy 'stone' or 'clay tablets,' or on precious, expensive 'animal skins.' These were too heavy to carry far, so only a few very important or wealthy people could read books. But when 'paper' — made by pressing plant fibers flat and hardening them — appeared, books could be made astonishingly light, thin, cheap, and in large numbers. Thanks to this, doctors' knowledge and school textbooks reached ordinary people and children all over the world, and the level of education and medicine for all humanity rose explosively." },
  { id:85, topic:"Farming", emoji:"🌾",
    question:"When humans moved from a life of hunting for prey in the forest to tilling the land and starting 'farming,' how did life change?",
    choices:["Without traveling to dangerous far-off forests every day, they could keep living in one place (settle) and harvest plenty of food steadily","Since they no longer needed to run every day, everyone's body shrank","They no longer had to care about the weather at all","They stopped building houses and went back to caves"],
    answerIndex:0,
    explanation:"Before farming began, humans gathered nuts and chased animals, continuing a dangerous journey of moving to the next place when food ran out. But by inventing 'farming' — sowing seeds, watering, and growing plants in a planned way — humans could build sturdy houses and 'settle' in one place. Furthermore, because they could harvest and store large amounts of wheat and corn at once, the danger of starving to death decreased, and the foundation was laid for many people to join forces and build large villages and towns to live safely." },
  { id:86, topic:"The beginning of clothes", emoji:"🧵",
    question:"Why did humans start making their own 'clothes' by spinning plant fibers and sheep's wool?",
    choices:["To compete over beauty with friends and quarrel","To protect their own skin and body heat from strong sunlight, harsh cold, thorny grass, and insect poison","Because you cannot float on water unless you wear clothes","To hide lots of food inside their clothes"],
    answerIndex:1,
    explanation:"Human skin does not have sharp claws or thick fur like an animal's, so it is very delicate and easily hurt. Humans spun thread, wove 'cloth,' and made 'clothes' to wrap around the body in order to make defensive armor that protects life from harsh nature. Wearing clothes protects body heat from the freezing cold of winter, prevents burns from the strong summer sunlight, and guards against sharp thorns in the grass and bites from disease-carrying insects like mosquitoes. Clothing is a 'second skin' that humans created through wisdom, and an essential tool for acting safely." },
  { id:87, topic:"Shelter", emoji:"🏠",
    question:"What was the greatest purpose of leaving caves and building your own 'house (dwelling)' from mud, wood, and stone?",
    choices:["To make many rooms and play hide-and-seek","To reliably protect the family's lives and property from rain, wind, harsh heat and cold, and wild animals that attack at night","To dig into the ground and make many basements","To compete over house height and get closer to the gods"],
    answerIndex:1,
    explanation:"Living out in nature exposes you constantly to dangers like sudden heavy rain, freezing night winds, and wild meat-eating beasts that attack under cover of darkness. Humans began making bricks by drying mud in the sun, and building 'houses (dwellings)' by combining wood and stone, in order to shut out every danger of the outside world and secure a safe space. The roof keeps out rain and wind, and sturdy walls and a door shut out enemies. The wisdom of building one's own 'safe shelter,' where you can sleep soundly and rest an injured or sick body, has kept humanity alive." },
  { id:88, topic:"Iron tools", emoji:"⚒️",
    question:"By moving from stone tools to tools of 'iron and metal' melted in fire, what advanced?",
    choices:["Tools became light and floated on water","Instead of breaking apart easily like stone, very sturdy, sharp, long-lasting tools and farm implements could be made","Metal tools turn gold when polished","Tools became soft and changed shape freely"],
    answerIndex:1,
    explanation:"Axes and knives made of stone had a weakness: hit hard against something hard, they easily shattered to pieces. But humans discovered that when certain rocks are roasted in an extremely hot fire, a runny liquid (metal) melts out from inside, and when cooled it becomes far stronger than stone. This was the start of 'bronze' and 'iron tools.' Tools made of iron never broke even when dropped, and made it possible to cut down hard great trees and dig deep into hard ground to make fields. It was a wonderful revolution in technology that let people do stronger work safely with less force." },
  { id:89, topic:"Sailing ship", emoji:"⛵",
    question:"When humans made the 'sailing ship' with a big cloth sail raised, how did travel change?",
    choices:["Without rowing with human arms, the sail catches nature's 'wind power,' so they could cross the sea and carry large loads to distant continents","The ship could fly through the sky automatically","The ship never rocked even when a storm came","They could clean the sea water as they went"],
    answerIndex:0,
    explanation:"Old small boats could only move by rowing oars with human arms. This way human strength soon reached its limit, and crossing a wide sea with strong waves was impossible. So humans invented the 'sailing ship,' raising a large wall of cloth (a sail) on the ship to catch the 'energy of the wind' that blows over the earth and move forward. By using the power of nature's wind rather than human muscle, they could travel safely without rest for days, carrying many tons of heavy food and supplies, to countries thousands of kilometers across the sea, and exchange each other's wisdom and culture." },
  { id:90, topic:"Clocks and time", emoji:"🕰️",
    question:"Why did humans start measuring 'clocks and time' in detail using the moving shadow of the sun (a sundial) and the flow of water?",
    choices:["So everyone could hurry and run around","To accurately match, among everyone, society's promises like 'when to gather' and 'when to take turns,' and the plans of work","To decide on their own when they get hungry","To force night to turn into daytime"],
    answerIndex:1,
    explanation:"In a world where time is scattered and uneven, even with many people, a promise to cooperate like 'gather at that place at noon and lift the heavy log together' cannot hold. Some arrive too early, others late, and it becomes very inefficient. Humans invented the 'clock' and began dividing the day into morning, noon, and night, and into hours — a shared set of numbers — in order to make society's 'promises (the syncing of a community)' accurate. With this, they could fairly decide work shift times, and make plans to return home safely before dangerous night fell, gently bringing everyone's actions into harmony." },
  { id:91, topic:"The calendar", emoji:"📅",
    question:"Making a 'calendar' by observing the movement of the stars and sun — why was this so important for farming that lives depended on it?",
    choices:["Because flipping the date each day is fun","To predict in advance when the 'rainy season' or 'harsh winter' will come, sow seeds at the right time, and prepare food","Because you gain the power to change the weather freely yourself","Because looking at a calendar makes the plant in front of you grow faster"],
    answerIndex:1,
    explanation:"In farming, mistaking the timing of sowing seeds means the harvest becomes zero and the whole village starves. Sow seeds just before winter and they all wither in the cold. Long ago, people noticed that the patterns of stars shining in the night sky, and the position where the sun rises, change in a fixed, regular rule throughout the year. Summarizing this cycle of the earth on paper is the 'calendar.' Using it, even while it is still warm, they could read the future — 'the rainy season ends in a few weeks, so sow seeds now' — and produce food safely, making the most of nature's blessings." },
  { id:92, topic:"The beginning of money", emoji:"💰",
    question:"What is the benefit of stopping direct trade of goods for goods (barter) and starting to use 'money (currency)' made of shells or metal?",
    choices:["Because having money means thieves stop attacking you","Even between people who 'want different things,' like fish and meat, putting money in between lets them trade fairly for what they want anytime","Because eating money turns into nutrition","Because money is lying around everywhere endlessly"],
    answerIndex:1,
    explanation:"In a life of 'barter,' even if you want to trade your fish for someone's clothes, the trade does not happen unless that person wants fish. Also, since fish quickly rots, you cannot store up its value. So humans created a shared tool that everyone recognizes as valuable: 'money (currency).' If you turn fish into money once, you can store it without it rotting, and later buy clothes or medicine — whatever you need, whenever you need it — in another town. The system of money is an excellent wisdom of the economy, invented so that people all over the world can help each other (trade) smoothly and fairly without inconvenience." },
  { id:93, topic:"Printing", emoji:"📚",
    question:"The invention of 'movable-type printing' — combining letters one by one to print large numbers of books — how did it change the world?",
    choices:["The effort of copying each letter by hand disappeared, books exploded in number, and not only kings but anyone could learn knowledge and science","The weight of books became as heavy as iron","All the world's letters were unified into one","The letters written in books began to speak automatically"],
    answerIndex:0,
    explanation:"Before printing technology, to make a new book, humans had no choice but to look at every letter with their eyes and 'copy it by hand onto another paper (transcription).' It took months to make a single book, so books were as expensive as a house, and ordinary people and children could not even read. 'Movable-type printing,' developed by craftsmen in Germany and others, is a technology that lines up metal letter stamps and prints many pages in an instant with a press. With this, the price of books dropped dramatically, and anyone in the world could obtain 'books of wisdom' on medicine, farming, and arithmetic to study — a great revolution that reduced fear and disease caused by ignorance." },
  { id:94, topic:"Water supply", emoji:"🚰",
    question:"The 'water supply (aqueduct)' system built in ancient Rome and elsewhere, drawing clean water from a distant river to the town — why did it save so many lives?",
    choices:["Because they could make many clean pools inside homes","Because people no longer had to drink dirty water mixed with mud and germs, preventing terrible epidemics across the whole town","Because bathing in tap water heals injuries instantly","Because they no longer had to swim to the river to play"],
    answerIndex:1,
    explanation:"In large towns where people live crowded together, garbage and waste easily mixed into nearby wells and rivers, and the water became very dirty — a serious problem. Drinking dirty water spread terrible epidemics like cholera through the town in an instant, taking tens of thousands of lives. Ancient builders created the technology to bring 'clean, safe spring water' from mountains many kilometers away to the town over stone bridges (aqueducts) with a gentle slope. Creating an environment where everyone could always wash their hands with clean water and drink safe water became the strongest shield protecting the lives of the city from disease." },
  { id:95, topic:"Microscope", emoji:"🔬",
    question:"With the invention of the 'microscope,' a tool combining round glass lenses, how did doctors and science advance?",
    choices:["They discovered the form of tiny 'germs (bacteria),' the cause of disease, completely invisible to the human eye, and could treat and prevent correctly","The shapes of distant stars became clearly visible","Food could be sealed inside glass","You could see the surrounding scenery even with your eyes closed"],
    answerIndex:0,
    explanation:"Until the microscope, humans did not know the real reasons why people get sick or why food rots. It was believed to be the fault of invisible evil spirits or curses, and many people lost their lives to wrong treatments. But with the invention of the 'microscope,' which magnifies the tiny world hundreds of times with the power of lenses, humanity finally caught sight with their own eyes of the culprit that rots water and causes disease in the body: 'tiny germs and microbes.' Once the enemy's identity was known, the history of correct preventive medicine that reliably protects life — 'boil water to disinfect it,' 'wash your hands' — began." },
  { id:96, topic:"Compass", emoji:"🧭",
    question:"The 'compass,' whose magnetic needle always points north — how did its invention help people traveling the dark night sea or the desert?",
    choices:["Even in places where you cannot see the surrounding scenery at all, you know the 'correct direction' you are heading and can avoid getting lost","The magnet's power made the ship many times faster","It blew away all the desert sand and made a clean road","The needle automatically changed the weather to sunny"],
    answerIndex:0,
    explanation:"On the 'wide open sea' or the 'endless desert,' where all 360 degrees look the same, or moving through thick fog or pitch-dark night, is the most dangerous, terrifying time, when you lose sight of the direction to go. Humans discovered the mysterious property that a certain magnetic needle 'always points steadily to the north' through the earth's invisible magnetic force, and built it into a tool. This is the compass. Holding it, even without weather signs or landmarks, you know with 100% accuracy whether you are heading east or west, so you could completely prevent the disaster of getting lost and perishing when water and food run out." },
  { id:97, topic:"Electricity", emoji:"💡",
    question:"When humans developed the technology to generate 'electricity' and send it through wires, how did people's night lives become safer?",
    choices:["With light bulbs, they could light a safe, bright light with no danger of starting a fire inside the room","The night got shorter on its own and morning came quickly","Lots of water flowed out from the wires","The walls of the house became as sturdy as iron"],
    answerIndex:0,
    explanation:"Before electricity spread, the only night light was 'lighting a fire directly' on candles, oil, or gas. So if it was knocked over by the wind or left unextinguished, it became a great fire that set the house ablaze in an instant, and many people lost their lives. Also, because the light was dim, working at night was very dangerous. Once humans turned energy into electricity and lit 'light bulbs,' they could get a 'safe light as bright as the sun' that gives off no smoke and never causes a fire even if knocked over, at the press of a button. It is a great technology that dramatically reduced night crime and injury and protects the safety of society 24 hours a day." },
  { id:98, topic:"Communication", emoji:"📞",
    question:"As communication advanced from 'smoke signals' and 'letters' to the 'telegraph and telephone' that convey messages by electric signals, what got the best?",
    choices:["The meaning of words automatically changed into English","Without running for days to call someone, an 'emergency danger (SOS)' like heavy rain or an earthquake could be conveyed to a distant town in an instant to call for help","Calling on the phone made luggage fly in front of you","Your friend's weight got lighter"],
    answerIndex:1,
    explanation:"When a great disaster or enemy approached a distant town, in the old days the only way was to run a horse or have a person run to deliver a letter, which took many days, and often by the time it arrived it was too late. By inventing the 'telegraph' and 'telephone' that carry words and signals on electric waves, information could reach the other side of the world at 'a tremendous speed like light,' beyond the speed of human feet. With this, a life-saving SOS — 'the mountain is about to collapse, run now!' 'someone is badly hurt, send a doctor!' — could be conveyed in one second, and the number of lives that could be saved increased overwhelmingly." },
  { id:99, topic:"Advances in medicine", emoji:"💉",
    question:"When doctors developed methods of 'injection (vaccines)' and 'disinfecting tools,' how were human lives protected?",
    choices:["Human bones became hard as metal","Small children and many people who used to die easily because their bodies were weak could avoid terrible diseases and live long and healthy","Even when injured, no blood came out at all","All the sick people ran away"],
    answerIndex:1,
    explanation:"Long ago, no matter how healthy a person was, once a small wound let germs in, or a terrible virus like smallpox spread through the village, with no medicine or prevention, many people lost their lives young, helpless to stop it. Human medical scientists discovered the wisdom of 'vaccines (immunization)' — putting safe ingredients into the body in advance to build a barrier against disease — and 'disinfection,' wiping out germs with soap and alcohol. Thanks to this medical technology, the chance that babies and children all over the world can survive safely to adulthood, without losing their lives along the way, leapt up many times over." },
  { id:100, topic:"The meaning of learning", emoji:"🦉",
    question:"In this app 'Wise World,' what is the [true purpose] of you having learned so much wisdom of science and history?",
    choices:["To score 100 on a test and become greater than other people","To store up the finest charm — wisdom (knowledge) — in your head, protect your own life and the lives of those around you, and cooperate with everyone to build and live in a 'kind, safe world'","To gather lots of money and live in luxury all alone","To save up quiz experience points (EXP), clear the game, and be done"],
    answerIndex:1,
    explanation:"Congratulations! This completes the memorable 100th quiz. All the 'tools, science, and wisdom of history' that humanity has built up over tens of thousands of years, through repeated failures and at the risk of their lives, do not exist to bully someone or to let one person hold privilege and boast. They are a shared treasure invented so that all humanity — helping those truly in need, avoiding danger, beyond borders and language — can be freed from the fear of disease and hunger and 'live kindly, safely, and happily (welfare).' With the compass of the wise knowledge you learned in this app in your heart, may you gently light your own life and the future of the world. Everyone around the world is cheering on your journey of learning!" }
];
