/*
 * Wise World - Data ya jaribio (Kiswahili / Swahili)
 * ℹ Imetafsiriwa kwa msaada wa AI kutoka asili ya Kijapani. Weka id / answerIndex / emoji sawa kwa lugha zote.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).sw = [
  { id:1, topic:"Maji salama", emoji:"💧",
    question:"Ni maji gani salama yasiyokuumiza tumbo?",
    choices:["Maji ya mto","Maji ya kisima","Maji yaliyochemshwa vizuri motoni","Maji ya mvua"],
    answerIndex:2,
    explanation:"Maji ya mto, ya kisima na ya mvua yanaweza kuonekana safi kabisa, lakini yanaweza kujaa viumbe vidogo sana ambavyo macho yetu hayawezi kuona (vijidudu na virusi). Ukinywa maji haya kama yalivyo, yanaweza kusababisha maumivu makali ya tumbo au ugonjwa hatari unaotishia maisha. Lakini unapoweka maji motoni na kuyachemsha sana hadi yatoe mapovu, joto huua viumbe vyote hivyo vyenye madhara. Ndiyo maana maji yaliyochemshwa vizuri kisha yakapozwa ndiyo salama zaidi duniani, na ni maji unayoweza kunywa kwa amani." },
  { id:2, topic:"Kunawa mikono", emoji:"🧼",
    question:"Ufanye nini kabla ya kula?",
    choices:["Kunawa mikono kwa maji na sabuni","Kufuta mikono kwenye nguo","Kutofanya chochote","Kugusa udongo"],
    answerIndex:0,
    explanation:"Mikono yetu hugusa vitu vingi na ardhi kila siku, hivyo bila kujua hubeba vijidudu vingi visivyoonekana. Ukigusa chakula kwa mikono hiyo, vijidudu huhamia kwenye chakula na unavimeza mwilini pamoja na chakula. Kufuta mikono kwenye nguo chafu, au kuilowanisha kwa maji tu, hakuondoi vijidudu; hubaki vimegandama. Ni kwa kutumia sabuni na kusugua vizuri kiganja, sehemu ya juu ya mkono na kati ya vidole kwa povu, kisha kusuuza kwa maji, ndipo kweli unaondoa vijidudu." },
  { id:3, topic:"Kunawa mikono", emoji:"🚽",
    question:"Ufanye nini baada ya kutoka chooni?",
    choices:["Kwenda kucheza mara moja","Kunawa mikono kwa maji na sabuni","Kusugua mikono kwenye nguo","Kufuta mikono kwenye suruali"],
    answerIndex:1,
    explanation:"Baada ya kutoka chooni, vijidudu hatari sana kutoka kinyesi na mkojo vinavyosababisha magonjwa hugandama kwa urahisi mikononi mwako. Ukienda kucheza bila kunawa, vijidudu hivyo huhamia kwenye vipini vya milango na vitu vya kuchezea unavyogusa, na kumwambukiza rafiki au mtu wa familia anayegusa baadaye. Na ukigusa mdomo au macho yako kwa mikono hiyo, unaweza kuugua wewe mwenyewe. Hata uwe na haraka kiasi gani, kunawa mikono vizuri kwa maji na sabuni baada ya choo ni sheria inayolinda maisha yako na ya watu wanaokuzunguka." },
  { id:4, topic:"Afya", emoji:"💧",
    question:"Tumbo likiharibika na kinyesi kuwa kama maji (kuhara), jambo muhimu zaidi ni lipi?",
    choices:["Kula chakula kingi","Kutokunywa chochote","Kunywa maji salama mengi","Kukimbia na kucheza"],
    answerIndex:2,
    explanation:"Tumbo likiharibika na kinyesi kama maji (kuhara) kikitoka mara kwa mara, mwili hupoteza maji na lishe muhimu bila kukoma. Hali hii huitwa upungufu wa maji mwilini (dehydration). Mwili ukikosa maji, kazi muhimu zinazotuweka hai huanza kusimama, na hasa watoto wadogo wanaweza kupoteza maisha ghafla. Wakati wa kuhara, badala ya kujilazimisha kula chakula kigumu, jambo bora ni kwanza kurejesha maji uliyopoteza. Kwa kunywa maji salama yaliyochemshwa na kupozwa, kidogo kidogo na mara nyingi, unaweza kudumisha nguvu na kulinda maisha yako." },
  { id:5, topic:"Kutibu vidonda", emoji:"🩹",
    question:"Ukianguka na kutoka damu, ufanye nini kwanza?",
    choices:["Kuweka udongo","Kuosha vizuri kwa maji safi","Kuacha bila kufanya chochote","Kusugua kwa jani"],
    answerIndex:1,
    explanation:"Ukianguka na kupata jeraha linalotoa damu, jeraha hufunikwa na udongo, matope na vumbi kutoka ardhini, pamoja na vijidudu vingi. Ukiamini maneno ya zamani na kupaka udongo, kusugua kwa jani chafu, au kuliacha tu, vijidudu huingia ndani zaidi ya jeraha na kuzaliana. Kisha jeraha huvimba jekundu na kuuma sana, na katika hali mbaya zaidi mkono au mguu unaweza kuoza na kushindwa kusogea. Ukijeruhiwa, hatua ya kwanza sahihi ili jeraha lisiwe baya ni kutumia maji safi na salama yaliyo karibu kuosha matope na uchafu kwenye jeraha kwa nguvu." },
  { id:6, topic:"Chakula", emoji:"🦠",
    question:"Chakula kinapooza (kuharibika) kinakuwaje?",
    choices:["Kinakuwa kitamu","Kinaoza na kuumiza tumbo","Kinakuwa kigumu","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Chakula kina viumbe vidogo visivyoonekana (vijidudu) kwa idadi ndogo tangu mwanzo. Mahali penye baridi vijidudu haviwezi kufanya kazi, lakini ukiacha chakula kwa muda mrefu mahali pa joto, huwa mazingira bora kwao, na ndani ya saa chache huzaliana hadi mamilioni, idadi ya kutisha. Vijidudu vinapozaliana kiasi hicho na umbo na hali ya chakula kubadilika, tunasema kimeoza. Chakula kilichooza huhifadhi sumu kali iliyotengenezwa na vijidudu, hivyo kukila husababisha maumivu makali ya tumbo, kuhara na kichefuchefu, na kuharibu mwili wako." },
  { id:7, topic:"Chakula", emoji:"👃",
    question:"Dalili ya kuwa chakula kimeharibika ni ipi?",
    choices:["Harufu au ladha ya ajabu","Rangi nyekundu","Kitu cha baridi","Kitu kilichopikwa vizuri"],
    answerIndex:0,
    explanation:"Unaweza kutumia pua na ulimi wako kuchunguza kama chakula kimeharibika na hakiko salama tena. Kikiwa na harufu ya uchachu isiyo ya kawaida au harufu kali mbaya, au ladha ya ajabu ukiweka kidogo mdomoni, au kikiwa kinata na kuvuta nyuzi, hiyo ni ishara kwamba vijidudu vimezaliana sana na sumu imetokea. Ukijilazimisha kula kwa sababu si vyema kutupa, unahatarisha maisha yako kwa sumu kali ya chakula. Harufu au ladha ikiwa ya shaka hata kidogo, amua kukitupa na usimeze kamwe." },
  { id:8, topic:"Chakula", emoji:"🪰",
    question:"Ufanye nini na chakula ambacho nzi ametua juu yake?",
    choices:["Kula kama kilivyo","Usile sehemu aliyogusa nzi (itupe)","Kufuga nzi","Kukitazama tu"],
    answerIndex:1,
    explanation:"Mdudu tunayemwita nzi hupenda kutembea mahali pachafu sana penye vijidudu vingi, kama kinyesi cha wanyama, mizoga na madampo ya taka. Kwa hiyo vijidudu vinavyosababisha magonjwa ya kutisha hugandama kwenye miguu yake myembamba na mwili. Nzi kama huyo anapotua kwenye chakula chetu, papo hapo vijidudu vya miguuni mwake huhamia chakulani. Ukila sehemu aliyogusa, unaingiza mdomoni mwako bila kujua vijidudu vya kinyesi na taka, jambo linaloweza kusababisha ugonjwa mkubwa. Hata ionekane hasara, ni salama zaidi kukata na kutupa sehemu ya chakula nzi aliyotua." },
  { id:9, topic:"Kuzuia magonjwa", emoji:"🦟",
    question:"Ukiacha maji yamesimama kwa muda mrefu kunatokea nini?",
    choices:["Maji yanakuwa safi","Mbu hatari wanazaliana sana","Pesa zako zinaongezeka","Hakuna kinachotokea"],
    answerIndex:1,
    explanation:"Maji ya zamani yanayobaki mahali pamoja bila kutiririka huwa mahali bora kwa mdudu aitwaye mbu kutaga mayai yake. Ukiacha ndoo, matairi ya zamani au makopo matupu yenye maji karibu na uwanja au nyumba yako, huko huzaliwa mbu wapya mamia na maelfu wanaoruka kila mahali. Mbu anaponyonya damu ya mtu, huingiza mwilini vijidudu vya magonjwa hatari sana yanayoua kama malaria na dengue. Kuondoa madimbwi ya maji karibu na nyumba ni mpango muhimu wa kulinda familia dhidi ya magonjwa haya ya kutisha." },
  { id:10, topic:"Usafi", emoji:"✋",
    question:"Kucha zikiwa ndefu, ndani yake hujikusanya nini?",
    choices:["Mikono inakuwa na nguvu","Uchafu mweusi na vijidudu hujikusanya chini ya kucha","Chakula kinakuwa kitamu zaidi","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Kucha zinapokuwa ndefu, matope na uchafu mweusi hujaa kwenye nafasi nyembamba kati ya ukucha na ngozi unapocheza udongoni, unaposaidia au unapofanya kazi. Uchafu unaoingia nafasi hiyo hautoki kwa urahisi kwa kunawa mikono kwa kawaida, na huwa mahali bora pa kujificha kwa vijidudu. Kwa kucha ndefu, unapokula kwa mikono au unapogusa uso wako au jeraha, vijidudu hivyo vilivyojificha huingia mwilini kwa urahisi. Kukata kucha ziwe fupi kila wakati ni njia ya msingi ya kuzuia magonjwa." },
  { id:11, topic:"Adabu za kukohoa", emoji:"🤧",
    question:"Ufanye nini unapokohoa au kupiga chafya?",
    choices:["Kufanya kuelekea uso wa mtu","Kufunika mdomo na pua kwa mkono au mkono wa nguo","Kupiga kelele","Kutofanya chochote"],
    answerIndex:1,
    explanation:"Unapokuwa na mafua au ugonjwa wa mapafu, kukohoa au kupiga chafya mara moja tu hurusha matone madogo ya maji yasiyoonekana kutoka mdomoni na puani, mita kadhaa mbali kwa nguvu. Kila tone laweza kuwa na vijidudu vya magonjwa elfu kadhaa. Ukikohoa kuelekea uso wa mtu, unamwambukiza moja kwa moja, na usipofunika chochote, vijidudu husambaa hewani na kila mtu chumbani humo anaweza kuugua. Unapokohoa, kufunika vizuri mdomo na pua kwa mkono wa nguo au mkono hukuzuia kueneza ugonjwa kwa familia na marafiki wapendwa wanaokuzunguka." },
  { id:12, topic:"Usafi", emoji:"🗑️",
    question:"Ukiacha taka zimetupwa karibu na nyumba kunatokea nini?",
    choices:["Nyumba inakuwa safi","Panya na wadudu hatari hujikusanya na ugonjwa husambaa","Taka zinakuwa maua","Hakuna tatizo"],
    answerIndex:1,
    explanation:"Ukitupa mabaki ya chakula na taka karibu kabisa na nyumba yako, harufu huvutia viumbe vingi kama panya, nzi na mende. Viumbe hawa kwa kawaida hutembea kwenye mifereji ya maji machafu na sehemu chafu, hivyo hubeba vijidudu vingi vya magonjwa ya kutisha mwilini. Wanapoongezeka kuzunguka taka, hatimaye huingia ndani ya nyumba na kuchafua chakula na maji ya kunywa yaliyo ndani. Taka lazima zitupwe mahali maalum mbali vya kutosha na nyumba, au zifukiwe ndani ya shimo refu ardhini." },
  { id:13, topic:"Meno yenye afya", emoji:"🪥",
    question:"Sababu kuu ya kupiga mswaki ni ipi?",
    choices:["Kupaka meno rangi nyeupe","Kupunguza vijidudu vya kuoza meno mdomoni na kulinda meno","Kuimarisha taya","Kushibisha tumbo"],
    answerIndex:1,
    explanation:"Baada ya kula, mabaki madogo ya chakula hubaki daima kwenye nafasi na uso wa meno. Viumbe visivyoonekana viitwavyo vijidudu vya kuoza meno, vinavyoishi mdomoni mwetu, hupenda sana mabaki hayo. Ukiyaacha pale, vijidudu hivyo huyala na kutengeneza asidi kali inayoyeyusha meno. Kwa sababu ya asidi hiyo, mashimo hutokea polepole kwenye meno, ambayo yanapaswa kuwa sehemu ngumu zaidi ya mwili, na yanapofika kwenye neva huleta maumivu makali kiasi kwamba huwezi kulala usiku. Kupiga mswaki baada ya kula ni kazi ya lazima kabisa ili kuondoa chakula cha vijidudu na kulinda meno yako." },
  { id:14, topic:"Kuzuia majeraha", emoji:"👟",
    question:"Kwa nini uvae viatu unapotembea nje?",
    choices:["Ili miguu ikue","Ili kuzuia minyoo na vijidudu vya udongoni visiingie kupitia ngozi ya miguu","Ili kufanya mazoezi ya kukimbia","Ili nguo zisichafuke"],
    answerIndex:1,
    explanation:"Unapotembea bila viatu juu ya udongo na matope, viumbe vidogo sana vilivyojificha ardhini visivyoonekana (lava za minyoo ya vimelea) na vijidudu vinaweza kutoboa ngozi laini ya nyayo zako na kuingia mwilini vyenyewe. Minyoo inayoingia hujikita tumboni (matumbo) na kuiba lishe unayokula, ikikufanya uwe na upungufu mkubwa wa damu, kusimamisha ukuaji wako na kukunyima nguvu. Kuvaa viatu pia hukulinda dhidi ya majeraha makubwa ya kukanyaga vipande vya glasi, mawe makali au miiba. Vaa viatu au kandambili kila unapotoka nje." },
  { id:15, topic:"Usafi", emoji:"👕",
    question:"Ukiendelea kuvaa nguo chafu kunatokea nini?",
    choices:["Nguo zinakuwa imara","Ngozi inawasha au unaugua","Mwili unakuwa na nguvu","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Ukiendelea kuvaa nguo zenye jasho au zilizochafuliwa na matope kwa siku nyingi, ukungu na vijidudu hula jasho la binadamu na mafuta ya ngozi yaliyo kwenye nguo na kuzaliana sana ndani ya nyuzi zake. Kwa kuwa nguo hizo chafu husuguana na ngozi yako wakati wote, ngozi inaweza kuvimba jekundu, kuwasha sana, au kupata ugonjwa wenye vidonda vinavyotoa usaha. Nguo chafu zinaweza kuondolewa vijidudu kabisa kwa kuzifua vizuri kwa maji na sabuni na kuzikausha vizuri juani (miale ya urujuanimno). Kuvaa nguo safi daima ni muhimu ili kulinda ngozi yako." },
  { id:16, topic:"Usafi", emoji:"🚿",
    question:"Kuoga mwili kuna faida gani?",
    choices:["Ngozi inakuwa safi na unazuia magonjwa ya ngozi","Unakuwa mrefu","Nywele zinapukutika","Unasikia njaa"],
    answerIndex:0,
    explanation:"Kila siku ngozi ya binadamu hutoa mafuta yasiyoonekana (sebamu) na jasho, na vumbi na udongo wa nje huchanganyika, ukichafua mwili mzima. Ukiacha uchafu huu kwa siku nyingi, vijidudu vibaya huzaliana juu ya ngozi, na unaweza kupata majipu mabaya au ugonjwa wa kutisha ambapo ngozi hupata vidonda na kuoza. Kwa kuoga mwili mzima kwa upole mara kwa mara, kwa maji na sabuni, na kuondoa mafuta na uchafu wa zamani, ngozi yako hubaki na afya na nguvu, ikitengeneza kinga imara inayozuia ugonjwa usiingie kutoka nje." },
  { id:17, topic:"Maji salama", emoji:"💧",
    question:"Ukiwa na maji yenye matope tu, unaweza kuyanywa salama vipi?",
    choices:["Kuyanywa kama yalivyo","Kuchuja matope kwa kitambaa au mchanga, kisha kuyachemsha motoni","Kuyaweka juani tu kisha kunywa","Kunywa kidogo tu"],
    answerIndex:1,
    explanation:"Unapoweza kupata maji yenye matope tu, kuyanywa kama yalivyo huingiza mwilini mwako vijidudu vingi sana pamoja na matope na husababisha ugonjwa mkubwa. Kuyafanya salama kunahitaji hekima mbili. Kwanza, pitisha maji kwenye kitambaa safi chenye matundu madogo, au chombo kilichojaa mchanga na kokoto ndogo, ili kuchuja matope na uchafu mkubwa na kufanya maji yawe safi. Lakini kuwa safi pekee hakutoshi; vijidudu visivyoonekana bado vi hai. Baada ya hapo, lazima uyaweke motoni na kuyachemsha sana hadi yatoe mapovu, ili joto liangamize vijidudu na hatimaye yawe maji salama ya kunywa. Kwa hekima, unaweza kutengeneza maji yanayookoa maisha hata kutoka maji yenye matope." },
  { id:18, topic:"Watoto wachanga", emoji:"🍼",
    question:"Lishe bora zaidi kwa mtoto mchanga ni ipi?",
    choices:["Maziwa ya ng'ombe (mabichi)","Maziwa ya mama (kunyonyesha)","Maji ya mto","Maji ya sukari"],
    answerIndex:1,
    explanation:"Mwili wa mtoto mchanga aliyezaliwa karibuni ni dhaifu sana na hauna karibu nguvu yoyote ya kushinda vijidudu vya magonjwa. Maziwa ya mama (kunyonyesha) hayana tu lishe kamili kwa mtoto kukua, bali pia kiasi kikubwa cha kiungo maalum cha kinga kiitwacho kinga ya mwili (immunity), kinachomlinda dhidi ya magonjwa. Pia, maziwa ya mama hutoka moja kwa moja mwilini, hivyo hayagusi kamwe maji machafu ya nje wala vijidudu vya vyombo; ni safi na salama zaidi duniani. Maziwa mabichi ya wanyama wengine, maji ya mto au maji ya sukari yanaweza kuharibu tumbo na matumbo dhaifu ya mtoto na kuchukua maisha yake, hivyo usiwahi kumpa." },
  { id:19, topic:"Kuzuia magonjwa", emoji:"😷",
    question:"Karibu na mtu anayekohoa sana ufanye nini?",
    choices:["Kuwa mbali kidogo, na kugeuza uso unapopita","Kuvuta pumzi kwa nguvu mbele yake","Kupeana mkono naye","Kusimama mbele yake kabisa"],
    answerIndex:0,
    explanation:"Magonjwa hatari ya kupumua kama kifua kikuu (TB) huelea hewani kwa muda mrefu, yakibebwa na matone madogo yasiyoonekana yanayotawanyika mtu mgonjwa anapokohoa. Ukivuta pumzi kwa nguvu karibu, au ukikaa karibu kwa muda mrefu, unavuta vijidudu hivyo ndani zaidi ya mapafu yako na unaweza kupata ugonjwa huo huo hatari. Mtu anapokohoa sana, si suala la ukatili wala kumtenga; bali ili kujilinda, kaa umbali wa mita kadhaa, na unapopita geuza uso na utoe pumzi taratibu; hivyo ndivyo nyote wawili mnavyojilinda." },
  { id:20, topic:"Hewa safi", emoji:"🪟",
    question:"Unawezaje kuweka hewa ya chumba safi?",
    choices:["Kufunga milango na madirisha yote vizuri","Kufungua madirisha na milango ili kubadilisha hewa","Kila mtu apige kelele pamoja","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Watu wengi wanapokusanyika katika chumba kidogo kilichofungwa, vijidudu na virusi vya magonjwa anavyobeba mtu fulani hujikusanya zaidi na zaidi hewani, hadi hewa ya chumba ijae vijidudu. Ukikaa muda mrefu katika chumba hicho, kila mtu huvuta hewa chafu na kuugua pamoja (maambukizi ya kikundi). Kwa kufungua madirisha na milango sehemu mbili au zaidi ili kubadilisha hewa safi ya nje na hewa chafu ya chumbani (kupitisha hewa), unaweza kufukuza vijidudu kutoka hewani na kulinda afya ya kila mtu chumbani." },
  { id:21, topic:"Nguzo", emoji:"🪨",
    question:"Unapotaka kusogeza jiwe zito lililozikwa ardhini kwa kutumia fimbo ndefu, ni wapi unapaswa kukandamiza kwa nguvu zaidi ili kulisogeza kwa nguvu ndogo kabisa?",
    choices:["Mahali palipo karibu kabisa na jiwe","Katikati ya fimbo","Mwisho wa fimbo ulio mbali zaidi na jiwe","Ni sawa popote ukandamizapo"],
    answerIndex:2,
    explanation:"Unaposogeza kitu kizito kwa fimbo, kuna kanuni iitwayo «kanuni ya nguzo»: kadiri unavyokuwa mbali na jiwe dogo linalofanya kazi ya egemeo (kitovu cha egemeo), ndivyo unavyohitaji nguvu ndogo zaidi kukandamiza. Ukikandamiza karibu na jiwe, fimbo haiyumbi, lakini ukishika mwisho wa fimbo ulio mbali zaidi na kukandamiza huku ukiegemeza uzito wa mwili wako, unaweza kuinua jiwe zito kwa nguvu ndogo ya kushangaza. Kujua jinsi chombo kinavyofanya kazi hivi kunakuwezesha kuongeza nguvu yako mara nyingi na kufanya kazi nzito kwa urahisi." },
  { id:22, topic:"Nguzo", emoji:"⚖️",
    question:"Unapoinua mzigo mzito kwa fimbo ndefu, ni wapi unapaswa kuweka jiwe dogo (kitovu cha egemeo) linalotegemeza fimbo ili uinuke kwa urahisi zaidi?",
    choices:["Karibu kabisa na mzigo mzito","Karibu kabisa na mahali unapotia nguvu yako","Katikati kabisa ya fimbo","Ni bora usiweke jiwe kabisa"],
    answerIndex:0,
    explanation:"Unapoinua kitu kizito kwa fimbo, nafasi ya jiwe dogo la egemeo (kitovu cha egemeo) ni muhimu sana. Kwa kuweka egemeo hili karibu kabisa na mzigo mzito, mzigo husogea umbali mfupi tu, lakini nguvu unayohitaji kuuinua hupungua sana. Kinyume chake, kama jiwe la egemeo liko karibu nawe, hata ukikandamiza kiasi gani hutaweza kuinua mzigo. Unapotaka kusogeza kitu kizito, kumbuka hekima ya kuweka egemeo karibu na kitu unachotaka kukisogeza." },
  { id:23, topic:"Kuviringika", emoji:"🪵",
    question:"Unaposogeza sanduku zito la mbao kwa kulikokota ardhini, unawezaje kulisogeza kwa urahisi zaidi na nguvu ndogo kabisa?",
    choices:["Weka magogo kadhaa ya mviringo na magumu chini ya sanduku na ulivingirishe","Livute kwa nguvu zako zote kama lilivyo","Mwaga maji juu ya sanduku","Lipige sanduku kwa nguvu chini"],
    answerIndex:0,
    explanation:"Unapokokota kitu kizito moja kwa moja ardhini, hufanya kazi kwa nguvu kani ya kuzuia iitwayo msuguano, inayotokea mahali kitu kinapokwaruzana na ardhi, hivyo kusogeza huhitaji nguvu kubwa mno. Lakini ukiweka magogo ya mviringo na magumu chini ya sanduku, mwendo hubadilika kutoka kukokota hadi magogo kuviringika. Kuviringika kuna kani ya kuzuia ndogo mara makumi kuliko kukokota, hivyo hata mtu mmoja anaweza kusogeza mzigo mzito kwa wepesi. Mzigo unaposonga mbele, unachukua magogo yaliyotoka nyuma na kuyaweka tena mbele — hekima ambayo binadamu ametumia tangu zamani za kale." },
  { id:24, topic:"Mteremko", emoji:"🛝",
    question:"Unapotaka kupandisha mzigo mzito juu ya jukwaa refu lenye kimo cha kifua cha mtu mzima, ni njia ipi ya kuusogeza inayolemea mwili wako kidogo zaidi?",
    choices:["Simama mbele ya jukwaa na uinue mzigo moja kwa moja juu kwa nguvu zako zote","Egemeza ubao mrefu kwa mshazari kwenye jukwaa kutengeneza mteremko, na uusukume juu","Rusha mzigo kwenye jukwaa kutoka mbali","Punguza kimo cha jukwaa ili kiwe kifupi"],
    answerIndex:1,
    explanation:"Ukijaribu kuinua mzigo mzito moja kwa moja juu, unakabiliana ana kwa ana na kani inayovuta vitu kuelekea ardhini (graviti), hivyo lazima ubebe uzito wote kwa misuli yako pekee, jambo linaloumiza mgongo na mikono. Hapa, ukiegemeza ubao mrefu kwa mshazari kwenye jukwaa kutengeneza «mteremko» (sakafu iliyoinama), ubao huja kubeba sehemu kubwa ya uzito wa mzigo. Kwenye mteremko, umbali unaotembea huongezeka, lakini nguvu inayohitajika kusukuma mzigo inaweza kupunguzwa hadi chini ya nusu. Unapobeba vitu mahali pa juu, daima tafuta njia ya kutengeneza mteremko." },
  { id:25, topic:"Kapi", emoji:"🪣",
    question:"Unapovuta ndoo nzito iliyojaa maji kutoka kisima kirefu kwa kamba, ni nini hurahisika ukiweka gurudumu la mviringo linalozunguka (kapi) kwenye mti ulio juu ya kisima na kupitisha kamba juu yake?",
    choices:["Uzito wa maji huwa mwepesi nusu","Kiasi cha maji huongezeka chenyewe","Unaweza kupandisha maji kwa kuvuta kamba chini tu","Kamba haitakatika kamwe"],
    answerIndex:2,
    explanation:"Unapopitisha kamba kwenye gurudumu la mviringo lililo juu ya kisima (kapi tuli), kwa kweli uzito wa maji wenyewe hauwi mwepesi. Lakini jambo zuri la chombo hiki ni kwamba hubadilisha mwelekeo unaotia nguvu. Ukijaribu kupandisha kamba moja kwa moja juu, lazima uiinue kwa nguvu ya mikono na mgongo wako pekee; lakini ukipitisha kamba kwenye gurudumu la mviringo na kuvuta chini, unaweza kuegemeza uzito wote wa mwili wako kwenye kamba. Kuweza kutumia uzito wa mwili wako kuvuta maji mazito kwa urahisi na usalama, ndiyo hekima ya gurudumu hili la mviringo." },
  { id:26, topic:"Gurudumu na ekseli", emoji:"🔄",
    question:"Unapotaka kuzungusha skrubu isiyozunguka kabisa, au mtambo mzito wa kuviringisha wa kisima, unawezaje kuuzungusha kwa urahisi zaidi?",
    choices:["Kuuzungusha kwa fimbo fupi na nyembamba","Kufanya sehemu ya mpini kuwa kubwa na ndefu, na kuzungusha hiyo","Kuuzungusha kwa ncha za vidole tu, bila chombo","Kupiga skrubu kwa nyundo kwa nguvu"],
    answerIndex:1,
    explanation:"Unapotaka kuzungusha ekseli iliyo katikati, ukiweka «mpini mkubwa wa mviringo» au «mpini mrefu» kwenye ekseli hiyo, unaweza kuzalisha kani kubwa ya kuzungusha kwa juhudi ndogo. Hii huitwa kanuni ya «gurudumu na ekseli». Huwezi kusogeza sehemu nyembamba kwa kuizungusha moja kwa moja kwa vidole, lakini unapozungusha mpini mkubwa wa nje, umbali unaopita mkono wako huongezeka, huku kani kwenye ekseli ikiwa kubwa mara nyingi. Mtambo unaoviringisha kamba ya kisima, kitasa cha mlango nyumbani, skrubu za vyombo; kila kitu kinachozunguka karibu nawe hutumia hekima hii." },
  { id:27, topic:"Kitovu cha uzito", emoji:"🏺",
    question:"Kuna watu wanaotembea kwa ustadi huku wakibeba mtungi mzito wa maji au kuni «juu ya kichwa». Kwa nini wanaweza kutembea umbali mrefu bila kuumiza shingo au mgongo?",
    choices:["Kwa sababu wanatembea huku wakikunja mwili mbele au nyuma sana","Kwa sababu wananyoosha mgongo sawasawa kabisa na kuweka kitovu cha mzigo (kitovu chake cha uzito) juu kabisa ya mifupa yao","Kwa sababu wanatikisa mzigo kwa nguvu juu ya kichwa muda wote","Kwa sababu kila mtu huzaliwa na mifupa ya shingo minene kuliko wengine"],
    answerIndex:1,
    explanation:"Unapobeba mzigo mzito mikononi, mzigo huelemea upande mmoja tu wa mwili na misuli huchoka haraka. Lakini ukinyoosha mgongo sawasawa kabisa na kuweka mzigo juu kabisa ya kichwa, uzito wa kitovu cha mzigo (kitovu chake cha uzito) hushuka moja kwa moja kupitia nguzo ya mifupa, kutoka kichwani hadi shingoni kisha uti wa mgongo, na kutokea ardhini. Kwa kuwa mifupa imara, si misuli, ndiyo inayobeba uzito, unaweza kuubeba kwa usalama umbali mrefu bila kupoteza nguvu za misuli, mradi tu udumishe uwiano. Kuweka vitu karibu na «mhimili wa katikati wa mwili wako» ni hekima muhimu ili usijiumize." },
  { id:28, topic:"Shinikizo", emoji:"🦶",
    question:"Unapotembea kwenye «njia ya matope» ambayo baada ya mvua hugeuka matope mazito na miguu huzama, unawezaje kutembea kwa urahisi bila kuzama?",
    choices:["Tembea kwa ncha za vidole, ukifanya nyayo za miguu kuwa ndogo kadiri iwezekanavyo","Funga ubao wa mbao bapa na mkubwa chini ya nyayo za miguu na utembee","Piga kelele kwa sauti kubwa tu na uvuke mbio","Beba mizigo mingi ili uzito wako uongezeke"],
    answerIndex:1,
    explanation:"Uzito unaobonyeza ardhi hujikusanya kwa nguvu zaidi sehemu moja na kuzama ndani zaidi, kama sindano, kadiri eneo linaloligusa linavyokuwa dogo. Hii huitwa «shinikizo». Kusimama kwa ncha za vidole hufanya eneo kuwa dogo, hivyo unazama ndani zaidi. Kinyume chake, ukifunga ubao bapa na mkubwa chini ya nyayo za miguu, uzito wa mwili wako husambaa kwenye eneo pana, hivyo kani inayobonyeza ardhi chini hudhoofika na unaweza kutembea juu ya matope bila kuzama. Kufanya msingi wa jengo zito kuwa mpana na bapa pia ni hekima ileile ya kusambaza shinikizo." },
  { id:29, topic:"Mikokoteni", emoji:"🛒",
    question:"Unapotaka kupakia mzigo mwingi mzito kwenye mkokoteni wa magurudumu mawili na kuuvuta, ni wapi uweke vitu vizito ili uwe mwepesi na rahisi kuvuta zaidi?",
    choices:["Karibu kabisa na mikono yako, kando ya mpini","Mwisho kabisa wa nyuma wa mkokoteni","Juu kabisa ya ekseli ya magurudumu","Ni sawa popote upakiapo"],
    answerIndex:2,
    explanation:"Unapovuta mkokoteni, uzito ulio mikononi mwako hubadilika sana kulingana na mahali unapoweka mzigo. Ukipakia mzigo mzito karibu na mikono yako, unaishia kukimbia huku ukiinua uzito wa mzigo moja kwa moja kwa mikono, na unachoka haraka. Ukiweka mbali sana nyuma, mkokoteni hupinduka nyuma, jambo hatari. Jibu sahihi ni juu kabisa ya ekseli ya magurudumu. Ukiweka vitu vizito hapa, magurudumu imara na ardhi hubeba uzito wote, hivyo karibu hakuna uzito unaoangukia mikononi mwako. Kwa kuwa unahitaji tu nguvu ya kuvuta mbele, unaweza kubeba mzigo mkubwa kwa urahisi sana." },
  { id:30, topic:"Makali", emoji:"🔪",
    question:"Unapononoa makali ya shoka la kupasua kuni, au kisu cha jikoni cha kukata chakula, kwa kuyasugua kwenye jiwe (jiwe la kunoa), kwa nini hukata vizuri zaidi?",
    choices:["Kwa sababu ncha ya makali huwa nyembamba na laini zaidi, na nguvu hujikusanya sehemu moja","Kwa sababu makali huwa moto na kuyeyusha chakula","Kwa sababu makali huwa mazito zaidi","Kwa sababu makali huwa ya mviringo"],
    answerIndex:0,
    explanation:"Kitu kukatwa na makali hutokea kwa sababu nguvu anayotia mtu hujikusanya kwenye sehemu nyembamba sana ya ncha ya makali na kupasua kitu. Makali yanapozeeka na kuwa ya mviringo, nguvu husambaa kwenye eneo pana, hivyo hata ukikandamiza kiasi gani hayakati. Kunoa makali ni kazi ya kusugua ncha iliyoviringika ili iwe nyembamba na laini kadiri iwezekanavyo. Ncha ikishakuwa nyembamba, hata nguvu ndogo huzalisha «shinikizo» kubwa mno sehemu hiyo, hivyo unaweza kukata kuni ngumu au chakula kwa mguso mwepesi. Kutunza vyombo vyako ni msingi wa kuokoa nguvu zako." },
  { id:31, topic:"Msuguano", emoji:"👟",
    question:"Unapotembea kwenye mteremko au juu ya miamba yenye unyevu, ni kipi kinacholeza kidogo na ni salama zaidi: viatu laini vinavyolezesha, au viatu vyenye mifereji yenye meno na kina kwenye sehemu ya chini?",
    choices:["Viatu laini bapa","Viatu vyenye mifereji yenye meno na kina chini","Ni sawa vyovyote uvaavyo","Unalezesha kidogo bila viatu kabisa"],
    answerIndex:1,
    explanation:"Sehemu ya chini ya kiatu inapokwaruzana na ardhi, hapo hufanya kazi kani ya kuzuia iitwayo msuguano inayokuzuia usilezeze. Kama sehemu ya chini ni laini, hakuna kuzuia kunakofanya kazi kati yake na ardhi, na unalezesha na kuanguka kwa urahisi, hasa palipo na maji au matope. Kama sehemu ya chini ina mifereji yenye meno na kina, mifereji hiyo hung'ang'ania kwa nguvu matuta ya ardhi na kuzalisha kuzuia kwenye nguvu. Kulezesha na kuanguka kunaweza kusababisha jeraha kubwa, lakini kwa kujua jinsi msuguano unavyofanya kazi — kwa kuchagua viatu vyenye mifereji mahali penye kulezesha au kwa kuweka nyayo nzima ardhini kwa imara — unaweza kutenda kwa usalama." },
  { id:32, topic:"Kuelea", emoji:"⛵",
    question:"Kijiwe kidogo huzama majini, na bado meli ya mbao iliyo nzito na kubwa maelfu ya mara zaidi inaweza kuelea juu ya maji. Kwa nini?",
    choices:["Kwa sababu meli ina umbo la «bakuli» na hushikilia hewa na maji mengi ndani yake","Kwa sababu meli hupigwa na upepo mwingi","Kwa sababu kuna mawe ya kichawi yaliyopakwa chini yake","Kwa sababu meli imetengenezwa kwa mafuta mepesi kuliko maji"],
    answerIndex:0,
    explanation:"Kwenye kitu kilicho ndani ya maji hufanya kazi kani ya ajabu iitwayo «kani ya kuelea», inayokisukuma juu kiasi sawa na maji kinachoyasukuma kando. Kijiwe ni kigumu ndani na kizito, hivyo kijiwe ni kizito kuliko maji kinayoyasukuma kando, na huzama. Lakini meli kubwa ina umbo la «bakuli», na ndani yake ina hewa nyingi. Ikitazamwa kwa ujumla, huwa nyepesi sana kulingana na ukubwa wake, hivyo kani ya maji inayosukuma kutoka chini huwa na nguvu zaidi, na hata meli kubwa inaweza kuelea juu ya maji bila kupinduka." },
  { id:33, topic:"Pembetatu", emoji:"🔺",
    question:"Unapojenga nyumba au daraja kwa mbao au chuma, kwa nini kuunganisha fremu kwa umbo la «pembetatu» hufanya jengo imara sana na gumu kuvunjika?",
    choices:["Kwa sababu huhitaji vifaa vingi kuliko mraba","Kwa sababu pembetatu ina sifa kwamba umbo lake halipotoki kamwe, hata nguvu kubwa ikitumika kutoka juu","Kwa sababu kutengeneza pembetatu hufanya upepo kupita kwa urahisi zaidi","Kwa sababu ni umbo la kale linalotumika kama hirizi kutoka kwa miungu"],
    answerIndex:1,
    explanation:"Jengo lililotengenezwa kwa nguzo zilizounganishwa kwa «mraba» tu huporomoka kwa urahisi, viungio vyake vikiinama vilegevu, nguvu kubwa au mtikisiko wa tetemeko la ardhi unapotumika kutoka juu au kando. Lakini ukiongeza ufito mmoja wa mshazari ndani ya mraba huo kutengeneza «pembetatu» (muundo wa trasi), basi nguvu itoke mwelekeo wowote, fito huvutana na kusukumana na umbo halipotoki kamwe. Ukitazama madaraja makubwa duniani, au upande wa chini wa paa za majengo, pembetatu hizi daima zimeunganishwa kwa ufundi. Ni hekima nzuri ya ujenzi: hata kwa vifaa vichache, kwa kufikiria tu umbo unaweza kutengeneza kitu imara mara nyingi zaidi." },
  { id:34, topic:"Mwendo", emoji:"🐎",
    question:"Farasi au mkokoteni unaokimbia ukikanyaga breki ghafla na kusimama kabisa, kinatokea nini kwa mzigo na watu waliopanda juu?",
    choices:["Hupinduka nyuma kama walivyo","Hurushwa mbele kwa nguvu","Huruka moja kwa moja juu palepale","Hakuna kinachotokea; nao husimama kabisa"],
    answerIndex:1,
    explanation:"Katika ulimwengu kuna kani ya ajabu iitwayo «hali ya kusonga» (inertia): kitu kinachosonga hujaribu kuendelea kusonga kwa kasi ileile. Hata farasi au gari likisimama ghafla, watu na mizigo iliyo juu bado hujaribu kuendelea mbele. Kwa hiyo, usipoweka miguu yako kwa imara au kufunga mzigo kwa kamba, unarushwa mbele kwa nguvu na kuumia vibaya. Unaposimamisha kitu kinachosonga, au unapopanda chombo cha kasi, lazima ukumbuke kwamba kani hii inayojaribu kurusha vitu mbele hufanya kazi daima, na ujiandae kwa ajili ya usalama wako." },
  { id:35, topic:"Mkasi", emoji:"✂️",
    question:"Unapotaka kukata tawi gumu au kitambaa kinene kwa mkasi, ni sehemu ipi ya ubapa unapaswa kubana ili kukata kwa urahisi zaidi na nguvu ndogo kabisa?",
    choices:["Kwenye ncha kabisa ya ubapa","Kwenye shina la ubapa (karibu zaidi na skrubu au bawaba)","Katikati ya ubapa","Nguvu inayohitajika ni sawa popote ukatapo"],
    answerIndex:1,
    explanation:"Mkasi pia ni chombo chenye manufaa sana kinachotumia «kanuni ya nguzo» tuliyojifunza. Skrubu ambapo bapa mbili huvukana na kufungwa huwa egemeo (kitovu cha egemeo). Kadiri unavyokata karibu na skrubu hii ya egemeo, ndivyo nguvu ambayo mkono wako unaobana huipeleka kwenye ubapa inavyokuwa kubwa mara nyingi. Kwa hiyo, kwa kitu kigumu kisichokatika, kujaribu kukata kwa ncha ya mkasi huumiza mkono tu, lakini ukikibana kwa kina kwenye shina la ubapa, unaweza kukikata kwa nguvu ndogo ya kushangaza. Jua sifa za vyombo vyako na utumie sehemu yenye ufanisi zaidi." },
  { id:36, topic:"Graviti", emoji:"🍎",
    question:"Kwa nini, kati ya kuangusha kijiwe kidogo kwenye mguu kutoka kimo cha goti na kukiangusha kutoka juu ya paa la nyumba, kile kinachoanguka kutoka paani husababisha jeraha kubwa zaidi?",
    choices:["Kwa sababu jiwe huwa baridi zaidi juu ya paa","Kwa sababu graviti, kani inayovuta vitu kuelekea ardhini, hufanya jiwe liende kasi zaidi na zaidi kadiri kuanguka kunavyozidi kuwa kwa mbali, hivyo mshtuko wa kugonga huwa mkali zaidi","Kwa sababu jiwe lililoko mahali pa juu huwa kubwa zaidi kwa ukubwa","Kwa sababu hewa husukuma jiwe chini"],
    answerIndex:1,
    explanation:"Kila kitu kilicho juu ya dunia huvutwa daima na kani iitwayo «graviti», ikikielekeza ardhini. Kwa kitu kilichoko mahali pa juu, kadiri kuanguka kunavyozidi kuwa kwa mbali, ndivyo graviti inavyozidi kukivuta na kasi yake huzidi kuongezeka (huongeza mwendokasi). Kitu kilichoongeza kasi huzalisha nguvu kubwa ya uharibifu (nishati) wakati kinapogonga ardhi au mwili wako. Kutoka kimo cha goti huuma tu, lakini kinachoanguka kutoka paa refu au genge, hata kiwe kijiwe kidogo au chombo, huwa silaha inayoweza kuondoa uhai wa mtu. Unapofanya kazi karibu na mahali pa juu, lazima uhakikishe hakuna mtu chini na uwe makini sana usiangushe chochote." },
  { id:37, topic:"Uwiano", emoji:"⚖️",
    question:"Unapobeba begani fimbo ndefu (mpiko) ukiwa umetundika mitungi miwili mizito ya maji mbele na nyuma, unawezaje kutembea kwa urahisi bila bega kuumia?",
    choices:["Kufanya mzigo wa mbele kuwa mzito sana na mzigo wa nyuma kuwa mwepesi","Kufanya mizigo ya mbele na nyuma kuwa na uzito «sawa kabisa», na kuweka katikati kabisa ya fimbo begani","Kutoweka fimbo begani; kuibeba kwa mikono tu","Kuangusha mizigo chini kwa zamu huku ukikimbia"],
    answerIndex:1,
    explanation:"Unapobeba mizigo iliyotundikwa pande zote mbili za fimbo ndefu, kama uzito wa mbele na nyuma haulingani, fimbo huinama upande mmoja na lazima upambane kuishikilia kwa mikono. Hii huchosha haraka si bega tu, bali mikono na mgongo pia. Jibu sahihi ni kufanya mizigo ya mbele na nyuma kuwa na uwiano sawa kabisa. Hivyo uzito hubonyeza sawasawa juu kabisa ya bega kupitia mpiko, na unaweza kubeba mizigo mizito kwa kutembea tu, bila kutumia misuli ya ziada kupambana na kuinama. Kama mzigo mmoja ni mwepesi bila kuepukika, rekebisha uwiano kwa kuteleza kamba ya upande mwepesi kuelekea ncha ya fimbo." },
  { id:38, topic:"Kizuizi cha hewa", emoji:"🪂",
    question:"Una karatasi mbili zenye ukubwa sawa na uzito sawa. Moja imeachwa karatasi bapa, nyingine imefinywa kwa mkono kuwa mpira mgumu. Unapoziangusha kwa pamoja kutoka mahali pa juu, ni ipi hufika ardhini kwanza?",
    choices:["Karatasi bapa kama ilivyo","Karatasi iliyofinywa kuwa mpira mgumu","Zote hufika kwa wakati mmoja kabisa","Hubadilika kila mara kulingana na upepo"],
    answerIndex:1,
    explanation:"Hata kwa vitu vyenye uzito sawa, vinapoanguka kupitia hewa hufanya kazi kani ya kuzuia iitwayo «kizuizi cha hewa», hewa ikizuia. Karatasi bapa ina eneo pana, hivyo hunasa hewa nyingi chini yake na huanguka polepole tu, kama parachuti. Lakini karatasi iliyofinywa kuwa mpira mdogo hugusa hewa kwenye eneo dogo sana, hivyo karibu haipati kuzuia na huanguka kwa kasi, ikivutwa moja kwa moja chini na graviti. Kinu cha upepo kuzunguka kwa upepo, au mwavuli kukaribia kupeperushwa siku ya upepo mkali, pia kunahusiana na kani hii ya kuzuia ya hewa." },
  { id:39, topic:"Mnyumbuko", emoji:"🏹",
    question:"Unapopinda kwa nguvu zako zote mwanzi mgumu na imara, au tawi laini la mti, kisha ukauachilia ghafla, hurudi kwa nguvu kwenye umbo lake la awali. Unaweza kutumia sifa hii (mnyumbuko) kwa nini ili kutengeneza chombo chenye manufaa maishani?",
    choices:["Friji ili chakula kisioze","«Upinde na mshale» wa kurusha mshale kwa mawindo ya mbali, au «mtego» unaorusha vitu vizito","Kichujio cha kusafisha maji","Chombo cha kupaka rangi nguo kuwa nyeupe"],
    answerIndex:1,
    explanation:"Mpira na spring, na pia mwanzi na matawi ya miti, vina sifa ya ajabu iitwayo «mnyumbuko»: ukitia nguvu umbo lake hupinda, na ukiachilia hujaribu kurudi kwenye umbo lake la awali kwa kasi kubwa. Wakati unaushikilia umepindwa kwa mkono, nguvu anayotia mtu huhifadhiwa kwa muda ndani ya chombo hicho kama «nishati». Wakati unaachilia, nguvu hiyo iliyohifadhiwa huachiliwa kwa pamoja, hivyo unaweza kurusha mshale mbali mara nyingi zaidi, au kuendesha mtego, kuliko kurusha kwa mkono pekee. Kwa kutumia nguvu hii waliyo nayo mimea ya asili, binadamu ametengeneza vyombo vya uwindaji na maisha tangu zamani za kale." },
  { id:40, topic:"Kulainisha", emoji:"🛢️",
    question:"Magurudumu ya mkokoteni, au bawaba ya mlango, yameanza kutoa mlio wa kukerakera kila unapoyasogeza na kuwa mazito. Ukidondosha matone machache ya «mafuta» hapa, kwa nini yanasogea kwa wepesi tena?",
    choices:["Kwa sababu mafuta huyeyusha chuma na kukifanya chepesi","Kwa sababu mafuta hugandamana na kuwa gundi","Kwa sababu mafuta huingia kwenye nafasi kati ya chuma na chuma na kupunguza sana kani ya kuzuia ya kukwaruzana (msuguano)","Kwa sababu harufu ya mafuta hufukuza wadudu"],
    answerIndex:2,
    explanation:"Mashine au chombo kinaposogea, kuna sehemu ambapo chuma hukwaruzana na chuma moja kwa moja na kwa nguvu. Hapo hufanya kazi kani ya kuzuia yenye nguvu sana iitwayo msuguano, na ikiachwa hivyo hujikwarua na kuharibika, au huhitaji nguvu kubwa mno kuisogeza. Unapopaka mafuta, utando mwembamba wa mafuta hutengenezwa kwenye nafasi ndogo ya chuma na kuzuia visikwaruzane moja kwa moja. Kwa sababu kani ya kuzuia hutoweka kwa pamoja, chombo husogea kwa wepesi wa kushangaza na nguvu ndogo. Kwa kupaka tu mafuta kidogo ya kupikia au mafuta ya mimea kwenye chombo, chombo hudumu zaidi na hupunguza sana matumizi ya nguvu za mtu." },
  { id:41, topic:"Radi", emoji:"⚡",
    question:"Radi inapopiga na uko nje, ni wapi salama zaidi kukimbilia?",
    choices:["Chini kabisa ya mti mrefu","Katikati ya uwanja mpana wazi","Ndani ya jengo imara, au gari lililozungukwa na chuma","Umesimama ukishikilia mwavuli mkubwa"],
    answerIndex:2,
    explanation:"Radi ina mwelekeo mkubwa wa kupiga vitu virefu. Kwa hiyo, ukisimama peke yako katika uwanja wazi, binadamu huwa kitu kirefu chenye ncha zaidi kuzunguka, na hatari ya kupigwa moja kwa moja huwa kubwa sana. Pia, kusimama chini kabisa ya mti mrefu ni hatari: radi inayopiga mti inaweza kuruka hadi mwilini mwako, jambo linaloitwa «mpigo wa kando», na kusababisha jeraha la kifo. Mahali salama zaidi ni ndani ya jengo imara la zege, au ndani ya gari lililozungukwa na mabamba ya chuma. Hata radi ikipiga gari, umeme hupita kwenye chuma cha nje na kushuka ardhini, hivyo watu walio ndani huwa salama kabisa." },
  { id:42, topic:"Mafuriko", emoji:"🌊",
    question:"Mvua kubwa inapogeuza barabara kuwa mto na huna budi kutembea majini ili kuhama, ni nini salama zaidi kuvaa miguuni?",
    choices:["Bila viatu (peku)","Kandambili","Viatu vilivyofungwa imara kwa kamba","Buti za mpira ndefu"],
    answerIndex:2,
    explanation:"Chini ya barabara iliyojaa maji hujificha hatari nyingi zisizoonekana: vioo vilivyovunjika, makopo makali, mashimo ya kifuniko cha mfereji yaliyofunguka. Bila viatu au kwa kandambili unajeruhi miguu kwa urahisi na huwezi tena kusonga. Buti za mpira huonekana nzuri, lakini maji yakiingia kutoka juu huwa nzito kama mito ya maji, miguu haiinuki kabisa, na hilo hukuzuia kutembea au kukuzamisha. Salama zaidi ni viatu visivyochomoka na vyenye sole gumu: «viatu vya michezo vilivyofungwa imara kwa kamba». Havizidi uzito hata maji yakiingia, na vinalinda miguu yako huku vikikuwezesha kutembea kwa uthabiti." },
  { id:43, topic:"Kuhama", emoji:"⛰️",
    question:"Mafuriko kutokana na mvua kubwa au tsunami yamefika, na maji yanafika miguuni mwako. Ni upande gani ni sahihi kukimbia?",
    choices:["Kuelekea chini ya mto ambapo maji hutiririka kwa kasi (mahali pa chini)","Kilima au mlima mrefu wa karibu, au ghorofa ya juu ya jengo imara (mahali pa juu)","Nyumba ya jamaa iliyo mbali","Chumba cha chini ya ardhi cha nyumba yako (chini kuliko ardhi)"],
    answerIndex:1,
    explanation:"Wakati wa mafuriko au tsunami, maji hujikusanya kwa nguvu kubwa, kuanzia maeneo ya chini kabisa. Ukijificha katika chumba cha chini ya ardhi kilicho chini kuliko ardhi, maji huingia kwa mara moja kupitia mlango, huwezi kutoka, na unazama. Pia, ukijaribu kukimbia mbali kwa kuzunguka-zunguka, unaweza kugongwa na miti au magari yaliyosombwa, au mkondo mkali ukakwangua chini ya miguu yako na ukasombwa. Maji yanapokaribia, kanuni si kwenda mbali, bali kuelekea «mahali pa juu palipo karibu zaidi na ulipo sasa». Kupanda kilima au mlima wa karibu, au ghorofa ya pili au ya tatu ya jengo imara la zege, na kusubiri maji yapungue, ndio chaguo linalolinda maisha yako." },
  { id:44, topic:"Kiharusi cha joto", emoji:"🥵",
    question:"Katika siku ya joto kali sana yenye mwanga mkali sana wa jua, ni nini muhimu zaidi kuzuia ugonjwa ambao mwili huzidi joto na unaanguka (kiharusi cha joto)?",
    choices:["Kuvumilia bila kunywa maji","Kujipaka matope baridi mwili mzima","Kupumzika kivulini, na kunywa maji salama kidogo kidogo, mara nyingi","Kukimbia sana ili kutoka jasho"],
    answerIndex:2,
    explanation:"Ukikaa muda mrefu mahali pa joto kali sana, maji na chumvi mwilini mwako hutoka kama jasho, na mwili hauwezi tena kushusha joto lake wenyewe. Hii ndiyo hali ya kutisha iitwayo kiharusi cha joto. Ili kuizuia, ni muhimu kupata «kivuli baridi» ambapo mwanga wa jua haukupigi moja kwa moja, na kupumzisha mwili. Na unahitaji kunywa maji salama yaliyochemshwa kisha yakapozwa, kidogo kidogo na mara nyingi, hata kabla ya kuhisi kiu. Badala ya kunywa mengi kwa mara moja, kunywa funda ndogo mara kwa mara hufanya mwili unyonye maji vizuri, hivyo unaweza kupitisha siku ukiwa na nguvu na salama hata chini ya jua kali." },
  { id:45, topic:"Matetemeko", emoji:"🪑",
    question:"Tetemeko la ardhi linapotokea na ardhi na nyumba yako vinaanza kutikisika kwa nguvu, ni nini cha kwanza kufanya ndani ya chumba?",
    choices:["Kukimbia nje kwa hofu","Kujificha chini ya meza imara na kulinda kichwa na mwili","Kufunga madirisha vizuri na kuangalia nje","Kushindilia vitu vingi kwenye begi"],
    answerIndex:1,
    explanation:"Tetemeko linapotokea, hatari zaidi ni «vitu kuanguka kutoka juu» na «samani kuanguka». Ukikimbia nje kwa hofu, kutoka sehemu za juu za majengo vinaweza kuanguka vioo vilivyovunjika na vigae vikakupiga kichwani, hatari kubwa sana ya jeraha zito. Unapohisi mtikisiko, kwanza jiingize papo hapo chini ya «meza au kitanda imara», shika miguu ya meza kwa nguvu na ulinde kichwa na mwili wako. Kama hakuna pa kujificha, funika kichwa chako kwa nguvu kwa mto, begi au mikono yako mwenyewe, jikunyate katikati ya chumba ambapo samani hazitakuangukia, na subiri kimya hadi mtikisiko ukome kabisa, hii ndiyo salama zaidi." },
  { id:46, topic:"Radi", emoji:"⚡",
    question:"Radi inapopiga karibu sana, ni tendo gani la hatari zaidi kufanya nje?",
    choices:["Kushikilia toy ya plastiki","Kushikilia fimbo ndefu ya chuma au ndoano ya kuvua samaki iliyoinuliwa juu kuelekea angani","Kuvaa nguo za kitambaa","Kuvaa viatu vya mbao"],
    answerIndex:1,
    explanation:"Radi ina mwelekeo wa kutisha wa kupiga kwa kujikita kwenye vitu vilivyo «virefu na vyenye ncha kali». Kwa hiyo, ukiwa nje ukishikilia fimbo ndefu ya chuma, ndoano ya kuvua, au mwavuli mrefu ukiuinua juu kuelekea angani, huwa kama antena inayoita radi, na inakupiga moja kwa moja. Unaposikia radi ikinguruma, lalisha mara moja fimbo yoyote ndefu unayoshikilia ardhini kwa mlalo, shusha mkao wako kadiri uwezavyo, na uchuchumae ukishusha kichwa. Kisha hama mara moja ndani ya jengo salama." },
  { id:47, topic:"Maporomoko ya ardhi", emoji:"⚠️",
    question:"Mvua kubwa inaponyesha bila kukoma karibu na mlima, ni ishara gani ya hatari kwamba mlima unaweza kuporomoka (maporomoko ya ardhi)?",
    choices:["Maji ya mto ghafla yanakuwa meusi na yenye matope, na vipande vingi vya mbao vinasombwa","Mawe madogo yanaanguka kutoka mlimani kidogo kidogo","Kutoka ndani ya ardhi kunasikika sauti ya ajabu kama mngurumo wa ardhi","Hizi zote ni ishara za hatari"],
    answerIndex:3,
    explanation:"Mvua kubwa inaponyesha mlimani, udongo hunyonya maji kwa wingi mkubwa, na katika muda fulani ghafla mwinuko au mlima mzima huporomoka kwa mara moja, maafa makubwa yaitwayo «maporomoko ya ardhi» au «mtiririko wa matope na mawe». Kabla tu ya kutokea kwake, asili daima hutoa ishara kadhaa za onyo. Maji ya mto kuwa na matope ghafla na kuongezeka kwa mbao zinazosombwa ni ushahidi kwamba juu udongo umeanza kuporomoka. Pia, mawe madogo yakianguka kutoka mlimani, au sauti ya kutisha ikisikika kutoka ardhini, ni ishara kwamba mlima mzima unakaribia kuanza kusonga. Ukiona au ukihisi hata moja ya ishara hizi, ni lazima uondoke mahali hapo sekunde moja mapema na ukimbilie mahali pa juu palipo imara." },
  { id:48, topic:"Mafuriko", emoji:"🦯",
    question:"Unapolazimika kutembea katika maji ya mafuriko, katika barabara ambapo matope hufanya ardhi isionekane kabisa, unawezaje kutembea ili uwe salama?",
    choices:["Kukimbia kwa kasi yote ili kuponyoka haraka","Kutumia fimbo ndefu kugonga na kuhakikisha ardhi ni salama, hatua kwa hatua","Kufumba macho na kwenda moja kwa moja mbele","Kuvua nguo zote na kusonga mbele kwa kuogelea"],
    answerIndex:1,
    explanation:"Baada ya mafuriko, maji ya barabara huwa ya kahawia yenye matope yaliyochanganyika na takataka, hivyo huoni kabisa ardhi ilivyo chini ya miguu. Kwa kweli, chini ya maji kifuniko cha mfereji kinaweza kuwa kimechomoka kikiacha shimo refu, au ardhi inaweza kuwa imemomonyoka kuwa mfereji wenye kina. Ukikimbia au ukitembea bila kutambua, unaweza kuanguka kwenye shimo refu kwa muda mfupi na kuzama majini. Unapotembea majini, daima shikilia «fimbo ndefu na imara» kama bakora, na kabla ya kupiga hatua inayofuata, gonga ardhi kwa fimbo ili uhakikishe «kama kuna shimo», ukisonga taratibu kwa tahadhari, hii ndiyo namna ya kutembea inayolinda maisha yako." },
  { id:49, topic:"Kimbunga", emoji:"🌪️",
    question:"Kimbunga (upepo mkali unaozunguka kwa kasi ya ajabu) kinapokaribia, ni wapi salama zaidi kujificha ndani ya nyumba?",
    choices:["Karibu kabisa na dirisha lenye mwonekano mzuri wa nje","Juu ya paa ambapo upepo unafurahisha","Chumba imara kisicho na madirisha, au choo au kabati katikati ya nyumba","Umelala juu ya kitanda kikubwa"],
    answerIndex:2,
    explanation:"Kimbunga ni mvumo mkali zaidi duniani, chenye nguvu za kutosha kupeperusha paa la nyumba au kuzungusha miti mikubwa na magari angani. Kimbunga kinapokaribia, cha kutisha zaidi ni «kitu kinachoruka kutoboa kioo cha dirisha na vipande vya kioo kutawanyika chumbani kwa kasi ya ajabu». Kwa hiyo kuwa karibu na dirisha kunamaanisha jeraha zito. Mahali salama zaidi ni ambapo kuta ni nene zaidi na hakuna dirisha kabisa: «choo katikati ya nyumba, chumba imara au kabati». Jifungie humo, funika kichwa kwa mto au blanketi, jikunyate, na subiri kimya dhoruba ipite, hii ndiyo namna sahihi ya kujificha." },
  { id:50, topic:"Moto", emoji:"🔥",
    question:"Moto unapozuka na moshi mwingi unajaa chumbani, unawezaje kukimbia nje?",
    choices:["Kusimama wima mrefu na kukimbia kwa kasi yote","Kuchukua mkao wa chini ukitambaa sakafuni, kufunika mdomo kwa kitambaa, na kukimbia","Kufunga madirisha yote ili kufungia moshi","Kujifunika blanketi kubwa na kulala kitandani"],
    answerIndex:1,
    explanation:"Moshi unaotokana na moto una sumu nyingi yenye madhara (kama monoksidi kaboni) inayomzimisha mtu papo hapo anapoivuta. Kwa kuwa moshi ni wa moto, chumbani hujikusanya kwanza «kuanzia dari (sehemu ya juu)», na hewa safi kiasi hubaki mwisho karibu na sakafu. Kwa hiyo, ukisimama wima, unavuta moshi wenye sumu mzito zaidi moja kwa moja na hauwezi tena kusonga. Unapokimbia, dumisha «mkao wa chini» kifua kikiwa karibu na sakafu, bonyeza kwa nguvu kitambaa au nguo iliyolowa juu ya mdomo na pua, vuta hewa ya karibu na sakafu, na utoke nje haraka, hii ndiyo namna sahihi ya kukimbia." },
  { id:51, topic:"Tsunami", emoji:"🌊",
    question:"Unapokuwa karibu na bahari na ukahisi tetemeko kali, ni jambo gani muhimu zaidi unalopaswa kufanya mara moja?",
    choices:["Kwenda kuangalia kama kuna samaki baharini","Kurudi nyumbani ili kukusanya vitu vyako vyote","Kuondoka pwani na kupanda haraka mlima mrefu au mwinuko imara wa juu","Kukaa kimya ufukweni wa mchanga"],
    answerIndex:2,
    explanation:"Tetemeko kubwa linapotokea chini ya bahari, ardhi ya sakafu ya bahari husogea kwa nguvu, na maji yote yanayozunguka husonga mbele kama wimbi kubwa kama ukuta, maafa makubwa yaitwayo «tsunami». Tofauti na mawimbi ya kawaida, tsunami ina uzito na nguvu ya uharibifu ya ajabu, yenye uwezo wa kusomba majengo na nyumba kwa muda mfupi. Pia, kabla tsunami haijafika, maji ya bahari yanaweza kupwa ghafla na kuonyesha mchanga, lakini ukienda kuangalia kwa kufurahia, muda unaofuata unamezwa na wimbi kubwa. Ukihisi mtikisiko karibu na bahari, usichukue kitu chochote, ondoka baharini sekunde moja mapema, na ukimbilie «kwa vyovyote kilima au mlima mrefu, au ghorofa ya juu ya jengo imara». Baada ya kuona wimbi, kukimbia kunakuwa kumechelewa." },
  { id:52, topic:"Baridi", emoji:"🧥",
    question:"Unapoweza kupotea mahali pa baridi kali sana wakati wa baridi, ni tendo gani bora zaidi kuhifadhi joto la mwili na kuendelea kuishi?",
    choices:["Kunywa maji baridi mengi","Kubaki na nguo zilizolowa kama zilivyo","Kujificha mahali ambapo upepo haukupigi, na kuvaa tabaka nyingi za nguo au kitambaa","Kulala moja kwa moja juu ya theluji"],
    answerIndex:2,
    explanation:"Mwili wa binadamu, joto lake likishuka sana, hauwezi tena kusonga na hupoteza maisha (joto la chini la mwili). Hasa «upepo» na «nguo zilizolowa» ni maadui hatari wanaonyang'anya joto la mwili kwa muda mfupi. Ili kujilinda mahali pa baridi, kipaumbele cha kwanza ni kujificha mahali ambapo «upepo haukupigi kabisa», kama nyuma ya mwamba mkubwa au ndani ya jengo. Kisha, kama nguo zimelowa, hakikisha unabadilisha kuvaa kavu, na uvae «tabaka nyingi» za nguo, kitambaa au karatasi ulizonazo. Kurundika kitambaa hutengeneza tabaka la hewa ya joto kati ya tabaka, ukuta wa kichawi usioacha joto la mwili wako litoke. Kulala moja kwa moja juu ya theluji hunyang'anya joto, hivyo kutandika majani au katoni ardhini ili kukalia pia ni hekima muhimu." },
  { id:53, topic:"Volkeno", emoji:"🌋",
    question:"Volkeno ya karibu (mlima unaotema moto na matope ya moto) inapolipuka ghafla, unawezaje kujilinda dhidi ya majivu na mawe yanayoruka kutoka angani?",
    choices:["Kutazama angani na kuchunguza kwa makini kinachoanguka","Kuingia ndani ya jengo imara (kama nyumba ya zege) na kufunika mdomo na pua kwa kitambaa","Kuruka katika mto wa karibu na kuogelea","Kukimbia kwa kasi yote kuelekea mlimani"],
    answerIndex:1,
    explanation:"Volkeno inapolipuka, kutoka kileleni huanguka kutoka angani «lava» nzito iliyowaka wekundu na mawe makubwa kwa kasi ya kutisha. Yakikupiga kichwani ni hatari kwa maisha, hivyo ni lazima ujifiche mara moja ndani ya jengo imara «la zege au la mfano huo». Pia, «majivu ya volkeno» yanayotemwa na volkeno si mchanga wa kawaida, bali kama miiba ya kioo iliyosagwa laini. Kuyavuta hujeruhi mapafu hivyo huwezi kupumua, na yakiingia machoni husababisha maumivu makali hivyo huwezi kuyafungua. Baada ya kujificha ndani ya jengo, funga madirisha vizuri, funika mdomo na pua kwa nguvu kwa barakoa au kitambaa kilicholowa maji, na ujilinde usivute kamwe majivu machafu." },
  { id:54, topic:"Ukungu", emoji:"🌫️",
    question:"Ukungu (ukungu mweupe unaoenea hewani) unapokuwa mzito sana na huoni mbele kabisa, ni nini cha hatari zaidi unapotembea?",
    choices:["Kusimama palepale ulipo","Kutosikia tena sauti zinazokuzunguka","Kutoona mahali ulipo au sehemu za hatari kama miinuko, hivyo kupotea njia au kuanguka","Nguo kuwa na unyevu kidogo"],
    answerIndex:2,
    explanation:"Ukungu mzito ukitokea, hata mandhari ya mita chache mbele huwa nyeupe pe na huoni chochote. Ukijilazimisha kuendelea kutembea hivi, hisia yako ya mwelekeo, unakoelekea, hupooza kabisa, na inaweza kusababisha ajali kubwa: kupotea katika msitu mzito wa hatari, au kutotambua mwinuko au mto wenye kina ulio mbele yako moja kwa moja na kuporomoka kichwa kwanza hadi kufa. Usipoona mbele, kamwe usisonge mbele kwa nguvu. Kinga salama zaidi ni «kusimama palepale ulipo» mahali penye kushikilia kwa uhakika, kama katikati ya barabara pana salama, na kusubiri kimya hadi ukungu uondoke na uone tena vizuri kukuzunguka." },
  { id:55, topic:"Mporomoko wa mwinuko", emoji:"🪨",
    question:"Unapokuwa karibu na ukuta mrefu wa udongo (mwinuko) baada ya mvua kubwa kunyesha, ni nini lazima uwe makini nacho kabisa?",
    choices:["Maji ya mvua yanaweza kupenya kwenye mwinuko nao ukaporomoka ghafla (mporomoko wa mwinuko), kwa hiyo ondoka mara moja","Kupanda juu ya mwinuko na kucheza kwa furaha","Kupiga hema chini kabisa ya mwinuko na kulala","Kumwaga maji mengi kwenye ukuta wa mwinuko"],
    answerIndex:0,
    explanation:"Mwinuko au mteremko wa zamani wa udongo, baada ya mvua kubwa, una maji mengi mno yaliyojikusanya hadi kikomo ndani ya udongo, na uko katika hali dhaifu sana, laini kama sponji. Hata baada ya mvua kukoma, baada ya saa kadhaa hadi siku kadhaa, mara nyingi hutokea «mporomoko wa mwinuko» ambapo ukuta mzima huporomoka kwa mara moja kana kwamba unalipuka, bila sauti yoyote. Ukicheza au ukilala chini ya mwinuko, unafukiwa chini ya tani nyingi za udongo mzito kwa muda mfupi na huwezi tena kuokolewa. Wakati wa mvua kubwa, na kwa siku kadhaa baada ya mvua kukoma, daima zingatia kanuni: «usikaribie kamwe ukuta mrefu wa udongo au mwinuko, ondoka mara moja»." },
  { id:56, topic:"Kuhama", emoji:"🏃",
    question:"Mto ulio karibu na nyumba yako unapozidi kupanda kwa mvua kubwa na uko karibu kufurika, ni lini unapaswa kuanza kuhama?",
    choices:["Baada ya maji kuingia ndani ya nyumba","Mapema, wakati bado kuna mwanga nje na hakuna maji yaliyojaa barabarani, wakati ni salama","Kusubiri kimya hadi maji ya mto yafurike kabisa","Kulifikiria baada ya kuingia kitandani kulala"],
    answerIndex:1,
    explanation:"Kujaribu kuhama baada ya mto kufurika na maji kuanza kujaa barabarani ni uamuzi wa hatari zaidi, uliochelewa mno. Maji yanapojaa hadi kimo cha goti barabarani, hata mwanaume mzima husombwa na nguvu kali ya maji na hawezi kutembea kabisa. Pia, giza likiingia usiku, huwezi tena kutofautisha wapi ni barabara na wapi ni mto, na unaangukia mtoni na kusombwa katikati ya kuhama. Wakati sahihi zaidi wa kuanza kuhama ni wakati bado kuna «mwanga nje na hakuna maji yaliyojaa miguuni mwako, wakati ni salama». Ukihisi hatari hata kidogo kutoka mto unaopanda, punguza mizigo hadi kiwango cha chini na uanze safari mapema kuelekea makazi ya juu salama, hii ndiyo hekima inayolinda maisha yako kwa uhakika." },
  { id:57, topic:"Mshtuko wa umeme", emoji:"🔌",
    question:"Baada ya tetemeko au mvua kubwa, unapokuta nyumbani waya wa umeme uliopasuka ukitoa cheche, kwa nini hupaswi kuugusa kamwe?",
    choices:["Kwa sababu mikono itachafuka kwa matope meusi","Kwa sababu umeme mkali unaopita kwenye waya hupita mwilini mwako na kusababisha jeraha zito, kama moyo kusimama (mshtuko wa umeme)","Kwa sababu waya ni baridi kama barafu","Kwa sababu chumba kitakuwa giza totoro"],
    answerIndex:1,
    explanation:"Kutoka waya uliopasuka, au kifaa cha umeme kilicholowa maji, umeme mkali sana usioonekana kwa jicho la binadamu unaweza kuwa unavuja nje. Ukiugusa kwa mkono bila kujua, umeme wa waya hupenya mwili wa binadamu kwa muda mfupi na kushuka kuelekea ardhini. Hii inaitwa «mshtuko wa umeme». Kupata umeme mkali hakuchomi tu mwili wako, bali kunaweza kusimamisha moyo wako papo hapo, ajali ya kifo kwa muda mfupi. Hasa wakati mwili au mikono yako imelowa maji, umeme hupita mwilini mwako kwa urahisi mara nyingi zaidi, jambo la hatari zaidi. Ukikuta waya unaotoa cheche au waya uliokatika, usikaribie kamwe, usiguse, na umwarifu mtu mzima." },
  { id:58, topic:"Vimbunga", emoji:"🌀",
    question:"Upepo mkali sana (kimbunga au tufani) unapovuma, kwa nini kutoka nje ni hatari kiasi cha kutishia maisha?",
    choices:["Kwa sababu hewa ya nje haina ladha nzuri sana","Kwa sababu mabango ya maduka, vigae vya paa, na matawi makubwa ya miti huruka na kukupiga kichwani","Kwa sababu nguo unazozipenda huchafuka kwa matope","Kwa sababu kupigwa na upepo mkali mwili mzima hukunenepesha"],
    answerIndex:1,
    explanation:"Wakati wa dhoruba kali kama kimbunga au tufani, nguvu ya upepo huwa mbali zaidi ya wanavyofikiri binadamu. Kusombwa na upepo wenyewe ni hatari, lakini cha kutisha zaidi ni «kila kitu mjini kuwa silaha na kuruka kuelekea kwako». Mabango mazito ya maduka, vigae vigumu vya paa, matawi yaliyovunjika ya miti na vinginevyo huja vikiruka kwa ubavu kwa kasi kama kisu kikali au risasi. Hata kimoja kati ya hivi kikikupiga mwili, ni jeraha la kifo. Wakati sauti ya upepo mkali inasikika, hata uwe na shughuli kiasi gani, «hupaswi kutoka nje kamwe». Kubaki ndani ya nyumba salama, mbali na madirisha, na kusubiri kimya dhoruba ipite kabisa, ndilo tendo sahihi." },
  { id:59, topic:"Dhoruba za mchanga", emoji:"🏜️",
    question:"Dhoruba ya mchanga (mchanga na vumbi vinavyoinuliwa na upepo mkali) inapotokea, unapaswa kufanya nini ili kulinda macho na mapafu yako?",
    choices:["Kufungua macho na mdomo kwa upana na kupokea upepo","Kufunika kwa nguvu uso, mdomo na pua kwa skafu au kitambaa, na kujificha ndani ya jengo imara","Kutoka nje na kushindana mbio na marafiki","Kutazama angani ili kuona mchanga unaruka mbali kiasi gani"],
    answerIndex:1,
    explanation:"Dhoruba ya mchanga inayotokea karibu na jangwa au katika eneo kavu ni dhoruba kubwa inayoinua kwa upepo mkali mamia ya mamilioni ya chembe ndogo za mchanga na vumbi chafu. Ukivuta mchanga na vumbi hivi kama vilivyo, mchanga hujikusanya ndani kabisa ya mapafu yako na unakohoa kwa nguvu, ugonjwa mbaya ambao huwezi kupumua. Pia macho yanaweza kujeruhiwa na mchanga hivyo huoni. Dhoruba ya mchanga inapokaribia, hama mara moja ndani ya jengo imara na ufunge madirisha na milango bila nyufa. Kisha, rundika mara nyingi skafu au kitambaa cha nguo ulichonacho na «funika uso wote, hasa mdomo na pua, kwa nguvu» ili kutengeneza barakoa inayozuia mchanga kuingia. Hadi dhoruba ipite, jilinde kwa kuvuta kimya hewa inayopita kwenye kitambaa tu." },
  { id:60, topic:"Mafuriko", emoji:"🌊",
    question:"Wakati wa mafuriko ambapo maji ya matope yanaingia kwa nguvu ndani ya nyumba, kwa nini kuwa katika chumba cha chini ya ardhi (chumba kilicho chini kuliko ardhi) ni marufuku kabisa?",
    choices:["Kwa sababu chumba cha chini ya ardhi ni baridi na cha starehe zaidi kuliko vyumba vingine","Kwa sababu maji ya matope kutoka barabara ya juu huingia kwa mara moja kama maporomoko ya maji, mlango wa kutokea hufungwa, na unazama kwa muda mfupi","Kwa sababu chumba cha chini ya ardhi huwa giza umeme ukikatika","Kwa sababu wakati mwingine panya wadogo huishi chumba cha chini ya ardhi"],
    answerIndex:1,
    explanation:"Chumba cha chini ya ardhi au chumba cha nusu-chini ya ardhi kilicho chini kuliko ardhi hugeuka kuwa «mahali pa kifo zaidi, pa hatari zaidi duniani» mafuriko yanapotokea. Maji ya matope yaliyofurika kwenye barabara ya juu huingia kwa mara moja kupitia ngazi na madirisha ya chumba cha chini kwa nguvu na uzito wa ajabu wa maporomoko ya maji. Nguvu ya maji yanayoshuka kwenye ngazi ni kali, na hata nguvu ya mtu mzima haiwezi kuipinga ili kupanda juu. Zaidi ya hayo, uzito wa maji hubonyeza mlango wa chumba cha chini kutoka nje, na inakuwa haiwezekani kabisa kuufungua kutoka ndani. Chumba hujaa maji kwa muda mfupi, njia ya kutoroka hupotea kabisa, na mtu anazama. Mvua ikiwa kali, kanuni kamili ya chuma ni: «usikaribie kamwe chumba cha chini ya ardhi, panda sasa hivi ghorofa ya juu»." },
  { id:61, topic:"Kugawanya", emoji:"🍎",
    question:"Kuna tufaha 10. Ukizigawanya sawa kati ya watu 5, kila mmoja anapata ngapi?",
    choices:["Tufaha 1","Tufaha 2","Tufaha 3","Tufaha 5"],
    answerIndex:1,
    explanation:"Kugawanya vitu sawa kati ya wote ndiyo wazo la ‘kugawanya’. Ili kugawanya tufaha 10 sawa kati ya watu 5, kwanza mpe kila mmoja tufaha 1; hapo tufaha 5 zinatumika. Bado una tufaha 5, hivyo unaweza kumpa kila mmoja tufaha 1 nyingine. Sasa tufaha zote 10 zimegawanywa, na kila mtu ana ‘tufaha 2’. Ili mtu asipate zaidi huku mwingine akihuzunika kwa kupata pungufu, hekima ya kuhesabu kwa makini na kugawanya kwa haki ni nguvu muhimu sana ya kuishi pamoja kwa amani." },
  { id:62, topic:"Kuzidisha", emoji:"🍬",
    question:"Unanunua peremende 3, kila moja sarafu 5. Unalipa jumla ngapi?",
    choices:["Sarafu 5","Sarafu 8","Sarafu 15","Sarafu 20"],
    answerIndex:2,
    explanation:"Hesabu ambapo namba ile ile inarudiwa tena na tena inaitwa ‘kuzidisha’. Peremende 3 za sarafu 5 kila moja maana yake 5 inaongezwa mara tatu. 5 jumlisha 5 ni 10, na ukiongeza 5 nyingine inakuwa 15 jumla. Unaponunua dukani, kama hujui hesabu hii, mtu anaweza kukutoza zaidi ya inavyostahili na kukudanganya bila wewe kutambua. Kujua jinsi kuzidisha kunavyojumlisha namba ile ile kwa pamoja kunakuwa silaha yenye nguvu ya kulinda pesa zako za thamani na kufanya biashara na kuishi vizuri." },
  { id:63, topic:"Kutoa (chenji)", emoji:"🪙",
    question:"Unaenda dukani na sarafu 10 na kununua samaki kwa sarafu 7. Chenji (pesa zinazorudi) ni ngapi?",
    choices:["Sarafu 2","Sarafu 3","Sarafu 5","Sarafu 7"],
    answerIndex:1,
    explanation:"Kuondoa ulichotumia kutoka jumla uliyo nayo kunaitwa ‘kutoa’. Unapomlipa muuzaji sarafu 7 kati ya 10 zako, ili kujua kilichobaki unatoa 7 kutoka 10. Kwa kuhesabu kurudi nyuma kutoka 10 moja moja—9, 8, 7, 6, 5, 4, 3—zinabaki 3. Pesa hizi zilizobaki zinaitwa ‘chenji’. Kama huwezi kuhesabu chenji mwenyewe baada ya kununua, unaweza kupata hasara, kwa mfano wakikupa chenji pungufu. Kuimudu kutoa ni hatua ya kwanza ya kuishi kwa kujitegemea bila kudanganywa katika jamii." },
  { id:64, topic:"Kuhesabu kwa kibadala", emoji:"📦",
    question:"Unapakia mzigo kwenye gari. Uzito wa sanduku moja ni sawa na mawe madogo 3. Kama kuna masanduku 3, ni sawa na mawe mangapi jumla?",
    choices:["Mawe 3","Mawe 6","Mawe 9","Mawe 12"],
    answerIndex:2,
    explanation:"Hii ni hekima ya kubadilisha uzito wa jumla kwa kipimo kingine—hapa idadi ya mawe. Sanduku moja ni mawe 3, hivyo masanduku 3 maana yake ‘seti 3 za mawe 3’. 3 jumlisha 3 ni 6, na ukiongeza 3 inakuwa 9. Unapoweza kuhesabu si idadi ya vitu unavyoona tu, bali ‘vina uzito gani kweli’ kwa kuvibadilisha na kitu kingine, unaweza kuzuia gari lisivunjike kwa mzigo mzito kupita kiasi na kubeba vitu kwa mpango bila kumlemea ng'ombe au farasi." },
  { id:65, topic:"Kanuni ya mpangilio", emoji:"🔷",
    question:"Kitendawili cha mchoro. ‘Duara, pembetatu, mraba, duara, pembetatu, mraba, duara, pembetatu’—umbo gani linafuata?",
    choices:["Duara","Pembetatu","Mraba","Msalaba"],
    answerIndex:2,
    explanation:"Hiki ni kitendawili cha kutafuta ‘kanuni (mchoro)’ katika jinsi vitu vilivyopangwa. Ukiangalia mpangilio kwa makini, unaona maumbo matatu—duara, pembetatu, mraba—yakirudia kwa mpangilio ule ule tena na tena. Seti moja ya ‘duara, pembetatu, mraba’ ikiisha, inaanza ‘duara, pembetatu, mraba’ inayofuata. Kitendawili kimeishia kwenye ‘duara, pembetatu’, hivyo kwa kufuata kanuni, kinachofuata lazima ni ‘mraba’. Hata katika dunia inayoonekana bila mpangilio, kuangalia kwa makini mara nyingi hufichua kanuni zilizofichika. Kukuza nguvu hii ya ubongo ya kutafuta michoro kunakufanya bora zaidi katika kutabiri na kupanga ya baadaye." },
  { id:66, topic:"Mantiki", emoji:"📏",
    question:"Kuna fimbo 3 za urefu tofauti (A, B, C). A ni ndefu kuliko B. B ni ndefu kuliko C. Fimbo gani ndiyo ndefu zaidi?",
    choices:["Fimbo A","Fimbo B","Fimbo C","Zote urefu sawa"],
    answerIndex:0,
    explanation:"Hiki ni kitendawili cha ‘fikira za kimantiki’ ambapo unapanga taarifa kichwani ili kufikia jibu sahihi. Kwanza, kutoka ‘A ni ndefu kuliko B’ tunajua A iko juu ya B. Kisha, kutoka ‘B ni ndefu kuliko C’ tunajua B iko juu ya C. Ukiziunganisha katika mstari wima, mpangilio unakuwa: juu A, katikati B, chini C. Hivyo ndefu zaidi ni ‘fimbo A’. Hata bila vitu halisi mbele yako, nguvu hii ya kuunganisha maneno na masharti ili kupata jibu sahihi ni muhimu sana kwa kupata chanzo cha tatizo na kulitatua kwa busara." },
  { id:67, topic:"Hekima ya kugawa", emoji:"🍞",
    question:"Kitendawili cha kugawa chakula sawa. Ili kugawanya mkate mmoja wa mviringo sawa kwa ‘watu 4’, unahitaji mikato mingapi iliyonyooka ya kisu?",
    choices:["Mkato 1","Mikato 2","Mikato 3","Mikato 4"],
    answerIndex:1,
    explanation:"Hii ni hekima ya ‘utambuzi wa nafasi’—kugawa umbo kichwani. Kwanza kata mkate wa mviringo katikati moja kwa moja ‘mara 1’, unagawanyika sehemu mbili. Kisha kata ‘mkato wa 2’ katikati moja kwa moja, ukivuka mkato wa kwanza kama alama ya kujumlisha, mkate unagawanyika vizuri vipande 4 sawa. Kwa mienendo 2 tu ya kisu unaweza kuugawanya sawa kwa watu 4. Kujua sifa za maumbo hivi kunakuwezesha kugawa vitu kwa ufanisi na haki, bila juhudi za bure na bila mtu kutoridhika." },
  { id:68, topic:"Kuzidisha", emoji:"🐟",
    question:"Unauza samaki kwa pesa. Kuuza samaki 1 kunaleta sarafu 2. Ukiuza samaki 5, unapata sarafu ngapi jumla?",
    choices:["Sarafu 2","Sarafu 5","Sarafu 7","Sarafu 10"],
    answerIndex:3,
    explanation:"Hii ni kuzidisha, msingi wa biashara. Unapata sarafu 2 kwa kila samaki, hivyo kuuza samaki 5 maana yake sarafu 2 zimekusanyika mara 5. Kwa kuhesabu mbili mbili—2, 4, 6, 8, 10—inakuwa sarafu 10 jumla. Unapofanya kazi kwa bidii au kuuza ulichokuza, kama huwezi kuhesabu sawasawa ‘inapaswa kuwa pesa ngapi’, mfanyabiashara mbaya anaweza kushusha bei na kukunyonya, akikuachia pesa pungufu sana kuliko thamani ya kazi yako. Nguvu ya kuhesabu namba ni ngao inayolinda thamani ya kazi yako na kukuwezesha kuishi kwa neema zaidi." },
  { id:69, topic:"Nafasi ya makumi", emoji:"🔟",
    question:"Kitendawili cha makundi ya kumi. Kuna masanduku ambayo kila moja huchukua ‘kundi’ la 10. Kama una masanduku 3 ya namna hii na vitu 5 vilivyo peke yake, una jumla ngapi?",
    choices:["8","15","35","53"],
    answerIndex:2,
    explanation:"Namba tunazotumia kila siku zinafuata kanuni iitwayo ‘mfumo wa kumi’, ambapo 10 zikikusanyika zinapanda kwenye nafasi kubwa inayofuata. Masanduku 3 ya 10 maana yake 10, 20, 30—hilo pekee ni 30. Kuongeza vitu 5 vilivyo peke yake, 30 jumlisha 5 ni 35. Katika lugha na biashara nyingi duniani, vitu na pesa huhesabiwa katika ‘makundi haya ya kumi’. Mara unapoweza kuwazia kichwani jinsi masanduku (makumi) na vitu peke yake (mamoja) vinavyofanya kazi, hata namba kubwa zaidi kama 100 au 1000 zinakuwa rahisi kuhesabu." },
  { id:70, topic:"Kuhesabu hatua kwa hatua", emoji:"🥚",
    question:"Kuna mayai 8 kwenye kikapu. Unatumia 3 kupika. Baadaye, kuku anataga mayai 2 mapya. Sasa kuna mayai mangapi kwenye kikapu?",
    choices:["3","5","7","10"],
    answerIndex:2,
    explanation:"Hiki ni kitendawili ambapo unafanya hesabu ya ‘hatua mbili’ kwa mpangilio—namba inapungua kwanza kisha inaongezeka. Kwanza, toa mayai 3 yaliyotumika kupika kutoka mayai 8 ya mwanzo. 8 ondoa 3 ni 5, na wakati huu kikapu kina 5. Kisha kuku anataga mayai 2 mapya yanayoongezwa kwenye kikapu, hivyo sasa ongeza 2 kwa 5. 5 jumlisha 2 ni 7. Maishani, mabadiliko magumu kama ‘kupungua kisha kuongezeka’ hutokea kila siku. Unapoweza kupanga matukio kwa mpangilio kichwani na kuchanganya kujumlisha na kutoa, unakuwa hodari sana katika kusimamia na kupanga chakula cha nyumbani." },
  { id:71, topic:"Mara mbili", emoji:"🪣",
    question:"Kuna maji kwenye ndoo. Ndoo A inachukua ‘mara 2’ ya ndoo B. Ndoo B inachukua lita 4 za maji. Ndoo A inachukua lita ngapi za maji?",
    choices:["Lita 2","Lita 4","Lita 6","Lita 8"],
    answerIndex:3,
    explanation:"‘Mara 2 (maradufu)’ ya namba maana yake kuunganisha nyingine sawa nayo; yaani ‘kuijumlisha mara mbili’ au ‘kuizidisha kwa 2’. Ndoo B ina lita 4, na A ni kubwa mara mbili, hivyo fikiria sehemu mbili za lita 4. Kwa kuhesabu 4 jumlisha 4 unapata 8. Ndiyo maana ndoo A inachukua lita 8. Maishani mara nyingi tunasema ‘eneo maradufu’, ‘uzito maradufu’, ‘watu maradufu’, na kujua wazo la ‘mara’ kunakuwezesha kulinganisha kiasi kwa usahihi na kukadiria vizuri vifaa au maji ambayo kazi inahitaji." },
  { id:72, topic:"Mpangilio", emoji:"🧒",
    question:"Watoto 5 wamesimama kwenye safu iliyonyooka. Nyuma ya mtoto wa 3 kutoka mbele, kuna watoto wangapi waliosimama?",
    choices:["Mtoto 1","Watoto 2","Watoto 3","Watoto 4"],
    answerIndex:1,
    explanation:"Hiki ni kitendawili cha mantiki kuhusu kuelewa vizuri uhusiano kati ya idadi ya jumla na nafasi ya katikati. Kuna watoto 5 jumla. Kwa kuhesabu kutoka mbele—wa 1, wa 2, wa 3—hili linahusisha watoto 3, pamoja na wa 3 mwenyewe. Kutoa hawa 3 kutoka jumla ya 5 kunabakisha 2. Yaani nyuma ya mtoto wa 3 wamesimama wa 4 na wa 5—‘watoto 2’. Nguvu ya kufahamu mpangilio na nafasi kwa usahihi kwa namba ni hekima muhimu unaposimama kwenye foleni kwenye kundi kupata kitu, au kuheshimu zamu yako kwa haki katika jamii." },
  { id:73, topic:"Kanuni ya maumbo", emoji:"🔺",
    question:"Kitendawili cha sifa za maumbo. Ni umbo gani unaweza kutengeneza kwa kuunganisha ‘fimbo 3 zilizonyooka’ bila nafasi?",
    choices:["Duara","Pembetatu","Mraba","Nyota"],
    answerIndex:1,
    explanation:"Hiki ni kitendawili cha kanuni za msingi za kutengeneza maumbo. Kwa kutumia fimbo 3 zilizonyooka (pande) na kuunganisha ncha zake bila nafasi, daima unatengeneza ‘pembetatu’ yenye pembe 3. Kwa fimbo 4 unapata mraba, na duara hutengenezwa kwa mstari uliopinda, si fimbo zilizonyooka. Kama tulivyojifunza katika pakiti ya makanika iliyopita, pembetatu ni umbo imara zaidi duniani—halipotoshi kamwe chini ya nguvu kutoka juu. Kujua uhusiano kati ya idadi ya fimbo na umbo ni msingi wa kujenga nyumba imara na kubuni vitegemezo salama vya vitu." },
  { id:74, topic:"Kanuni ya namba", emoji:"🔢",
    question:"Kitendawili cha jinsi namba zinavyoongezeka. ‘2, 4, 6, 8, 10’ zimepangwa. Kwa kufuata kanuni hii, namba gani inafuata baada ya 10?",
    choices:["11","12","13","15"],
    answerIndex:1,
    explanation:"Hii ni mazoezi ya akili ya kutafuta ‘kanuni (mfululizo)’ ambapo namba zinaongezeka kwa kiasi maalum. Ukiangalia kwa makini, kutoka 2 hadi 4 imeongezeka ‘2’. Kutoka 4 hadi 6 pia imeongezeka ‘2’. Yaani safu hii ya namba inafuata kanuni ya ‘kuongezeka 2 kila hatua’. Ili kupata namba baada ya 10, ongeza tu ‘2’ ya kanuni kwa 10, hivyo 10 jumlisha 2 ni 12. Unapoweza kung'amua sheria ambapo namba zinaongezeka au kupungua kwa kanuni maalum, inakuwa rahisi sana kutabiri ukuaji wa kila siku wa mmea au kuelewa kanuni za tarehe kwenye kalenda." },
  { id:75, topic:"Nusu", emoji:"🫘",
    question:"Unataka kugawanya maharagwe uliyovuna shambani mwako kwenye vikapu 2, ‘idadi sawa kila kimoja’, nusu kwa nusu kabisa. Kama kuna maharagwe 12 jumla, unaweka mangapi kila kikapu?",
    choices:["4 kila kimoja","6 kila kimoja","8 kila kimoja","12 kila kimoja"],
    answerIndex:1,
    explanation:"Kugawanya namba katika kiasi viwili sawa kabisa kunaitwa ‘nusu’. Ukigawa maharagwe 12 kwenye vikapu 2 moja moja kwa zamu, kila kikapu kinapata idadi sawa ya maharagwe. Ukimaliza kuyagawa yote na kuhesabu, kila kikapu kina ‘maharagwe 6’ kamili. Kwa kuwa 6 jumlisha 6 ni 12, nusu ya 12 ni 6. Unaposhiriki chakula au mavuno na familia na marafiki, kuweza kuhesabu nusu ni hekima ya upole inayozuia ugomvi na kukuwezesha kugawana kwa haki, mkijaliana." },
  { id:76, topic:"Mizani", emoji:"⚖️",
    question:"Kitendawili cha kulinganisha uzito. Upande wa kushoto wa ‘mizani’ unaweka tufaha 1, na inalingana sawasawa wakati kuna mawe madogo 4 upande wa kulia. Ili kulingana na uzito wa tufaha 2, unahitaji mawe mangapi jumla?",
    choices:["Mawe 2","Mawe 4","Mawe 6","Mawe 8"],
    answerIndex:3,
    explanation:"Hii ni hekima ya kuhesabu mizani ya uzito (uwiano). Uzito wa tufaha 1 ni sawasawa na mawe 4. Sasa nini kinatokea tufaha zikiongezeka hadi 2? Kwa kuwa tufaha zimeongezeka maradufu, idadi ya mawe yanayohitajika kuyalinganisha nayo lazima nayo yaongezeke maradufu, vinginevyo mizani inavurugika. Yaani unahitaji seti nyingine sawa na mawe 4. Kwa kuhesabu 4 jumlisha 4, au 4 zidisha 2, jibu ni 8. Unaponunua na kuuza, nguvu ya kupima na kulinganisha sawasawa ni maarifa muhimu sana ya kuepuka kudanganywa kwa kiasi kidogo kisicho cha haki." },
  { id:77, topic:"Kugundua uongo", emoji:"🧩",
    question:"Kitendawili cha mantiki cha kupata nani anasema uongo. Kuna watu wawili, A na B. A anasema: ‘Mimi sisemi uongo.’ B anasema: ‘A anasema uongo.’ Kama anachosema A ni [kweli], je B anasema uongo au kweli?",
    choices:["B anasema uongo","B anasema kweli","Wote wawili wanasema uongo","Haiwezi kubainika"],
    answerIndex:0,
    explanation:"Hiki ni kitendawili cha mantiki cha kiwango cha juu kidogo cha kupata utata katika maneno. Sharti la kitendawili linasema ‘anachosema A ni kweli’. Maana yake A ni mtu mwaminifu asiyesema uongo kweli. Lakini bado B anasema ‘A anasema uongo’. Kwa kuwa B anamshtaki A mkweli kuwa mwongo, ni maneno ya B ndiyo ‘makosa (uongo)’. Hivyo jibu sahihi ni ‘B anasema uongo’. Katika jamii, nguvu ya kupanga kichwani maneno gani ni sahihi na yapi yanapingana na ukweli ni muhimu sana kwa kujilinda." },
  { id:78, topic:"Manunuzi ya faida", emoji:"🪵",
    question:"Kitendawili cha kulinganisha kipi chenye faida zaidi. Duka linauza mafungu 2 ya kuni. Fungu A lina ‘vijiti 5 kwa sarafu 10’. Fungu B lina ‘vijiti 3 kwa sarafu 10’. Ukilipa sarafu 10 zile zile, lipi linakupa kuni zaidi na lina faida?",
    choices:["Fungu A","Fungu B","Yote sawa","Yote hasara"],
    answerIndex:0,
    explanation:"Hii ni hadithi ya manunuzi kuhusu kulinganisha kwa busara ‘kiasi’ unachopata kwa bei ile ile. A na B vyote vinagharimu ‘sarafu 10’ zile zile kabisa. Lakini kuchagua A kunakupa vijiti 5, ilhali kuchagua B kunakupa 3 tu. Kwa kulinganisha 5 na 3, 5 ni zaidi kwa 2, hivyo kwa pesa zile zile, kununua A kunakupa kuni zaidi na ni ‘faida zaidi’. Kuweza kuhukumu mwenyewe kipi ni faida na kipi ni hasara kwa kulinganisha namba unaponunua ni hekima kubwa ya kutumia pesa na rasilimali zako finyu kwa uangalifu na kuifanya maisha yawe na neema zaidi." },
  { id:79, topic:"Bado kiasi gani", emoji:"🏺",
    question:"Kuna mtungi mkubwa wa maji. Unachukua ‘ndoo 5’ za maji kamili. Sasa mtungi tayari una ndoo 2 za maji. Ili kujaza mtungi kabisa, unahitaji kuongeza ndoo ngapi za maji?",
    choices:["Ndoo 2","Ndoo 3","Ndoo 5","Ndoo 7"],
    answerIndex:1,
    explanation:"Hii ni matumizi ya kutoa—kuhesabu bado kiasi gani (tofauti) unahitaji kufikia kiasi unacholenga. Jumla ya kujaza mtungi ni ndoo 5. Kwa kuwa ndoo 2 tayari ziko ndani, ili kupata nafasi tupu iliyobaki, toa 2 za sasa kutoka jumla ya 5. Kwa kuhesabu 5 ondoa 2, jibu ni 3. Yaani kuongeza ndoo 3 zaidi kunajaza mtungi sawasawa bila kufurika. Katika kupika, kilimo na kazi, nguvu ya kuhesabu kwa usahihi ‘bado kiasi gani kinahitajika’ kuelekea lengo ni hekima ya lazima ya kuepuka upotevu na kujiandaa kwa ufanisi." },
  { id:80, topic:"Kasi", emoji:"⏱️",
    question:"Kitendawili cha kulinganisha muda. Marafiki watatu—A, B na C—walikimbia mbio. Muda kila mmoja alichukua kufika lengoni: A sekunde 10, B sekunde 8, C sekunde 12. Nani alikuwa ‘mwepesi zaidi’?",
    choices:["A","B","C","Wote kwa kasi sawa"],
    answerIndex:1,
    explanation:"Hiki ni kitendawili cha mantiki cha kuelewa vizuri maana ya namba za muda. Katika mbio, kuwa ‘mwepesi’ maana yake ‘kuchukua muda mfupi zaidi (namba ndogo zaidi)’ kufika lengoni. Anayechukua muda mwingi alikimbia polepole zaidi. Kwa kulinganisha muda wote watatu—sekunde 12, 10, 8—namba ndogo zaidi ni ‘sekunde 8’ za B. Yaani kwa kuwa B alifika lengoni kwa muda mfupi zaidi, B alikuwa mwepesi zaidi. Kuelewa hali ambapo namba kubwa haimaanishi ushindi pia ni hatua muhimu ya fikira katika hesabu na maisha ya kila siku." },
  { id:81, topic:"Ugunduzi wa moto", emoji:"🔥",
    question:"Watu wa kale walipojifunza kutumia ‘moto’ vizuri, ni nini kilichokuwa salama zaidi maishani mwao?",
    choices:["Kuona mbali hata katika giza la usiku","Kwa kuchoma nyama na samaki kula, walizuia magonjwa ya tumbo na kuweza kujilinda dhidi ya wanyama wakali","Kuosha nguo ziwe safi","Kukimbia haraka zaidi"],
    answerIndex:1,
    explanation:"Kwa watu wa kale, kugundua moto na kujifunza kuudhibiti kwa uhuru ilikuwa maendeleo makubwa zaidi ya kulinda maisha. Nyama na mimea, ngumu na yenye vijidudu vingi ikiwa mbichi, ziliweza kubadilishwa kuwa chakula laini, rahisi kumeng'enywa na salama kisichoharibu tumbo, kwa ‘kuzipasha joto (kupika)’ motoni. Pia, kwa kuweka moto ukiwaka katika giza la usiku, wanyama wakali wa kutisha wanaowashambulia binadamu waliuogopa na kuacha kukaribia, hivyo watu waliweza kulala kwa amani usiku pia. Moto ulikuwa njia ya kwanza na bora zaidi ya ulinzi ya binadamu kuishi katika asili kali." },
  { id:82, topic:"Nguvu ya maandishi", emoji:"📜",
    question:"Kwa kuvumbua ‘maandishi’, kwa nini jamii za dunia nzima zikawa na busara zaidi?",
    choices:["Sauti yako inafika kwa mtu wa mbali bila kuzungumza","Bila kuweka kila kitu kichwani tu, maarifa muhimu na sheria (makubaliano) yaliweza kufikishwa kwa usahihi kwa watu wengi kwa muda mrefu","Kuchora kukawa hakuna haja kabisa","Kuandika herufi kunafanya pesa ziongezeke zenyewe"],
    answerIndex:1,
    explanation:"Katika enzi kabla ya maandishi, binadamu hawakuwa na njia nyingine ila kukariri na kurithisha busara na historia yote kwa ‘mdomo kwa mdomo (kusimulia hadithi)’ tu. Lakini kwa njia hii maudhui yangeweza kusahaulika njiani au kupitishwa kimakosa. Hapa binadamu walivumbua hekima ya kuchonga ‘maandishi’ kwenye vibao vya udongo na mawe. Kwa hili, waliweza kuwaachia vizazi vya mamia ya miaka baadaye, bila kosa hata dogo, mambo kama njia ya kutambua mimea salama, kanuni za jamii ambazo wote lazima wazishike (sheria), na kumbukumbu za makosa ya zamani. Maandishi ni mashine kuu zaidi ya wakati ya kushiriki na kuhifadhi pamoja maarifa ya binadamu wote, ikipita mipaka ya kumbukumbu ya binadamu." },
  { id:83, topic:"Gurudumu", emoji:"🛞",
    question:"‘Gurudumu (mviringo)’ lililovumbuliwa zamani—kwa nini lilirahisisha sana usafiri na kazi za binadamu?",
    choices:["Umbo la mviringo hupunguza nguvu ya breki (msuguano) ya kusugua ardhini, hivyo mizigo mizito inaweza kuviringishwa na kubebwa kwa nguvu kidogo","Kuweka magurudumu kunafanya mzigo uelee angani","Maji mengi hukusanyika ndani ya gurudumu","Linaonekana zuri zaidi kuliko mzigo wa mraba"],
    answerIndex:0,
    explanation:"Kama tulivyojifunza katika pakiti ya makanika iliyopita, kuburuta kitu kizito moja kwa moja ardhini hutengeneza breki yenye nguvu iitwayo ‘msuguano’. Lakini kutokana na uzoefu wa ‘kuviringisha gogo la mviringo’, binadamu walipata hekima ya kuweka pete ya mviringo inayozunguka (gurudumu) kwenye gari. Kwa magurudumu, kuni, mawe na chakula chenye uzito wa mamia ya kilo ambacho hata watu wazima 10 hawakuweza kukisogeza, kiliweza kupakiwa kwenye gari na kubebwa kwa urahisi mbali na mtu mmoja tu. Ni kwa sababu ya uvumbuzi wa gurudumu ndipo binadamu waliweza kufanya biashara ya bidhaa nyingi na miji ya mbali na kuendeleza jamii yenye neema." },
  { id:84, topic:"Uvumbuzi wa karatasi", emoji:"📄",
    question:"‘Karatasi’ iliyovumbuliwa China ya kale, ilikuwa ya ajabu ikilinganishwa na jiwe, ngozi za wanyama na vibao vya udongo vilivyotumika kabla. Kwa nini?",
    choices:["Ni nyepesi sana na nyembamba na inaweza kukunjwa, hivyo vitabu vingi viliweza kutengenezwa kwa bei rahisi na kubebwa","Karatasi haichaniki kamwe hata ikilowa","Kula karatasi hujaza tumbo","Ni ngumu zaidi kuchonga na imara kuliko jiwe"],
    answerIndex:0,
    explanation:"Kabla ya karatasi kuvumbuliwa, watu waliandika herufi kwenye ‘jiwe’ au ‘vibao vya udongo’ vizito, au kwenye ‘ngozi za wanyama’ za thamani na ghali. Hivi vilikuwa vizito mno kubebwa mbali, hivyo ni watu wachache tu wenye cheo au matajiri walioweza kusoma vitabu. Lakini ‘karatasi’—iliyotengenezwa kwa kushindilia nyuzi za mmea ziwe bapa na kuzigumisha—ilipojitokeza, vitabu viliweza kutengenezwa vyepesi kwa kushangaza, vyembamba, vya bei rahisi na vingi. Kutokana na hili, maarifa ya madaktari na vitabu vya shule vilifika kwa watu wa kawaida na watoto duniani kote, na kiwango cha elimu na tiba cha binadamu wote kilipanda kwa kasi kubwa." },
  { id:85, topic:"Kilimo", emoji:"🌾",
    question:"Binadamu walipohama kutoka maisha ya kutafuta mawindo msituni hadi kulima ardhi na kuanza ‘kilimo’, maisha yalibadilikaje?",
    choices:["Bila kusafiri kila siku kwenda misitu ya mbali yenye hatari, waliweza kuendelea kuishi mahali pamoja (kukaa) na kuvuna chakula kingi kwa uthabiti","Kwa kuwa hawakuhitaji tena kukimbia kila siku, miili ya wote ikawa midogo","Hawakuhitaji tena kujali hali ya hewa hata kidogo","Waliacha kujenga nyumba na kurudi mapangoni"],
    answerIndex:0,
    explanation:"Kabla ya kilimo kuanza, binadamu walichuma matunda na kufuata wanyama, wakiendelea na safari ya hatari ya kuhamia mahali panapofuata chakula kilipoisha. Lakini kwa kuvumbua ‘kilimo’—kupanda mbegu, kumwagilia na kukuza mimea kwa mpango—binadamu waliweza kujenga nyumba imara na ‘kukaa’ mahali pamoja. Zaidi ya hayo, kwa kuwa waliweza kuvuna na kuhifadhi ngano na mahindi mengi kwa mara moja, hatari ya kufa kwa njaa ilipungua, na msingi ukawekwa wa watu wengi kuungana nguvu na kujenga vijiji na miji mikubwa na kuishi kwa usalama." },
  { id:86, topic:"Mwanzo wa nguo", emoji:"🧵",
    question:"Kwa nini binadamu walianza kutengeneza ‘nguo’ zao wenyewe kwa kusokota nyuzi za mmea na sufi ya kondoo?",
    choices:["Kushindana urembo na marafiki na kugombana","Kulinda ngozi yao na joto la mwili dhidi ya jua kali, baridi kali, nyasi zenye miiba na sumu ya wadudu","Kwa sababu huwezi kuelea majini bila nguo","Kuficha chakula kingi ndani ya nguo"],
    answerIndex:1,
    explanation:"Ngozi ya binadamu haina makucha makali wala manyoya manene kama ya mnyama, hivyo ni laini sana na rahisi kujeruhiwa. Binadamu walisokota uzi, wakafuma ‘kitambaa’ na kutengeneza ‘nguo’ za kujifunga mwilini ili kutengeneza ngao ya ulinzi inayolinda maisha dhidi ya asili kali. Kuvaa nguo hulinda joto la mwili dhidi ya baridi kali ya majira ya baridi, huzuia kuungua kwa jua kali la kiangazi, na hukinga dhidi ya miiba mikali ya nyasi na kuumwa na wadudu wabebao magonjwa kama mbu. Nguo ni ‘ngozi ya pili’ ambayo binadamu waliumba kwa busara yao, na chombo cha lazima cha kutenda kwa usalama." },
  { id:87, topic:"Makazi", emoji:"🏠",
    question:"Lengo kubwa zaidi la kutoka mapangoni na kujenga ‘nyumba (makazi)’ mwenyewe kwa udongo, mbao na mawe lilikuwa lipi?",
    choices:["Kutengeneza vyumba vingi na kucheza kujificha","Kulinda kwa uhakika maisha na mali ya familia dhidi ya mvua, upepo, joto na baridi kali, na wanyama wa porini wanaoshambulia usiku","Kuchimba ardhi na kutengeneza vyumba vingi vya chini","Kushindana urefu wa nyumba na kuwakaribia miungu"],
    answerIndex:1,
    explanation:"Kuwa nje porini moja kwa moja kunakuweka daima kwenye hatari kama mvua kubwa ya ghafla, upepo wa baridi wa usiku, na wanyama wa porini walao nyama wanaoshambulia chini ya giza. Binadamu walianza kutengeneza matofali kwa kukausha udongo juani na kujenga ‘nyumba (makazi)’ kwa kuunganisha mbao na mawe, ili kuzuia kila hatari ya dunia ya nje na kuhakikisha nafasi salama. Paa huzuia mvua na upepo, na kuta imara na mlango huwaweka maadui nje. Hekima ya kujenga mwenyewe ‘kimbilio salama’, ambapo unaweza kulala fofofo na kupumzisha mwili uliojeruhiwa au mgonjwa, imeyaweka maisha ya binadamu hai." },
  { id:88, topic:"Vyombo vya chuma", emoji:"⚒️",
    question:"Kwa kuhama kutoka vyombo vya mawe hadi vyombo vya ‘chuma na madini’ vilivyoyeyushwa motoni, ni nini kilichoendelea?",
    choices:["Vyombo vikawa vyepesi na kuelea majini","Badala ya kuvunjika kwa urahisi kama jiwe, viliweza kutengenezwa vyombo na zana za kilimo imara sana, vikali na vya kudumu","Vyombo vya madini hugeuka dhahabu vikisuguliwa","Vyombo vikawa laini na kubadilisha umbo kwa uhuru"],
    answerIndex:1,
    explanation:"Mashoka na visu vilivyotengenezwa kwa jiwe vilikuwa na udhaifu: vikipigwa kwa nguvu kwenye kitu kigumu, vilivunjika vipande kwa urahisi. Lakini binadamu waligundua kwamba, ukichoma miamba fulani katika moto wa joto kali sana, kioevu kizito (madini) huyeyuka kutoka ndani, ambacho kikipozwa kinakuwa imara zaidi kuliko jiwe. Huu ulikuwa mwanzo wa ‘shaba’ na ‘vyombo vya chuma’. Vyombo vya chuma havikuvunjika kamwe hata vikianguka, na viliwezesha kukata miti mikubwa migumu na kuchimba ardhi ngumu kwa kina kuifanya mashamba. Ilikuwa mapinduzi ya ajabu ya teknolojia yaliyowezesha kufanya kazi nzito zaidi kwa usalama na kwa nguvu kidogo." },
  { id:89, topic:"Meli ya tanga", emoji:"⛵",
    question:"Binadamu walipotengeneza ‘meli ya tanga (meli kubwa)’ kwa kupandisha tanga kubwa la kitambaa, usafiri ulibadilikaje?",
    choices:["Bila kupiga makasia kwa mikono, tanga hunasa ‘nguvu ya upepo’ ya asili, hivyo waliweza kuvuka bahari na kubeba mizigo mikubwa hadi mabara ya mbali","Meli iliweza kuruka angani yenyewe","Meli haikuyumba kamwe hata dhoruba ikija","Waliweza kusafisha maji ya bahari wakati wakienda"],
    answerIndex:0,
    explanation:"Mashua ndogo za zamani ziliweza kwenda tu kwa kupiga makasia kwa mikono. Kwa njia hii nguvu ya binadamu ilifika kikomo haraka, na kuvuka bahari pana yenye mawimbi makali ilikuwa haiwezekani. Hivyo binadamu walivumbua ‘meli ya tanga’, kwa kupandisha ukuta mkubwa wa kitambaa (tanga) kwenye meli ili kunasa ‘nishati ya upepo’ unaovuma juu ya dunia na kwenda mbele. Kwa kutumia nguvu ya upepo wa asili badala ya misuli ya binadamu, waliweza kusafiri kwa usalama bila kupumzika kwa siku nyingi, wakibeba tani nyingi za chakula na vifaa vizito, hadi nchi za maelfu ya kilomita ng'ambo ya bahari, na kubadilishana busara na utamaduni wa kila mmoja." },
  { id:90, topic:"Saa na wakati", emoji:"🕰️",
    question:"Kwa nini binadamu walianza kupima ‘saa na wakati’ kwa undani kwa kutumia kivuli kinachosogea cha jua (saa ya jua) na mtiririko wa maji?",
    choices:["Ili kila mtu aweze kuharakisha na kukimbia","Ili kuoanisha kwa usahihi kati ya wote makubaliano ya jamii kama ‘lini kukutana’ na ‘lini kubadilishana zamu’, na mipango ya kazi","Ili waamue wenyewe lini watahisi njaa","Ili kulazimisha usiku kuwa mchana"],
    answerIndex:1,
    explanation:"Katika dunia ambapo wakati umetawanyika na haulingani, hata kwa watu wengi, makubaliano ya kushirikiana kama ‘kukutana mahali pale adhuhuri na kuinua gogo zito pamoja’ hayasimami. Wengine wanafika mapema mno, wengine wanachelewa, na inakuwa isiyo na ufanisi sana. Binadamu walivumbua ‘saa’ na kuanza kugawanya siku kuwa asubuhi, adhuhuri na usiku, na kuwa saa—seti ya namba ya pamoja—mahususi ili kufanya ‘makubaliano (uoanishaji wa jamii)’ ya jamii kuwa sahihi. Kwa hili, waliweza kuamua nyakati za kubadilishana kazi kwa haki na kupanga kurudi nyumbani kwa usalama kabla ya usiku wa hatari kufika, wakioanisha kwa upole vitendo vya wote." },
  { id:91, topic:"Kalenda", emoji:"📅",
    question:"Kutengeneza ‘kalenda’ kwa kuangalia mwendo wa nyota na jua—kwa nini ilikuwa muhimu kwa kilimo hadi maisha yakategemea?",
    choices:["Kwa sababu kupindua tarehe kila siku ni furaha","Ili kutabiri mapema lini ‘msimu wa mvua’ au ‘baridi kali’ utafika, kupanda mbegu kwa wakati sahihi, na kuandaa chakula","Kwa sababu unapata nguvu ya kubadilisha hali ya hewa kwa hiari yako","Kwa sababu kuangalia kalenda hufanya mmea ulio mbele yako ukue haraka"],
    answerIndex:1,
    explanation:"Katika kilimo, kukosea wakati wa kupanda mbegu maana yake mavuno yawe sufuri na kijiji kizima kife kwa njaa. Ukipanda mbegu kabla tu ya baridi, vyote vinanyauka kwa baridi. Zamani sana, watu waligundua kwamba mpangilio wa nyota zing'aazo angani usiku, na mahali jua linapochomoza, vinabadilika kwa kanuni maalum na ya kawaida mwaka mzima. Kufupisha mzunguko huu wa dunia kwenye karatasi ndiyo ‘kalenda’. Kwa kuitumia, hata wakati bado ni joto, waliweza kusoma ya baadaye—‘msimu wa mvua unaisha baada ya wiki chache, hivyo panda sasa’—na kuzalisha chakula kwa usalama, wakitumia vyema baraka za asili." },
  { id:92, topic:"Mwanzo wa pesa", emoji:"💰",
    question:"Faida ya kuacha kubadilishana vitu kwa vitu moja kwa moja (kubadilishana bidhaa) na kuanza kutumia ‘pesa (sarafu)’ za makombe au madini ni ipi?",
    choices:["Kwa sababu kuwa na pesa kunafanya wezi waache kukushambulia","Hata kati ya watu ‘wanaotaka vitu tofauti’, kama mwenye samaki na mwenye nyama, kuweka pesa katikati kunawawezesha kufanya biashara kwa haki ya wanachotaka wakati wowote","Kwa sababu kula pesa kunakuwa lishe","Kwa sababu pesa zimetapakaa kila mahali bila kikomo"],
    answerIndex:1,
    explanation:"Katika maisha ya ‘kubadilishana bidhaa’, hata ukitaka kubadilisha samaki wako na nguo za mtu, biashara haitimii isipokuwa mtu huyo anataka samaki. Pia, kwa kuwa samaki huoza haraka, huwezi kuhifadhi thamani yake. Hivyo binadamu waliumba chombo cha pamoja ambacho wote wanakubali thamani yake: ‘pesa (sarafu)’. Ukibadilisha samaki kuwa pesa mara moja, unaweza kuzihifadhi bila kuoza na baadaye katika mji mwingine kununua nguo au dawa—chochote unachohitaji, wakati unapohitaji. Mfumo wa pesa ni hekima bora ya uchumi, iliyovumbuliwa ili watu duniani kote waweze kusaidiana (kufanya biashara) kwa urahisi na haki bila usumbufu." },
  { id:93, topic:"Uchapishaji", emoji:"📚",
    question:"Uvumbuzi wa ‘uchapishaji wa herufi zinazohamishika’—kuunganisha herufi moja moja kuchapisha vitabu vingi—uliibadilishaje dunia?",
    choices:["Juhudi ya kunakili kila herufi kwa mkono ilikwisha, vitabu viliongezeka kwa kasi kubwa, na si wafalme tu, bali mtu yeyote angeweza kujifunza maarifa na sayansi","Uzito wa vitabu ukawa mzito kama chuma","Herufi zote za dunia ziliunganishwa kuwa moja","Herufi zilizoandikwa vitabuni zilianza kuongea zenyewe"],
    answerIndex:0,
    explanation:"Kabla ya teknolojia ya uchapishaji, kutengeneza kitabu kipya, binadamu hawakuwa na njia nyingine ila kuangalia kila herufi kwa macho na ‘kuinakili kwa mkono kwenye karatasi nyingine (kunakili)’. Kutengeneza kitabu kimoja kulichukua miezi mingi, hivyo vitabu vilikuwa ghali kama nyumba, na watu wa kawaida na watoto hawakuweza hata kusoma. ‘Uchapishaji wa herufi zinazohamishika’, ulioendelezwa na mafundi wa Ujerumani na kwingineko, ni teknolojia inayopanga mihuri ya herufi za madini na kuchapisha kurasa nyingi papo hapo kwa mashine ya kukandamiza. Kwa hili, bei ya vitabu ilishuka kwa kasi, na mtu yeyote duniani angeweza kupata ‘vitabu vya busara’ vya tiba, kilimo na hesabu kujifunza—mapinduzi makubwa yaliyopunguza hofu na magonjwa yatokanayo na ujinga." },
  { id:94, topic:"Mfumo wa maji", emoji:"🚰",
    question:"Mfumo wa ‘usambazaji wa maji (mfereji wa maji)’ uliojengwa Roma ya kale na kwingineko, ulioleta maji safi kutoka mto wa mbali hadi mjini—kwa nini uliokoa maisha mengi?",
    choices:["Kwa sababu wangeweza kutengeneza mabwawa mengi safi ndani ya nyumba","Kwa sababu watu hawakuhitaji tena kunywa maji machafu yaliyochanganyika na matope na vijidudu, jambo lililozuia magonjwa ya kuambukiza ya kutisha katika mji mzima","Kwa sababu kuoga kwa maji ya bomba huponya jeraha papo hapo","Kwa sababu hawakuhitaji tena kuogelea hadi mtoni kucheza"],
    answerIndex:1,
    explanation:"Katika miji mikubwa ambapo watu wanaishi wamebanana, takataka na uchafu vilichanganyika kwa urahisi na visima na mito ya karibu, na maji yalichafuka sana—tatizo kubwa. Kunywa maji machafu kulieneza magonjwa ya kuambukiza ya kutisha kama kipindupindu katika mji mzima papo hapo, yakichukua maisha ya makumi ya maelfu. Wajenzi wa kale walitengeneza teknolojia ya kuleta ‘maji safi na salama ya chemchemi’ kutoka milima ya kilomita nyingi mbali, hadi mjini, kupitia madaraja ya mawe (mifereji ya maji) yenye mteremko mpole. Kutengeneza mazingira ambapo wote wangeweza daima kunawa mikono kwa maji safi na kunywa maji salama kukawa ngao imara zaidi ya kulinda maisha ya mji dhidi ya magonjwa." },
  { id:95, topic:"Darubini ndogo", emoji:"🔬",
    question:"Kwa uvumbuzi wa ‘darubini ndogo (hadubini)’, chombo kinachounganisha lenzi za kioo za mviringo, madaktari na sayansi vilivyoendeleaje?",
    choices:["Waligundua sura ya ‘vijidudu (bakteria)’ vidogo, chanzo cha magonjwa, visivyoonekana kabisa kwa jicho la binadamu, na wakaweza kutibu na kuzuia kwa usahihi","Sura za nyota za mbali zikaonekana wazi","Chakula kiliweza kufungwa ndani ya kioo","Uliweza kuona mandhari ya kuzunguka hata macho yamefumba"],
    answerIndex:0,
    explanation:"Hadi hadubini, binadamu hawakujua sababu za kweli za kwa nini watu wanaugua au kwa nini chakula kinaoza. Iliaminika ni kosa la mizimu mibaya au laana zisizoonekana, na watu wengi walipoteza maisha kwa matibabu yasiyo sahihi. Lakini kwa uvumbuzi wa ‘hadubini’, inayokuza dunia ndogo mara mamia kwa nguvu ya lenzi, binadamu hatimaye waliona kwa macho yao wenyewe mhalifu anayeoza maji na kusababisha magonjwa mwilini: ‘vijidudu na viumbe vidogo’. Utambulisho wa adui ulipojulikana, historia ya tiba sahihi ya kinga inayolinda maisha kwa uhakika ilianza: ‘kuchemsha maji kuyaua vijidudu’, ‘kunawa mikono’." },
  { id:96, topic:"Dira", emoji:"🧭",
    question:"‘Dira’, ambayo sindano yake ya sumaku daima inaelekeza kaskazini—uvumbuzi wake uliwasaidiaje wale waliosafiri katika bahari ya giza usiku au jangwani?",
    choices:["Hata mahali ambapo huoni mandhari ya kuzunguka kabisa, unajua ‘mwelekeo sahihi’ unaoenda na kuepuka kupotea","Kwa nguvu ya sumaku meli ikawa haraka mara nyingi","Iliacha mchanga wote wa jangwa na kutengeneza njia safi","Sindano ilibadilisha hali ya hewa kuwa ya jua yenyewe"],
    answerIndex:0,
    explanation:"Katika ‘bahari pana iliyo wazi’ au ‘jangwa lisilo na mwisho’, ambapo digrii zote 360 zinaonekana sawa, au unaposogea katika ukungu mzito au usiku wa giza nene, ndio wakati wa hatari zaidi na wa kutisha, unapopoteza mwelekeo unaopaswa kwenda. Binadamu waligundua tabia ya ajabu kwamba sindano fulani ya sumaku ‘daima inaelekeza imara kaskazini’ kwa nguvu ya sumaku ya dunia isiyoonekana, na wakaiweka kwenye chombo. Hii ndiyo dira. Kwa kuishika, hata bila dalili za hali ya hewa au alama, unajua kwa usahihi wa asilimia 100 kama unaelekea mashariki au magharibi, hivyo iliwezekana kuepuka kabisa maafa ya kupotea na kuangamia maji na chakula vinapoisha." },
  { id:97, topic:"Umeme", emoji:"💡",
    question:"Binadamu walipotengeneza teknolojia ya kuzalisha ‘umeme’ na kuusafirisha kwa nyaya, maisha ya usiku ya watu yalivyokuwa salama zaidi vipi?",
    choices:["Kwa balbu, waliweza kuwasha mwanga salama na angavu bila hatari ya kuanzisha moto ndani ya chumba","Usiku ulifupika wenyewe na asubuhi ikaja haraka","Maji mengi yalitiririka kutoka nyayani","Kuta za nyumba zikawa imara kama chuma"],
    answerIndex:0,
    explanation:"Kabla umeme kuenea, mwanga pekee wa usiku ulikuwa ni ‘kuwasha moto moja kwa moja’ kwenye mishumaa, mafuta au gesi. Hivyo, ukiangushwa na upepo au kusahau kuuzima, ukawa moto mkubwa ulioteketeza nyumba papo hapo, na watu wengi walipoteza maisha. Pia, kwa kuwa mwanga ulikuwa hafifu, kufanya kazi usiku ilikuwa hatari sana. Tangu binadamu walipobadilisha nishati kuwa umeme na kuwasha ‘balbu’, waliweza kupata ‘mwanga salama angavu kama jua’ usiotoa moshi na usioanzisha moto kamwe hata ukiangushwa, kwa kubonyeza kitufe kimoja. Ni teknolojia kuu iliyopunguza kwa kasi uhalifu na majeraha ya usiku na inayolinda usalama wa jamii saa 24." },
  { id:98, topic:"Mawasiliano", emoji:"📞",
    question:"Mawasiliano yalipoendelea kutoka ‘ishara za moshi’ na ‘barua’ hadi ‘telegrafu na simu’ zinazofikisha ujumbe kwa ishara za umeme, ni nini kilichoboreka zaidi?",
    choices:["Maana ya maneno ilibadilika kuwa Kiingereza yenyewe","Bila kukimbia siku nyingi kumwita mtu, ‘hatari ya dharura (SOS)’ kama mvua kubwa au tetemeko la ardhi ingeweza kufikishwa mji wa mbali papo hapo kuomba msaada","Kupiga simu kulifanya mizigo iruke mbele yako","Uzito wa rafiki yako ukawa mwepesi"],
    answerIndex:1,
    explanation:"Wakati maafa makubwa au adui ulipokaribia mji wa mbali, zamani njia pekee ilikuwa kukimbiza farasi au kumtuma mtu akimbie kufikisha barua, jambo lililochukua siku nyingi, na mara nyingi ilipofika ilikuwa tayari imechelewa mno. Kwa kuvumbua ‘telegrafu’ na ‘simu’ zinazobeba maneno na ishara kwenye mawimbi ya umeme, taarifa ingeweza kufika upande mwingine wa dunia kwa ‘kasi kubwa kama ya mwanga’, ikipita kasi ya miguu ya binadamu. Kwa hili, SOS inayookoa maisha—‘mlima unakaribia kuporomoka, kimbia sasa!’, ‘mtu amejeruhiwa vibaya, tuma daktari!’—ingeweza kufikishwa kwa sekunde moja, na idadi ya maisha yanayoweza kuokolewa iliongezeka kwa kiasi kikubwa." },
  { id:99, topic:"Maendeleo ya tiba", emoji:"💉",
    question:"Madaktari walipotengeneza mbinu za ‘sindano (chanjo)’ na ‘kuua vijidudu kwenye vyombo’, maisha ya binadamu yalilindwaje?",
    choices:["Mifupa ya binadamu ikawa migumu kama chuma","Watoto wadogo na watu wengi waliokuwa wakifa kwa urahisi kwa sababu miili yao ilikuwa dhaifu, waliweza kuepuka magonjwa ya kutisha na kuishi muda mrefu na wenye afya","Hata wakijeruhiwa, damu haikutoka kabisa","Wagonjwa wote walikimbia mbali"],
    answerIndex:1,
    explanation:"Zamani sana, hata mtu awe na afya kiasi gani, mara jeraha dogo lilipoacha vijidudu viingie, au virusi vya kutisha kama ndui vilipoenea kijijini, kwa kukosa dawa wala kinga, watu wengi walipoteza maisha wakiwa wadogo, bila uwezo wa kuzuia. Wanasayansi wa tiba waligundua hekima ya ‘chanjo (kinga)’—kuweka mapema viungo salama mwilini ili kujenga ngao dhidi ya magonjwa—na ‘kuua vijidudu’, kwa kuangamiza vijidudu kwa sabuni na alkoholi. Kutokana na teknolojia hii ya tiba, uwezekano wa watoto wachanga na watoto duniani kote kuishi salama hadi utu uzima, bila kupoteza maisha njiani, uliruka mara nyingi." },
  { id:100, topic:"Maana ya kujifunza", emoji:"🦉",
    question:"Katika programu hii ‘Wise World’, ni nini [lengo halisi] la wewe kujifunza busara nyingi hivi za sayansi na historia?",
    choices:["Kupata alama 100 katika mtihani na kuwa bora kuliko wengine","Kuhifadhi kichwani hirizi bora zaidi—busara (maarifa)—kulinda maisha yako na ya wale wanaokuzunguka, na kushirikiana na wote kujenga na kuishi katika ‘dunia ya wema na salama’","Kukusanya pesa nyingi na kuishi kwa anasa peke yako","Kukusanya pointi za uzoefu (EXP) za jaribio, kumaliza mchezo na kuishia hapo"],
    answerIndex:1,
    explanation:"Hongera! Kwa hili swali la 100 la kukumbukwa limekamilika. ‘Vyombo, sayansi na busara ya historia’ yote ambayo binadamu wamekusanya kwa makumi ya maelfu ya miaka, kupitia kushindwa mara kwa mara na kwa kuhatarisha maisha yao, havipo kwa ajili ya kumdhulumu mtu wala kwa mtu mmoja kushikilia upendeleo na kujivuna. Ni hazina ya pamoja, iliyovumbuliwa ili binadamu wote—kwa kusaidia wenye uhitaji kweli, kuepuka hatari, kupita mipaka na lugha—waweze kuwekwa huru kutoka hofu ya magonjwa na njaa na ‘kuishi kwa wema, usalama na furaha (ustawi)’. Kwa dira ya busara uliyojifunza katika programu hii moyoni mwako, na uangaze kwa upole maisha yako mwenyewe na mustakabali wa dunia. Dunia nzima inaishangilia safari yako ya kujifunza!" }
];
